-- The Broken Seal: repair missing trousers and invalid rendering class defaults.
-- Generated by tools/generate_broken_seal_outfit_fix.py. Appearance only; no spawn/quest/stat changes.
-- Owned preset records only. Preserve valid custom classes, nonzero clothing and all spawn overrides.
-- After importing: .customnpc outfit reload
CREATE TABLE IF NOT EXISTS `mod_customnpcs_bs_content` (
  `kind` VARCHAR(16) NOT NULL, `entry` INT UNSIGNED NOT NULL, `chapter` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`kind`,`entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TEMPORARY TABLE IF EXISTS `bs_outfit_repairs`;
CREATE TEMPORARY TABLE `bs_outfit_repairs` (
  `id` INT UNSIGNED PRIMARY KEY, `race` TINYINT UNSIGNED, `gender` TINYINT UNSIGNED,
  `chest` INT, `legs` INT, `feet` INT
);
INSERT INTO `bs_outfit_repairs` (`id`, `race`, `gender`, `chest`, `legs`, `feet`) VALUES
  (4001000, 6, 0, 6569, 6568, 0),
  (4001001, 1, 0, 9748, 9747, 0),
  (4001002, 4, 0, 6085, 6596, 6573),
  (4001003, 1, 0, 6238, 10045, 0),
  (4001005, 4, 1, 2317, 5961, 2315),
  (4001006, 1, 1, 1433, 1431, 1427),
  (4001007, 2, 0, 85, 139, 140),
  (4001004, 1, 1, 1433, 1431, 0),
  (4001008, 6, 0, 6238, 10045, 0),
  (4001009, 4, 0, 85, 139, 0),
  (4001010, 1, 0, 2317, 5961, 2315),
  (4001011, 1, 0, 6085, 6596, 0),
  (4001200, 1, 1, 6238, 6568, 0),
  (4001201, 1, 0, 6238, 6568, 0),
  (4001202, 1, 1, 6238, 6568, 0),
  (4001203, 1, 0, 6238, 6568, 0),
  (4001204, 4, 0, 6085, 6596, 6573),
  (4001205, 6, 0, 6085, 6596, 6573),
  (4001206, 1, 0, 6238, 6568, 0),
  (4001207, 1, 0, 6238, 6568, 0),
  (4001208, 1, 0, 6238, 6568, 0),
  (4001209, 1, 0, 6238, 6568, 0),
  (4001212, 1, 0, 6238, 6568, 0),
  (4001215, 1, 0, 6238, 6568, 0),
  (4001219, 1, 0, 6238, 6568, 0),
  (4001220, 2, 0, 6238, 6568, 0),
  (4001225, 1, 0, 6238, 6568, 0),
  (4001227, 2, 0, 6238, 6568, 0),
  (4001228, 4, 0, 6238, 6568, 0),
  (4001400, 3, 0, 6238, 6568, 0),
  (4001401, 2, 0, 6085, 6596, 6573),
  (4001402, 6, 1, 6238, 6568, 0),
  (4001403, 6, 0, 2317, 6568, 2315),
  (4001404, 6, 1, 2317, 6568, 2315),
  (4001405, 3, 1, 6238, 10045, 2315),
  (4001408, 6, 0, 2317, 6568, 2315),
  (4001409, 1, 1, 2317, 6568, 2315),
  (4001410, 2, 1, 2317, 6568, 2315),
  (4001411, 6, 0, 6085, 6596, 6573),
  (4001412, 6, 1, 6238, 6568, 0),
  (4009000, 1, 0, 6085, 6596, 6573),
  (4009001, 1, 0, 6085, 6596, 6573),
  (4009002, 1, 0, 6569, 6568, 6573),
  (4009003, 1, 0, 6569, 6568, 6573),
  (4009004, 1, 0, 6569, 6568, 6573),
  (4009005, 1, 0, 6569, 6568, 6573),
  (4009006, 6, 0, 6085, 6596, 6573),
  (4009007, 3, 0, 6085, 6596, 6573),
  (4009050, 1, 0, 6238, 6568, 2315),
  (4009051, 1, 0, 6238, 6568, 2315),
  (4009052, 1, 0, 6238, 6568, 2315),
  (4009053, 1, 0, 6238, 6568, 2315),
  (4009054, 1, 0, 6238, 6568, 2315),
  (4009055, 1, 0, 6238, 6568, 2315),
  (4009056, 6, 0, 6238, 6568, 2315),
  (4009057, 3, 0, 6238, 6568, 2315);
START TRANSACTION;
UPDATE `mod_customnpcs_outfit` o
INNER JOIN `bs_outfit_repairs` r ON r.`id`=o.`outfit_id`
INNER JOIN `mod_customnpcs_bs_content` owner ON owner.`kind`='outfit' AND owner.`entry`=o.`outfit_id`
  AND owner.`chapter` IN (0,1,2,3)
SET o.`class`=1 WHERE o.`class`=0;
-- Fill empty clothing only when the record still has the preset's race/gender and chest.
UPDATE `mod_customnpcs_outfit` o
INNER JOIN `bs_outfit_repairs` r ON r.`id`=o.`outfit_id`
INNER JOIN `mod_customnpcs_bs_content` owner ON owner.`kind`='outfit' AND owner.`entry`=o.`outfit_id`
  AND owner.`chapter` IN (0,1,2,3)
SET o.`legs`=IF(o.`legs`=0,r.`legs`,o.`legs`), o.`feet`=IF(o.`feet`=0,r.`feet`,o.`feet`)
WHERE o.`race`=r.`race` AND o.`gender`=r.`gender` AND o.`chest`=r.`chest`;
COMMIT;
DROP TEMPORARY TABLE `bs_outfit_repairs`;
