-- mod-customNPCs: Cataclysm/MoP Orgrimmar appearances and Wrath placements.
-- Generated by tools/generate_orgrimmar_appearances.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql and the later_expansion_trainers.sql roster.
-- Native displays, armor textures, customization and weapons were checked in build 12340.
-- Only this roster is updated. Existing spawn GUIDs and per-spawn outfit overrides survive.
-- Restart worldserver after applying: model/equipment/addon/spawn caches must also reload.
-- See docs/orgrimmar-trainers.md for sources, substitutions and placement checks.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_orgrimmar_appearance`;
CREATE TEMPORARY TABLE `mod_customnpcs_orgrimmar_appearance` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `display_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL,
  `mainhand` INT UNSIGNED NOT NULL,
  `offhand` INT UNSIGNED NOT NULL,
  `ranged` INT UNSIGNED NOT NULL,
  `stand_state` TINYINT UNSIGNED NOT NULL,
  `sheath_state` TINYINT UNSIGNED NOT NULL
);

-- 4000005: Shalla Whiteleaf (source 44726, race 6, gender 1).
-- 4000006: Nohi Plainswalker (source 44743, race 6, gender 0).
-- 4000007: Conjurer Mixli (source 45714, race 9, gender 1).
-- 4000008: Sunwalker Atohmo (source 44725, race 6, gender 0).
-- 4000009: Seer Liwatha (source 44735, race 6, gender 1).
-- 4000010: Night-Stalker Ku'nanji (source 45095, race 8, gender 0).
-- 4000011: Sahi Cloudsinger (source 44740, race 6, gender 1).
-- 4000012: Unjari Feltongue (source 45138, race 8, gender 1).
-- 4000013: Blademaster Ronakada (source 46667, race 2, gender 0).
-- 4000014: Old Umbehto (source 44975, race 8, gender 0).
-- 4000015: Krenk Choplimb (source 45540, race 9, gender 0).
-- 4000016: "Jack" Pisarek Slamfix (source 45545, race 9, gender 0).
-- 4000017: Kark Helmbreaker (source 45548, race 9, gender 0).
-- 4000018: Zarbo Porkpatty (source 45550, race 9, gender 0).
-- 4000019: Nivi Weavewell (source 45559, race 9, gender 1).
-- 4000020: Rento (source 44782, race 6, gender 0).
-- 4000021: Gizzik Oregrab (source 52170, race 9, gender 0).
-- 4000022: Lugrah (source 46675, race 2, gender 1).
-- 4000023: Nerog (source 46716, race 2, gender 0).
-- 4000024: Muraga (source 46741, race 2, gender 1).
INSERT INTO `mod_customnpcs_orgrimmar_appearance` VALUES
  (4000005, 26671, 1888.95, -4285.25, 31.1939, 3.8397, 13337, 0, 0, 0, 1),
  (4000006, 3811, 1872.91, -4280.95, 33.9886, 4.9218, 15424, 0, 45210, 0, 2),
  (4000007, 7909, 1558.52, -4209.71, 44.1398, 3.6827, 2030, 0, 0, 0, 1),
  (4000008, 3804, 1863.88, -4292.69, 34.1073, 5.5502, 31266, 0, 0, 0, 1),
  (4000009, 22121, 1863.46, -4297.75, 32.3292, 6.1436, 14836, 0, 0, 0, 1),
  (4000010, 4663, 1758.12, -4069.09, 44.6554, 1.0123, 17123, 17123, 0, 1, 1),
  (4000011, 29342, 1884.15, -4282.4, 31.6097, 4.6775, 45203, 0, 0, 0, 1),
  (4000012, 27222, 1675.61, -4132.1, 38.5644, 3.5256, 4993, 0, 0, 0, 1),
  (4000013, 28600, 1960.88, -4788.98, 57.1292, 1.5533, 10613, 0, 0, 0, 0),
  (4000014, 4575, 1705.74, -4118.14, 40.4606, 1.2392, 1117, 0, 0, 0, 1),
  (4000015, 28891, 1475.9, -4148.48, 40.9268, 2.6753, 2827, 0, 0, 0, 1),
  (4000016, 14530, 1482.48, -4143.12, 43.4716, 6.1959, 1911, 0, 0, 0, 1),
  (4000017, 7613, 1529.31, -4141.54, 46.6881, 0.9599, 1903, 0, 0, 0, 1),
  (4000018, 16951, 1477.67, -4201.27, 44.1081, 1.1345, 0, 0, 0, 0, 1),
  (4000019, 20905, 1560.91, -4224.63, 47.8017, 1.309, 0, 0, 0, 0, 1),
  (4000020, 5108, 1920.54, -4190.88, 43.726, 5.1662, 2711, 0, 0, 0, 0),
  (4000021, 29601, 1530.91, -4141.05, 46.3851, 1.6406, 1903, 0, 0, 0, 1),
  (4000022, 1878, 2088.8, -4767.27, 23.8183, 4.1539, 0, 0, 0, 0, 1),
  (4000023, 3752, 1838.72, -4464.13, 47.7959, 0, 12862, 0, 0, 0, 1),
  (4000024, 1358, 1907.59, -4460.51, 54.4983, 4.341, 6233, 0, 0, 0, 1);

-- The seven legacy goblins use fixed native goblin displays, not player-race substitutes.
DELETE a FROM `mod_customnpcs_outfit_entry` a
INNER JOIN `mod_customnpcs_orgrimmar_appearance` r ON r.`entry` = a.`creature_entry`;

-- These outfit IDs belong to this module roster; unrelated outfits are untouched.
DELETE FROM `mod_customnpcs_outfit` WHERE `outfit_id` IN (
  4000005, 4000006, 4000008, 4000009, 4000010, 4000011, 4000012, 4000013, 4000014, 4000020, 4000022, 4000023, 4000024
);
INSERT INTO `mod_customnpcs_outfit`
  (`outfit_id`, `race`, `gender`, `class`, `skin`, `face`, `hair`, `hair_color`, `facial_hair`, `guild_id`, `head`, `shoulders`, `shirt`, `chest`, `waist`, `legs`, `feet`, `wrists`, `hands`, `back`, `tabard`, `mainhand`, `offhand`, `ranged`)
VALUES
  (4000005, 6, 1, 11, 4, 2, 1, 0, 1, 0, -10998, 0, -25264, -25264, -25265, -25266, 0, -25268, 0, 0, 0, 13337, 0, 0),
  (4000006, 6, 0, 3, 7, 1, 7, 1, 4, 0, 0, 0, -10116, -10116, -7662, -6300, -16186, -10949, -10945, -46300, 0, 15424, 0, 45210),
  (4000008, 6, 0, 2, 7, 1, 9, 1, 3, 0, -10537, 0, -59912, -11102, -59913, -11104, -59914, -55482, -11106, -23045, 0, 31266, 0, 0),
  (4000009, 6, 1, 5, 2, 3, 0, 2, 1, 0, -7009, 0, 0, -30515, -28302, -31575, -59900, 0, -59901, 0, 0, 14836, 0, 0),
  (4000010, 8, 0, 4, 4, 4, 0, 9, 7, 0, 0, -30360, -30357, -30357, -30354, -30359, -30356, -30353, -30355, 0, 0, 17123, 17123, 0),
  (4000011, 6, 1, 7, 8, 0, 2, 2, 2, 0, -4256, 0, -11155, -11155, 0, -11011, 0, 0, 0, 0, 0, 45203, 0, 0),
  (4000012, 8, 1, 9, 4, 3, 8, 1, 1, 0, -15361, 0, 0, -54400, -15767, -54402, 0, -15768, -13392, 0, 0, 4993, 0, 0),
  (4000013, 2, 0, 1, 1, 2, 1, 0, 7, 0, -35466, 0, -26183, -26183, 0, -22502, -9699, -26181, -3993, 0, 0, 10613, 0, 0),
  (4000014, 8, 0, 1, 4, 4, 1, 8, 0, 0, 0, 0, -10018, -10874, -10061, -9187, -12257, -10939, -16376, 0, 0, 1117, 0, 0),
  (4000020, 6, 0, 1, 15, 3, 2, 1, 1, 0, 0, 0, -40237, -40237, -1107, -4263, -4008, 0, -2981, 0, 0, 2711, 0, 0),
  (4000022, 2, 1, 1, 3, 1, 0, 6, 1, 0, -4661, 0, -9628, -9628, -11880, -11881, -9051, -12147, -11564, 0, 0, 0, 0, 0),
  (4000023, 2, 0, 1, 3, 2, 4, 6, 4, 0, 0, 0, -9202, -54668, -9203, -11017, -9205, -9206, 0, 0, 0, 12862, 0, 0),
  (4000024, 2, 1, 1, 2, 0, 0, 3, 6, 0, 0, 0, -11871, -11871, -10091, -10992, -9184, -11188, -11025, 0, 0, 6233, 0, 0);

INSERT INTO `mod_customnpcs_outfit_entry` (`creature_entry`, `outfit_id`) VALUES
  (4000005, 4000005),
  (4000006, 4000006),
  (4000008, 4000008),
  (4000009, 4000009),
  (4000010, 4000010),
  (4000011, 4000011),
  (4000012, 4000012),
  (4000013, 4000013),
  (4000014, 4000014),
  (4000020, 4000020),
  (4000022, 4000022),
  (4000023, 4000023),
  (4000024, 4000024);

-- One fixed native fallback per NPC: correct race/gender even with outfits disabled.
DELETE m FROM `creature_template_model` m
INNER JOIN `mod_customnpcs_orgrimmar_appearance` r ON r.`entry` = m.`CreatureID`;
INSERT INTO `creature_template_model`
  (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`)
SELECT `entry`, 0, `display_id`, 1, 1 FROM `mod_customnpcs_orgrimmar_appearance`;

-- Native held weapons/tools also apply to legacy goblins and to disabled-outfit fallbacks.
DELETE e FROM `creature_equip_template` e
INNER JOIN `mod_customnpcs_orgrimmar_appearance` r ON r.`entry` = e.`CreatureID`;
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`)
SELECT `entry`, 1, `mainhand`, `offhand`, `ranged` FROM `mod_customnpcs_orgrimmar_appearance`;

-- Preserve addon paths, mounts, auras and higher bytes; copy supported idle/sheath states only.
INSERT INTO `creature_template_addon` (`entry`, `bytes1`, `bytes2`)
SELECT `entry`, `stand_state`, `sheath_state` FROM `mod_customnpcs_orgrimmar_appearance`
ON DUPLICATE KEY UPDATE
  `bytes1` = (`bytes1` & 4294967040) | VALUES(`bytes1`),
  `bytes2` = (`bytes2` & 4294967040) | VALUES(`bytes2`);

-- Support both older AzerothCore's creature.id and current creature.id1 schemas.
SET @MOD_CUSTOMNPCS_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
SET @MOD_CUSTOMNPCS_PLACEMENT_SQL := CONCAT(
  'UPDATE `creature` c INNER JOIN `mod_customnpcs_orgrimmar_appearance` r ON c.`',
  @MOD_CUSTOMNPCS_ENTRY_COLUMN, '` = r.`entry` ',
  'SET c.`position_x` = r.`position_x`, c.`position_y` = r.`position_y`, ',
  'c.`position_z` = r.`position_z`, c.`orientation` = r.`orientation`, c.`equipment_id` = 1 ',
  'WHERE c.`map` = 1 AND c.`position_x` BETWEEN 1200 AND 2300 ',
  'AND c.`position_y` BETWEEN -5100 AND -3800'
);
PREPARE mod_customnpcs_placement FROM @MOD_CUSTOMNPCS_PLACEMENT_SQL;
EXECUTE mod_customnpcs_placement;
DEALLOCATE PREPARE mod_customnpcs_placement;

DROP TEMPORARY TABLE `mod_customnpcs_orgrimmar_appearance`;
