-- mod-customNPCs: Cataclysm/MoP additions to Stormwind, converted to Wrath.
-- Generated by tools/generate_stormwind_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql. Includes new identities, native curricula,
-- checked appearances and map-0 placements. Does not alter existing stock NPCs.
-- Safe to reapply: existing spawn GUIDs and intentional spawn outfit overrides survive.
-- Restart worldserver after applying. See docs/stormwind-trainers.md.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_stormwind_roster`;
CREATE TEMPORARY TABLE `mod_customnpcs_stormwind_roster` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `subname` VARCHAR(100) NOT NULL,
  `gossip_menu_id` INT UNSIGNED NOT NULL,
  `npcflag` INT UNSIGNED NOT NULL,
  `unit_class` TINYINT UNSIGNED NOT NULL,
  `minlevel` TINYINT UNSIGNED NOT NULL,
  `maxlevel` TINYINT UNSIGNED NOT NULL,
  `trainer_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL
);
INSERT INTO `mod_customnpcs_stormwind_roster` VALUES
  (4000100, 'Don Omar', 'Hunter Trainer', 4474, 49, 2, 40, 40, 7, -8820.2, 346.051, 109.852, 1.5359),
  (4000101, 'Darlene Stokx', 'Riding Trainer', 4018, 81, 1, 45, 45, 37, -8776.6, 375.56, 101.921, 6.1708),
  (4000102, 'Bralla Cloudwing', 'Flying Trainer', 4018, 81, 1, 50, 50, 36, -8845.44, 502.14, 109.771, 3.7874),
  (4000103, 'Wulf Hansreim', 'Hunter Trainer', 4474, 49, 1, 60, 60, 7, -8821.98, 351.431, 109.748, 5.0266),
  (4000104, 'Sarisse Jume', 'Hunter Trainer', 4474, 49, 1, 50, 50, 7, -8818.38, 348.658, 110.157, 3.5605),
  (4000105, 'Alma Deering', 'Pet Trainer', 4783, 49, 1, 40, 40, 125, -8811.93, 337.392, 111.188, 0.733),
  (4000106, 'Bolner Hammerbeak', 'Shaman Trainer', 8110, 49, 2, 50, 50, 14, -8347.68, 567.38, 100.721, 3.0892),
  (4000107, 'Dalga Hammerbeak', 'Shaman Trainer', 8110, 49, 2, 40, 40, 14, -8349.36, 565.479, 101.108, 1.309),
  (4000108, 'Celestine of the Harvest', 'Druid Trainer', 4508, 49, 1, 1, 1, 33, -8773.65, 1110.91, 91.0333, 2.0944),
  (4000109, 'Theresa Denman', 'Jewelcrafting Trainer', 0, 80, 1, 30, 30, 111, -8712.15, 620.003, 101.942, 0.2443),
  (4000110, 'Chief Surgeon Gashweld', 'Priest Trainer', 4466, 49, 8, 60, 60, 11, -8390.44, 628.439, 95.6935, 3.194),
  (4000111, 'Arthur Huwe', 'Rogue Trainer', 4502, 49, 1, 60, 60, 9, -8700.56, 344.705, 102.735, 4.9278),
  (4000112, 'Jordan Smith', 'Blacksmithing Trainer & Supplies', 4000112, 209, 1, 30, 30, 59, -8557.13, 593.646, 105.17, 1.1694),
  (4000113, 'Angela Leifeld', 'First Aid Trainer', 657, 81, 1, 35, 35, 81, -8521.53, 816.257, 106.982, 2.8798);

-- Neutral custom-realm faction, valid creature stat classes, matching original titles/services.
INSERT INTO `creature_template`
  (`entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`,
   `npcflag`, `unit_class`, `unit_flags`, `type`, `AIName`, `ScriptName`, `flags_extra`)
SELECT `entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, 2, 35,
  `npcflag`, `unit_class`, 2, 7, 'NullCreatureAI', '', 2
FROM `mod_customnpcs_stormwind_roster`
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`), `subname` = VALUES(`subname`),
  `gossip_menu_id` = VALUES(`gossip_menu_id`), `npcflag` = VALUES(`npcflag`),
  `unit_class` = VALUES(`unit_class`);

DELETE t FROM `creature_default_trainer` t
INNER JOIN `mod_customnpcs_stormwind_roster` r ON r.`entry` = t.`CreatureId`;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`)
SELECT `entry`, `trainer_id` FROM `mod_customnpcs_stormwind_roster`;

-- Retain only source supplies present in Wrath, without later currencies/recipes.
DELETE v FROM `npc_vendor` v
INNER JOIN `mod_customnpcs_stormwind_roster` r ON r.`entry` = v.`entry`;
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`) VALUES
  (4000112, 3, 2880, 0, 0, 0),
  (4000112, 4, 3466, 0, 0, 0),
  (4000112, 6, 3857, 0, 0, 0),
  (4000112, 5, 18567, 0, 0, 0),
  (4000112, 2, 5956, 0, 0, 0),
  (4000112, 1, 2901, 0, 0, 0);

-- Jordan Smith: both training and supplies must be reachable from gossip.
DELETE FROM `gossip_menu_option` WHERE `MenuID` = 4000112;
DELETE FROM `gossip_menu` WHERE `MenuID` = 4000112;
INSERT INTO `gossip_menu` (`MenuID`, `TextID`)
SELECT 4000112, `TextID` FROM `gossip_menu` WHERE `MenuID` = 581;
INSERT INTO `gossip_menu_option`
  (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`)
VALUES
  (4000112, 0, 3, 'Train me.', 3266, 5, 16),
  (4000112, 1, 1, 'Let me browse your goods.', 8097, 3, 128);

-- Seed only missing Stormwind spawns. Do not delete/recreate existing NPCs or move outside-city copies.
SET @MOD_CUSTOMNPCS_SW_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_stormwind_existing`;
SET @MOD_CUSTOMNPCS_SW_EXISTING_SQL := CONCAT(
  'CREATE TEMPORARY TABLE `mod_customnpcs_stormwind_existing` AS ',
  'SELECT c.`guid`, c.`', @MOD_CUSTOMNPCS_SW_ENTRY_COLUMN, '` AS `entry` ',
  'FROM `creature` c INNER JOIN `mod_customnpcs_stormwind_roster` r ON r.`entry` = c.`',
  @MOD_CUSTOMNPCS_SW_ENTRY_COLUMN, '` ',
  'WHERE c.`map` = 0 AND c.`position_x` BETWEEN -9200 AND -7700 ',
  'AND c.`position_y` BETWEEN 100 AND 2500'
);
PREPARE mod_customnpcs_sw_existing FROM @MOD_CUSTOMNPCS_SW_EXISTING_SQL;
EXECUTE mod_customnpcs_sw_existing;
DEALLOCATE PREPARE mod_customnpcs_sw_existing;
SET @MOD_CUSTOMNPCS_SW_INSERT_SQL := CONCAT(
  'INSERT INTO `creature` (`', @MOD_CUSTOMNPCS_SW_ENTRY_COLUMN,
  '`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `equipment_id`, ',
  '`position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `MovementType`) ',
  'SELECT r.`entry`, 0, 1519, 1519, 1, 1, 1, r.`position_x`, r.`position_y`, r.`position_z`, ',
  'r.`orientation`, 300, 0 FROM `mod_customnpcs_stormwind_roster` r ',
  'LEFT JOIN `mod_customnpcs_stormwind_existing` s ON s.`entry` = r.`entry` WHERE s.`guid` IS NULL'
);
PREPARE mod_customnpcs_sw_insert FROM @MOD_CUSTOMNPCS_SW_INSERT_SQL;
EXECUTE mod_customnpcs_sw_insert;
DEALLOCATE PREPARE mod_customnpcs_sw_insert;
DROP TEMPORARY TABLE `mod_customnpcs_stormwind_existing`;
DROP TEMPORARY TABLE `mod_customnpcs_stormwind_roster`;

-- mod-customNPCs: Cataclysm/MoP Stormwind appearances and Wrath placements.
-- Generated by tools/generate_stormwind_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql and the Stormwind roster above.
-- Native displays, armor textures, customization and weapons were checked in build 12340.
-- Only this roster is updated. Existing spawn GUIDs and per-spawn outfit overrides survive.
-- Restart worldserver after applying: model/equipment/addon/spawn caches must also reload.
-- See docs/stormwind-trainers.md for sources, substitutions and placement checks.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_stormwind_appearance`;
CREATE TEMPORARY TABLE `mod_customnpcs_stormwind_appearance` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `display_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL,
  `mainhand` INT UNSIGNED NOT NULL,
  `offhand` INT UNSIGNED NOT NULL,
  `ranged` INT UNSIGNED NOT NULL,
  `stand_state` TINYINT UNSIGNED NOT NULL,
  `sheath_state` TINYINT UNSIGNED NOT NULL
);

-- 4000100: Don Omar (source 43277, race 1, gender 0).
-- 4000101: Darlene Stokx (source 43693, race 1, gender 1).
-- 4000102: Bralla Cloudwing (source 43769, race 3, gender 1).
-- 4000103: Wulf Hansreim (source 44247, race 1, gender 0).
-- 4000104: Sarisse Jume (source 44249, race 1, gender 1).
-- 4000105: Alma Deering (source 44251, race 1, gender 1).
-- 4000106: Bolner Hammerbeak (source 44393, race 3, gender 0).
-- 4000107: Dalga Hammerbeak (source 44394, race 3, gender 1).
-- 4000108: Celestine of the Harvest (source 44396, race 22, gender 1).
-- 4000109: Theresa Denman (source 44582, race 1, gender 1).
-- 4000110: Chief Surgeon Gashweld (source 45306, race 7, gender 1).
-- 4000111: Arthur Huwe (source 51998, race 1, gender 0).
-- 4000112: Jordan Smith (source 55684, race 1, gender 0).
-- 4000113: Angela Leifeld (source 56796, race 1, gender 1).
INSERT INTO `mod_customnpcs_stormwind_appearance` VALUES
  (4000100, 16615, -8820.2, 346.051, 109.852, 1.5359, 3364, 0, 34325, 0, 2),
  (4000101, 4273, -8776.6, 375.56, 101.921, 6.1708, 0, 0, 0, 0, 1),
  (4000102, 11741, -8845.44, 502.14, 109.771, 3.7874, 0, 0, 0, 0, 1),
  (4000103, 10641, -8821.98, 351.431, 109.748, 5.0266, 3191, 0, 36628, 0, 2),
  (4000104, 9255, -8818.38, 348.658, 110.157, 3.5605, 13631, 0, 23748, 0, 2),
  (4000105, 4488, -8811.93, 337.392, 111.188, 0.733, 0, 0, 0, 0, 1),
  (4000106, 8709, -8347.68, 567.38, 100.721, 3.0892, 0, 0, 0, 0, 1),
  (4000107, 11739, -8349.36, 565.479, 101.108, 1.309, 0, 0, 0, 0, 1),
  (4000108, 18625, -8773.65, 1110.91, 91.0333, 2.0944, 1908, 0, 0, 0, 0),
  (4000109, 11747, -8712.15, 620.003, 101.942, 0.2443, 0, 0, 0, 0, 1),
  (4000110, 10722, -8390.44, 628.439, 95.6935, 3.194, 4994, 0, 0, 0, 1),
  (4000111, 13171, -8700.56, 344.705, 102.735, 4.9278, 1900, 5284, 0, 5, 1),
  (4000112, 3354, -8557.13, 593.646, 105.17, 1.1694, 1903, 0, 0, 0, 1),
  (4000113, 11041, -8521.53, 816.257, 106.982, 2.8798, 0, 0, 0, 0, 1);

-- Native Wildhammer displays retain NPC-only tattoos; other NPCs use player outfits.
DELETE a FROM `mod_customnpcs_outfit_entry` a
INNER JOIN `mod_customnpcs_stormwind_appearance` r ON r.`entry` = a.`creature_entry`;

-- These outfit IDs belong to this module roster; unrelated outfits are untouched.
DELETE FROM `mod_customnpcs_outfit` WHERE `outfit_id` IN (
  4000100, 4000101, 4000103, 4000104, 4000105, 4000108, 4000109, 4000110, 4000111, 4000112, 4000113
);
INSERT INTO `mod_customnpcs_outfit`
  (`outfit_id`, `race`, `gender`, `class`, `skin`, `face`, `hair`, `hair_color`, `facial_hair`, `guild_id`, `head`, `shoulders`, `shirt`, `chest`, `waist`, `legs`, `feet`, `wrists`, `hands`, `back`, `tabard`, `mainhand`, `offhand`, `ranged`)
VALUES
  (4000100, 1, 0, 3, 4, 2, 5, 0, 2, 0, 0, 0, 0, -12038, -7200, -5870, -10595, 0, -8307, 0, 0, 3364, 0, 34325),
  (4000101, 1, 1, 1, 0, 5, 13, 6, 0, 0, 0, 0, -58446, -10601, -5873, -5874, -46610, -15410, 0, 0, 0, 0, 0, 0),
  (4000103, 1, 0, 3, 2, 2, 4, 1, 4, 0, 0, 0, -1817, -22005, 0, -17954, -22505, -18335, -23968, 0, 0, 3191, 0, 36628),
  (4000104, 1, 1, 3, 9, 10, 17, 0, 4, 0, 0, 0, -58159, -1019, -13014, -697, -1020, 0, -510, 0, 0, 13631, 0, 23748),
  (4000105, 1, 1, 3, 0, 8, 7, 2, 2, 0, 0, -44070, -46226, -46226, 0, -3882, -9080, -6867, -6868, 0, 0, 0, 0, 0),
  (4000108, 1, 1, 11, 0, 12, 14, 9, 0, 0, -15024, -13697, -8965, -14840, 0, -15577, -32309, 0, 0, 0, 0, 1908, 0, 0),
  (4000109, 1, 1, 1, 0, 4, 14, 0, 1, 0, 0, 0, -5326, -7172, -6062, -8974, -9771, 0, 0, 0, 0, 0, 0, 0),
  (4000110, 7, 1, 5, 0, 0, 4, 8, 4, 0, -23858, 0, -5783, -17807, -5821, -2185, -50174, 0, -10727, 0, 0, 4994, 0, 0),
  (4000111, 1, 0, 4, 2, 7, 0, 0, 2, 0, 0, -29086, -12969, -9131, -10433, -2018, -5354, 0, -10309, 0, 0, 1900, 5284, 0),
  (4000112, 1, 0, 1, 0, 7, 5, 4, 8, 0, 0, 0, -3552, -5837, -8347, -4293, -5853, 0, -8892, 0, 0, 1903, 0, 0),
  (4000113, 1, 1, 1, 0, 3, 17, 4, 1, 0, 0, 0, 0, -7795, -5588, -7797, -5786, 0, 0, 0, 0, 0, 0, 0);

INSERT INTO `mod_customnpcs_outfit_entry` (`creature_entry`, `outfit_id`) VALUES
  (4000100, 4000100),
  (4000101, 4000101),
  (4000103, 4000103),
  (4000104, 4000104),
  (4000105, 4000105),
  (4000108, 4000108),
  (4000109, 4000109),
  (4000110, 4000110),
  (4000111, 4000111),
  (4000112, 4000112),
  (4000113, 4000113);

-- One fixed native fallback per NPC: correct race/gender even with outfits disabled.
DELETE m FROM `creature_template_model` m
INNER JOIN `mod_customnpcs_stormwind_appearance` r ON r.`entry` = m.`CreatureID`;
INSERT INTO `creature_template_model`
  (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`)
SELECT `entry`, 0, `display_id`, 1, 1 FROM `mod_customnpcs_stormwind_appearance`;

-- Native held weapons/tools also apply to legacy goblins and to disabled-outfit fallbacks.
DELETE e FROM `creature_equip_template` e
INNER JOIN `mod_customnpcs_stormwind_appearance` r ON r.`entry` = e.`CreatureID`;
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`)
SELECT `entry`, 1, `mainhand`, `offhand`, `ranged` FROM `mod_customnpcs_stormwind_appearance`;

-- Preserve addon paths, mounts, auras and higher bytes; copy supported idle/sheath states only.
INSERT INTO `creature_template_addon` (`entry`, `bytes1`, `bytes2`)
SELECT `entry`, `stand_state`, `sheath_state` FROM `mod_customnpcs_stormwind_appearance`
ON DUPLICATE KEY UPDATE
  `bytes1` = (`bytes1` & 4294967040) | VALUES(`bytes1`),
  `bytes2` = (`bytes2` & 4294967040) | VALUES(`bytes2`);

-- Support both older AzerothCore's creature.id and current creature.id1 schemas.
SET @MOD_CUSTOMNPCS_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
SET @MOD_CUSTOMNPCS_PLACEMENT_SQL := CONCAT(
  'UPDATE `creature` c INNER JOIN `mod_customnpcs_stormwind_appearance` r ON c.`',
  @MOD_CUSTOMNPCS_ENTRY_COLUMN, '` = r.`entry` ',
  'SET c.`position_x` = r.`position_x`, c.`position_y` = r.`position_y`, ',
  'c.`position_z` = r.`position_z`, c.`orientation` = r.`orientation`, c.`equipment_id` = 1 ',
  'WHERE c.`map` = 0 AND c.`position_x` BETWEEN -9200 AND -7700 ',
  'AND c.`position_y` BETWEEN 100 AND 2500'
);
PREPARE mod_customnpcs_placement FROM @MOD_CUSTOMNPCS_PLACEMENT_SQL;
EXECUTE mod_customnpcs_placement;
DEALLOCATE PREPARE mod_customnpcs_placement;

DROP TEMPORARY TABLE `mod_customnpcs_stormwind_appearance`;
