-- mod-customNPCs: Cataclysm/MoP additions to Ironforge, converted to Wrath.
-- Generated by tools/generate_city_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql. Includes new identities, native curricula,
-- checked appearances and map-0 placements. Does not alter existing stock NPCs.
-- Safe to reapply: existing spawn GUIDs and intentional spawn outfit overrides survive.
-- Restart worldserver after applying. See docs/ironforge-trainers.md.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_ironforge_roster`;
CREATE TEMPORARY TABLE `mod_customnpcs_ironforge_roster` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `subname` VARCHAR(100) NOT NULL,
  `gossip_menu_id` INT UNSIGNED NOT NULL,
  `npcflag` INT UNSIGNED NOT NULL,
  `unit_class` TINYINT UNSIGNED NOT NULL,
  `minlevel` TINYINT UNSIGNED NOT NULL,
  `maxlevel` TINYINT UNSIGNED NOT NULL,
  `trainer_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL
);
INSERT INTO `mod_customnpcs_ironforge_roster` VALUES
  (4000200, 'Pyromancer Scorchbrew', 'Mage Trainer', 4552, 49, 1, 50, 50, 16, -4627.83, -913.788, 525.484, 3.7699),
  (4000201, 'Flarna Flametongue', 'Mage Trainer', 4552, 49, 1, 60, 60, 16, -4630.79, -914.106, 524.991, 5.8992),
  (4000202, 'Lainda Gemgold', 'Mage Trainer', 4552, 49, 1, 40, 40, 16, -4628.88, -916.18, 525.097, 1.8151),
  (4000203, 'Keric Smolderblade', 'Warlock Trainer', 4566, 49, 1, 60, 60, 31, -4605.77, -1115.43, 505.268, 5.8294),
  (4000204, 'Darba the Crone', 'Warlock Trainer', 4566, 49, 1, 50, 50, 31, -4599.31, -1107.49, 505.268, 2.9671),
  (4000205, 'Larn Caverndeep', 'Warlock Trainer', 4566, 49, 1, 40, 40, 31, -4602.15, -1107.76, 505.268, 0.1571),
  (4000206, 'Dareth', 'Druid Trainer', 4508, 49, 2, 60, 60, 33, -5081.38, -780.411, 495.671, 3.3685),
  (4000207, 'Hanner Gembold', 'Jewelcrafting Trainer', 7815, 80, 1, 30, 30, 111, -4706.71, -1110.23, 504.735, 3.0194);

-- Neutral custom-realm faction, valid creature stat classes, matching original titles/services.
INSERT INTO `creature_template`
  (`entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`,
   `npcflag`, `unit_class`, `unit_flags`, `type`, `AIName`, `ScriptName`, `flags_extra`)
SELECT `entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, 2, 35,
  `npcflag`, `unit_class`, 2, 7, 'NullCreatureAI', '', 2
FROM `mod_customnpcs_ironforge_roster`
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`), `subname` = VALUES(`subname`),
  `gossip_menu_id` = VALUES(`gossip_menu_id`), `npcflag` = VALUES(`npcflag`),
  `unit_class` = VALUES(`unit_class`);

DELETE t FROM `creature_default_trainer` t
INNER JOIN `mod_customnpcs_ironforge_roster` r ON r.`entry` = t.`CreatureId`;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`)
SELECT `entry`, `trainer_id` FROM `mod_customnpcs_ironforge_roster`;

-- Retain only source supplies present in Wrath, without later currencies/recipes.
DELETE v FROM `npc_vendor` v
INNER JOIN `mod_customnpcs_ironforge_roster` r ON r.`entry` = v.`entry`;

-- Seed only missing Ironforge spawns. Do not delete/recreate existing NPCs or move outside-city copies.
SET @MOD_CUSTOMNPCS_IRONFORGE_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_ironforge_existing`;
SET @MOD_CUSTOMNPCS_IRONFORGE_EXISTING_SQL := CONCAT(
  'CREATE TEMPORARY TABLE `mod_customnpcs_ironforge_existing` AS ',
  'SELECT c.`guid`, c.`', @MOD_CUSTOMNPCS_IRONFORGE_ENTRY_COLUMN, '` AS `entry` ',
  'FROM `creature` c INNER JOIN `mod_customnpcs_ironforge_roster` r ON r.`entry` = c.`',
  @MOD_CUSTOMNPCS_IRONFORGE_ENTRY_COLUMN, '` ',
  'WHERE c.`map` = 0 AND c.`position_x` BETWEEN -5300 AND -4500 ',
  'AND c.`position_y` BETWEEN -1400 AND -500'
);
PREPARE mod_customnpcs_ironforge_existing FROM @MOD_CUSTOMNPCS_IRONFORGE_EXISTING_SQL;
EXECUTE mod_customnpcs_ironforge_existing;
DEALLOCATE PREPARE mod_customnpcs_ironforge_existing;
SET @MOD_CUSTOMNPCS_IRONFORGE_INSERT_SQL := CONCAT(
  'INSERT INTO `creature` (`', @MOD_CUSTOMNPCS_IRONFORGE_ENTRY_COLUMN,
  '`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `equipment_id`, ',
  '`position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `MovementType`) ',
  'SELECT r.`entry`, 0, 1537, 1537, 1, 1, 1, r.`position_x`, r.`position_y`, r.`position_z`, ',
  'r.`orientation`, 300, 0 FROM `mod_customnpcs_ironforge_roster` r ',
  'LEFT JOIN `mod_customnpcs_ironforge_existing` s ON s.`entry` = r.`entry` WHERE s.`guid` IS NULL'
);
PREPARE mod_customnpcs_ironforge_insert FROM @MOD_CUSTOMNPCS_IRONFORGE_INSERT_SQL;
EXECUTE mod_customnpcs_ironforge_insert;
DEALLOCATE PREPARE mod_customnpcs_ironforge_insert;
DROP TEMPORARY TABLE `mod_customnpcs_ironforge_existing`;
DROP TEMPORARY TABLE `mod_customnpcs_ironforge_roster`;

-- mod-customNPCs: Cataclysm/MoP Ironforge appearances and Wrath placements.
-- Generated by tools/generate_city_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql and the Ironforge roster above.
-- Native displays, armor textures, customization and weapons were checked in build 12340.
-- Only this roster is updated. Existing spawn GUIDs and per-spawn outfit overrides survive.
-- Restart worldserver after applying: model/equipment/addon/spawn caches must also reload.
-- See docs/ironforge-trainers.md for sources, substitutions and placement checks.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_ironforge_appearance`;
CREATE TEMPORARY TABLE `mod_customnpcs_ironforge_appearance` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `display_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL,
  `mainhand` INT UNSIGNED NOT NULL,
  `offhand` INT UNSIGNED NOT NULL,
  `ranged` INT UNSIGNED NOT NULL,
  `stand_state` TINYINT UNSIGNED NOT NULL,
  `sheath_state` TINYINT UNSIGNED NOT NULL
);

-- 4000200: Pyromancer Scorchbrew (source 50716, race 3, gender 0).
-- 4000201: Flarna Flametongue (source 50717, race 3, gender 1).
-- 4000202: Lainda Gemgold (source 50720, race 3, gender 1).
-- 4000203: Keric Smolderblade (source 50723, race 3, gender 0).
-- 4000204: Darba the Crone (source 50729, race 3, gender 1).
-- 4000205: Larn Caverndeep (source 50732, race 3, gender 0).
-- 4000206: Dareth (source 52335, race 22, gender 0).
-- 4000207: Hanner Gembold (source 52586, race 3, gender 0).
INSERT INTO `mod_customnpcs_ironforge_appearance` VALUES
  (4000200, 8807, -4627.83, -913.788, 525.484, 3.7699, 13050, 0, 0, 0, 1),
  (4000201, 25233, -4630.79, -914.106, 524.991, 5.8992, 13078, 0, 0, 0, 1),
  (4000202, 1670, -4628.88, -916.18, 525.097, 1.8151, 14836, 0, 0, 0, 1),
  (4000203, 5465, -4605.77, -1115.43, 505.268, 5.8294, 11343, 0, 0, 0, 1),
  (4000204, 14663, -4599.31, -1107.49, 505.268, 2.9671, 2177, 0, 0, 0, 1),
  (4000205, 9946, -4602.15, -1107.76, 505.268, 0.1571, 2559, 0, 0, 0, 1),
  (4000206, 4885, -5081.38, -780.411, 495.671, 3.3685, 35740, 0, 0, 0, 1),
  (4000207, 3434, -4706.71, -1110.23, 504.735, 3.0194, 0, 0, 0, 0, 1);

-- Use checked native outfits and fixed same-race/gender fallback displays.
DELETE a FROM `mod_customnpcs_outfit_entry` a
INNER JOIN `mod_customnpcs_ironforge_appearance` r ON r.`entry` = a.`creature_entry`;

-- These outfit IDs belong to this module roster; unrelated outfits are untouched.
DELETE FROM `mod_customnpcs_outfit` WHERE `outfit_id` IN (
  4000202, 4000205, 4000206, 4000207
);
INSERT INTO `mod_customnpcs_outfit`
  (`outfit_id`, `race`, `gender`, `class`, `skin`, `face`, `hair`, `hair_color`, `facial_hair`, `guild_id`, `head`, `shoulders`, `shirt`, `chest`, `waist`, `legs`, `feet`, `wrists`, `hands`, `back`, `tabard`, `mainhand`, `offhand`, `ranged`)
VALUES
  (4000202, 3, 1, 8, 2, 2, 17, 4, 1, 0, 0, 0, 0, -5367, -5368, -5369, -5370, 0, 0, 0, 0, 14836, 0, 0),
  (4000205, 3, 0, 9, 0, 0, 0, 5, 5, 0, -15391, 0, 0, -17283, -17279, -17280, -17281, 0, -16068, 0, 0, 2559, 0, 0),
  (4000206, 1, 0, 11, 3, 2, 6, 1, 3, 0, 0, -6407, -54583, -6026, 0, -3442, -3709, -49484, -3846, 0, 0, 35740, 0, 0),
  (4000207, 3, 0, 1, 2, 6, 9, 3, 3, 0, -1170, 0, -5326, -27599, -9490, -27598, -25281, 0, 0, 0, 0, 0, 0, 0);

INSERT INTO `mod_customnpcs_outfit_entry` (`creature_entry`, `outfit_id`) VALUES
  (4000202, 4000202),
  (4000205, 4000205),
  (4000206, 4000206),
  (4000207, 4000207);

-- One fixed native fallback per NPC: matches the intended rendered race/gender with outfits disabled.
DELETE m FROM `creature_template_model` m
INNER JOIN `mod_customnpcs_ironforge_appearance` r ON r.`entry` = m.`CreatureID`;
INSERT INTO `creature_template_model`
  (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`)
SELECT `entry`, 0, `display_id`, 1, 1 FROM `mod_customnpcs_ironforge_appearance`;

-- Native held weapons/tools also apply to native fallback displays and to disabled-outfit fallbacks.
DELETE e FROM `creature_equip_template` e
INNER JOIN `mod_customnpcs_ironforge_appearance` r ON r.`entry` = e.`CreatureID`;
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`)
SELECT `entry`, 1, `mainhand`, `offhand`, `ranged` FROM `mod_customnpcs_ironforge_appearance`;

-- Preserve addon paths, mounts, auras and higher bytes; copy supported idle/sheath states only.
INSERT INTO `creature_template_addon` (`entry`, `bytes1`, `bytes2`)
SELECT `entry`, `stand_state`, `sheath_state` FROM `mod_customnpcs_ironforge_appearance`
ON DUPLICATE KEY UPDATE
  `bytes1` = (`bytes1` & 4294967040) | VALUES(`bytes1`),
  `bytes2` = (`bytes2` & 4294967040) | VALUES(`bytes2`);

-- Support both older AzerothCore's creature.id and current creature.id1 schemas.
SET @MOD_CUSTOMNPCS_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
SET @MOD_CUSTOMNPCS_PLACEMENT_SQL := CONCAT(
  'UPDATE `creature` c INNER JOIN `mod_customnpcs_ironforge_appearance` r ON c.`',
  @MOD_CUSTOMNPCS_ENTRY_COLUMN, '` = r.`entry` ',
  'SET c.`position_x` = r.`position_x`, c.`position_y` = r.`position_y`, ',
  'c.`position_z` = r.`position_z`, c.`orientation` = r.`orientation`, c.`equipment_id` = 1 ',
  'WHERE c.`map` = 0 AND c.`position_x` BETWEEN -5300 AND -4500 ',
  'AND c.`position_y` BETWEEN -1400 AND -500'
);
PREPARE mod_customnpcs_placement FROM @MOD_CUSTOMNPCS_PLACEMENT_SQL;
EXECUTE mod_customnpcs_placement;
DEALLOCATE PREPARE mod_customnpcs_placement;

DROP TEMPORARY TABLE `mod_customnpcs_ironforge_appearance`;
