-- mod-customNPCs: Cataclysm/MoP additions to Darnassus, converted to Wrath.
-- Generated by tools/generate_city_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql. Includes new identities, native curricula,
-- checked appearances and map-1 placements. Does not alter existing stock NPCs.
-- Safe to reapply: existing spawn GUIDs and intentional spawn outfit overrides survive.
-- Restart worldserver after applying. See docs/darnassus-trainers.md.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_darnassus_roster`;
CREATE TEMPORARY TABLE `mod_customnpcs_darnassus_roster` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `subname` VARCHAR(100) NOT NULL,
  `gossip_menu_id` INT UNSIGNED NOT NULL,
  `npcflag` INT UNSIGNED NOT NULL,
  `unit_class` TINYINT UNSIGNED NOT NULL,
  `minlevel` TINYINT UNSIGNED NOT NULL,
  `maxlevel` TINYINT UNSIGNED NOT NULL,
  `trainer_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL
);
INSERT INTO `mod_customnpcs_darnassus_roster` VALUES
  (4000300, 'Huntsman Blake', 'Hunter Trainer', 4474, 49, 2, 40, 40, 7, 10272.4, 2437.89, 1336.31, 1.0123),
  (4000301, 'Loren the Fence', 'Rogue Trainer', 4502, 49, 4, 40, 40, 9, 10307.4, 2455.99, 1337.07, 2.8623),
  (4000302, 'Myriam Spellwaker', 'Mage Trainer', 4552, 49, 8, 40, 40, 16, 10298.9, 2418.19, 1336.35, 5.2534),
  (4000303, 'Sergeant Cleese', 'Warrior Trainer', 4478, 49, 1, 40, 40, 1, 10275.8, 2440.53, 1336.18, 3.4209),
  (4000304, 'Sister Almyra', 'Priest Trainer', 4466, 49, 8, 40, 40, 11, 10284.1, 2449.1, 1336.34, 4.2761),
  (4000305, 'Vitus Darkwalker', 'Warlock Trainer', 4566, 49, 1, 40, 40, 31, 10301.8, 2418.08, 1335.83, 4.1539),
  (4000306, 'Belysra Starbreeze', 'Priestess of the Moon', 4466, 49, 8, 40, 40, 11, 10282.2, 2446.66, 1336.37, 1.117),
  (4000307, 'Lyros Swiftwind', 'Druid Trainer', 4508, 49, 2, 40, 40, 33, 10280.3, 2428.95, 1337.68, 0.8552),
  (4000308, 'Talran of the Wild', 'Druid Trainer', 4508, 49, 2, 40, 40, 33, 10286.1, 2412.17, 1335.79, 1.0123),
  (4000309, 'Vassandra Stormclaw', 'Druid Trainer', 4508, 49, 2, 40, 40, 33, 10282.3, 2424.13, 1337.53, 0.6981),
  (4000310, 'Tarelvir', 'Mage Trainer', 4552, 49, 8, 60, 60, 16, 9638.5, 2608.04, 1338.21, 0),
  (4000311, 'Dyrhara', 'Mage Trainer', 4552, 49, 8, 50, 50, 16, 9629.12, 2609.46, 1337.59, 5.2534),
  (4000312, 'Maelir', 'Mage Trainer', 4552, 49, 8, 40, 40, 16, 9631.83, 2605.41, 1337.64, 2.0944),
  (4000313, 'Droha', 'Shaman Trainer', 8110, 49, 2, 60, 60, 14, 9654.44, 2510.81, 1332.03, 0.1222),
  (4000314, 'Tana Lentner', 'Engineering Trainer', 4146, 80, 1, 35, 35, 89, 10132, 2423.56, 1332.58, 4.0143),
  (4000315, 'Rolf Karner', 'Blacksmithing Trainer', 581, 80, 1, 35, 35, 59, 9923.4, 2309.81, 1331.38, 2.5307),
  (4000316, 'Foreman Pernic', 'Mining Trainer', 7690, 80, 1, 35, 35, 78, 10119.8, 2416.36, 1322, 4.5902),
  (4000317, 'Aessa Silverdew', 'Jewelcrafting Trainer', 7815, 80, 1, 30, 30, 111, 10145, 2356.48, 1332.24, 6.0738);

-- Neutral custom-realm faction, valid creature stat classes, matching original titles/services.
INSERT INTO `creature_template`
  (`entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`,
   `npcflag`, `unit_class`, `unit_flags`, `type`, `AIName`, `ScriptName`, `flags_extra`)
SELECT `entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, 2, 35,
  `npcflag`, `unit_class`, 2, 7, 'NullCreatureAI', '', 2
FROM `mod_customnpcs_darnassus_roster`
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`), `subname` = VALUES(`subname`),
  `gossip_menu_id` = VALUES(`gossip_menu_id`), `npcflag` = VALUES(`npcflag`),
  `unit_class` = VALUES(`unit_class`);

DELETE t FROM `creature_default_trainer` t
INNER JOIN `mod_customnpcs_darnassus_roster` r ON r.`entry` = t.`CreatureId`;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`)
SELECT `entry`, `trainer_id` FROM `mod_customnpcs_darnassus_roster`;

-- Retain only source supplies present in Wrath, without later currencies/recipes.
DELETE v FROM `npc_vendor` v
INNER JOIN `mod_customnpcs_darnassus_roster` r ON r.`entry` = v.`entry`;

-- Seed only missing Darnassus spawns. Do not delete/recreate existing NPCs or move outside-city copies.
SET @MOD_CUSTOMNPCS_DARNASSUS_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_darnassus_existing`;
SET @MOD_CUSTOMNPCS_DARNASSUS_EXISTING_SQL := CONCAT(
  'CREATE TEMPORARY TABLE `mod_customnpcs_darnassus_existing` AS ',
  'SELECT c.`guid`, c.`', @MOD_CUSTOMNPCS_DARNASSUS_ENTRY_COLUMN, '` AS `entry` ',
  'FROM `creature` c INNER JOIN `mod_customnpcs_darnassus_roster` r ON r.`entry` = c.`',
  @MOD_CUSTOMNPCS_DARNASSUS_ENTRY_COLUMN, '` ',
  'WHERE c.`map` = 1 AND c.`position_x` BETWEEN 9500 AND 10500 ',
  'AND c.`position_y` BETWEEN 1800 AND 2900'
);
PREPARE mod_customnpcs_darnassus_existing FROM @MOD_CUSTOMNPCS_DARNASSUS_EXISTING_SQL;
EXECUTE mod_customnpcs_darnassus_existing;
DEALLOCATE PREPARE mod_customnpcs_darnassus_existing;
SET @MOD_CUSTOMNPCS_DARNASSUS_INSERT_SQL := CONCAT(
  'INSERT INTO `creature` (`', @MOD_CUSTOMNPCS_DARNASSUS_ENTRY_COLUMN,
  '`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `equipment_id`, ',
  '`position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `MovementType`) ',
  'SELECT r.`entry`, 1, 1657, 1657, 1, 1, 1, r.`position_x`, r.`position_y`, r.`position_z`, ',
  'r.`orientation`, 300, 0 FROM `mod_customnpcs_darnassus_roster` r ',
  'LEFT JOIN `mod_customnpcs_darnassus_existing` s ON s.`entry` = r.`entry` WHERE s.`guid` IS NULL'
);
PREPARE mod_customnpcs_darnassus_insert FROM @MOD_CUSTOMNPCS_DARNASSUS_INSERT_SQL;
EXECUTE mod_customnpcs_darnassus_insert;
DEALLOCATE PREPARE mod_customnpcs_darnassus_insert;
DROP TEMPORARY TABLE `mod_customnpcs_darnassus_existing`;
DROP TEMPORARY TABLE `mod_customnpcs_darnassus_roster`;

-- mod-customNPCs: Cataclysm/MoP Darnassus appearances and Wrath placements.
-- Generated by tools/generate_city_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql and the Darnassus roster above.
-- Native displays, armor textures, customization and weapons were checked in build 12340.
-- Only this roster is updated. Existing spawn GUIDs and per-spawn outfit overrides survive.
-- Restart worldserver after applying: model/equipment/addon/spawn caches must also reload.
-- See docs/darnassus-trainers.md for sources, substitutions and placement checks.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_darnassus_appearance`;
CREATE TEMPORARY TABLE `mod_customnpcs_darnassus_appearance` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `display_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL,
  `mainhand` INT UNSIGNED NOT NULL,
  `offhand` INT UNSIGNED NOT NULL,
  `ranged` INT UNSIGNED NOT NULL,
  `stand_state` TINYINT UNSIGNED NOT NULL,
  `sheath_state` TINYINT UNSIGNED NOT NULL
);

-- 4000300: Huntsman Blake (source 50497, race 1, gender 0).
-- 4000301: Loren the Fence (source 50498, race 1, gender 1).
-- 4000302: Myriam Spellwaker (source 50499, race 1, gender 1).
-- 4000303: Sergeant Cleese (source 50500, race 1, gender 0).
-- 4000304: Sister Almyra (source 50501, race 1, gender 1).
-- 4000305: Vitus Darkwalker (source 50502, race 1, gender 0).
-- 4000306: Belysra Starbreeze (source 50504, race 4, gender 1).
-- 4000307: Lyros Swiftwind (source 50505, race 4, gender 0).
-- 4000308: Talran of the Wild (source 50506, race 4, gender 0).
-- 4000309: Vassandra Stormclaw (source 50507, race 4, gender 1).
-- 4000310: Tarelvir (source 50690, race 4, gender 0).
-- 4000311: Dyrhara (source 50714, race 4, gender 1).
-- 4000312: Maelir (source 50715, race 4, gender 0).
-- 4000313: Droha (source 52292, race 11, gender 0).
-- 4000314: Tana Lentner (source 52636, race 22, gender 1).
-- 4000315: Rolf Karner (source 52640, race 22, gender 0).
-- 4000316: Foreman Pernic (source 52642, race 22, gender 0).
-- 4000317: Aessa Silverdew (source 52645, race 4, gender 1).
INSERT INTO `mod_customnpcs_darnassus_appearance` VALUES
  (4000300, 27118, 10272.4, 2437.89, 1336.31, 1.0123, 0, 0, 25270, 0, 1),
  (4000301, 18161, 10307.4, 2455.99, 1337.07, 2.8623, 2184, 0, 0, 0, 1),
  (4000302, 27261, 10298.9, 2418.19, 1336.35, 5.2534, 1908, 0, 0, 0, 1),
  (4000303, 28899, 10275.8, 2440.53, 1336.18, 3.4209, 12944, 2445, 0, 0, 1),
  (4000304, 1544, 10284.1, 2449.1, 1336.34, 4.2761, 5276, 0, 0, 0, 1),
  (4000305, 31647, 10301.8, 2418.08, 1335.83, 4.1539, 2559, 0, 0, 0, 1),
  (4000306, 1914, 10282.2, 2446.66, 1336.37, 1.117, 0, 0, 0, 0, 1),
  (4000307, 4304, 10280.3, 2428.95, 1337.68, 0.8552, 0, 0, 0, 0, 1),
  (4000308, 4237, 10286.1, 2412.17, 1335.79, 1.0123, 0, 0, 0, 0, 1),
  (4000309, 27168, 10282.3, 2424.13, 1337.53, 0.6981, 0, 0, 0, 0, 1),
  (4000310, 16157, 9638.5, 2608.04, 1338.21, 0, 49311, 0, 0, 0, 1),
  (4000311, 10749, 9629.12, 2609.46, 1337.59, 5.2534, 12421, 0, 0, 0, 1),
  (4000312, 3298, 9631.83, 2605.41, 1337.64, 2.0944, 13750, 0, 0, 0, 1),
  (4000313, 21265, 9654.44, 2510.81, 1332.03, 0.1222, 1908, 0, 0, 0, 1),
  (4000314, 24299, 10132, 2423.56, 1332.58, 4.0143, 4994, 0, 0, 0, 1),
  (4000315, 25611, 9923.4, 2309.81, 1331.38, 2.5307, 30078, 13611, 0, 0, 1),
  (4000316, 11743, 10119.8, 2416.36, 1322, 4.5902, 1910, 0, 0, 0, 1),
  (4000317, 15727, 10145, 2356.48, 1332.24, 6.0738, 0, 0, 0, 0, 1);

-- Use checked native outfits and fixed same-race/gender fallback displays.
DELETE a FROM `mod_customnpcs_outfit_entry` a
INNER JOIN `mod_customnpcs_darnassus_appearance` r ON r.`entry` = a.`creature_entry`;

-- These outfit IDs belong to this module roster; unrelated outfits are untouched.
DELETE FROM `mod_customnpcs_outfit` WHERE `outfit_id` IN (
  4000300, 4000301, 4000302, 4000303, 4000304, 4000305, 4000306, 4000307, 4000308, 4000309, 4000310, 4000311, 4000312, 4000313, 4000314, 4000315, 4000316, 4000317
);
INSERT INTO `mod_customnpcs_outfit`
  (`outfit_id`, `race`, `gender`, `class`, `skin`, `face`, `hair`, `hair_color`, `facial_hair`, `guild_id`, `head`, `shoulders`, `shirt`, `chest`, `waist`, `legs`, `feet`, `wrists`, `hands`, `back`, `tabard`, `mainhand`, `offhand`, `ranged`)
VALUES
  (4000300, 1, 0, 3, 4, 0, 0, 1, 5, 0, -59905, 0, -13115, -13116, 0, -13117, -38204, 0, -7513, -43652, 0, 0, 0, 25270),
  (4000301, 1, 1, 4, 1, 9, 10, 10, 1, 0, 0, 0, 0, -2317, -5788, -5346, -4272, 0, 0, 0, 0, 2184, 0, 0),
  (4000302, 1, 1, 8, 1, 3, 2, 2, 0, 0, 0, 0, -62324, -60793, -62325, -62326, -9096, 0, -60795, 0, -3454, 1908, 0, 0),
  (4000303, 1, 0, 1, 3, 10, 6, 3, 0, 0, 0, 0, -37515, -11601, -34078, -34084, -34083, -34079, -34082, 0, 0, 12944, 2445, 0),
  (4000304, 1, 1, 5, 3, 13, 11, 9, 0, 0, 0, 0, -58155, -38961, -58156, -37283, -10210, -58041, -11016, 0, 0, 5276, 0, 0),
  (4000305, 1, 0, 9, 0, 1, 0, 4, 4, 0, -1170, 0, -47544, -47544, -47545, -47546, -53252, 0, -49163, 0, 0, 2559, 0, 0),
  (4000306, 4, 1, 5, 3, 5, 8, 7, 0, 0, 0, 0, -23978, -23978, 0, -9686, -6909, 0, 0, 0, 0, 0, 0, 0),
  (4000307, 4, 0, 11, 5, 2, 1, 5, 3, 0, 0, -53869, -53870, -53871, -53872, -57634, -53874, -53875, -53876, -29720, 0, 0, 0, 0),
  (4000308, 4, 0, 11, 0, 0, 11, 0, 5, 0, 0, -53869, -53870, -53871, -53872, -57634, -53874, -53875, -53876, -29720, 0, 0, 0, 0),
  (4000309, 4, 1, 11, 8, 6, 10, 0, 0, 0, 0, -53869, -53870, -53871, -53872, -57634, -53874, -53875, -53876, -29720, 0, 0, 0, 0),
  (4000310, 4, 0, 8, 5, 6, 11, 4, 5, 0, -55053, -41571, -37569, -42270, -42271, -42272, -42273, 0, 0, -15040, 0, 49311, 0, 0),
  (4000311, 4, 1, 8, 5, 7, 7, 4, 0, 0, -49533, -4904, 0, -13179, -10501, -10794, -9573, 0, -10376, -23092, 0, 12421, 0, 0),
  (4000312, 4, 0, 8, 5, 1, 11, 4, 3, 0, -55053, -4904, 0, -13179, -10501, -10794, -9573, 0, -10376, -23092, 0, 13750, 0, 0),
  (4000313, 11, 0, 7, 2, 5, 2, 3, 3, 0, -5677, 0, 0, -44556, -43049, -56237, 0, -54676, -42527, 0, 0, 1908, 0, 0),
  (4000314, 1, 1, 1, 1, 4, 14, 0, 0, 0, -17552, 0, 0, -8414, -8606, -8426, 0, 0, -8608, 0, 0, 4994, 0, 0),
  (4000315, 1, 0, 1, 3, 7, 0, 0, 5, 0, 0, 0, 0, -15441, -14853, -15673, 0, -16420, -14843, 0, 0, 30078, 13611, 0),
  (4000316, 1, 0, 1, 3, 7, 7, 6, 1, 0, -15368, 0, -58194, -11213, -8431, -4439, 0, -8423, -4438, 0, 0, 1910, 0, 0),
  (4000317, 4, 1, 1, 2, 8, 2, 6, 0, 0, 0, 0, 0, -33909, -24527, -18015, -15450, 0, 0, 0, 0, 0, 0, 0);

INSERT INTO `mod_customnpcs_outfit_entry` (`creature_entry`, `outfit_id`) VALUES
  (4000300, 4000300),
  (4000301, 4000301),
  (4000302, 4000302),
  (4000303, 4000303),
  (4000304, 4000304),
  (4000305, 4000305),
  (4000306, 4000306),
  (4000307, 4000307),
  (4000308, 4000308),
  (4000309, 4000309),
  (4000310, 4000310),
  (4000311, 4000311),
  (4000312, 4000312),
  (4000313, 4000313),
  (4000314, 4000314),
  (4000315, 4000315),
  (4000316, 4000316),
  (4000317, 4000317);

-- One fixed native fallback per NPC: matches the intended rendered race/gender with outfits disabled.
DELETE m FROM `creature_template_model` m
INNER JOIN `mod_customnpcs_darnassus_appearance` r ON r.`entry` = m.`CreatureID`;
INSERT INTO `creature_template_model`
  (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`)
SELECT `entry`, 0, `display_id`, 1, 1 FROM `mod_customnpcs_darnassus_appearance`;

-- Native held weapons/tools also apply to native fallback displays and to disabled-outfit fallbacks.
DELETE e FROM `creature_equip_template` e
INNER JOIN `mod_customnpcs_darnassus_appearance` r ON r.`entry` = e.`CreatureID`;
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`)
SELECT `entry`, 1, `mainhand`, `offhand`, `ranged` FROM `mod_customnpcs_darnassus_appearance`;

-- Preserve addon paths, mounts, auras and higher bytes; copy supported idle/sheath states only.
INSERT INTO `creature_template_addon` (`entry`, `bytes1`, `bytes2`)
SELECT `entry`, `stand_state`, `sheath_state` FROM `mod_customnpcs_darnassus_appearance`
ON DUPLICATE KEY UPDATE
  `bytes1` = (`bytes1` & 4294967040) | VALUES(`bytes1`),
  `bytes2` = (`bytes2` & 4294967040) | VALUES(`bytes2`);

-- Support both older AzerothCore's creature.id and current creature.id1 schemas.
SET @MOD_CUSTOMNPCS_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
SET @MOD_CUSTOMNPCS_PLACEMENT_SQL := CONCAT(
  'UPDATE `creature` c INNER JOIN `mod_customnpcs_darnassus_appearance` r ON c.`',
  @MOD_CUSTOMNPCS_ENTRY_COLUMN, '` = r.`entry` ',
  'SET c.`position_x` = r.`position_x`, c.`position_y` = r.`position_y`, ',
  'c.`position_z` = r.`position_z`, c.`orientation` = r.`orientation`, c.`equipment_id` = 1 ',
  'WHERE c.`map` = 1 AND c.`position_x` BETWEEN 9500 AND 10500 ',
  'AND c.`position_y` BETWEEN 1800 AND 2900'
);
PREPARE mod_customnpcs_placement FROM @MOD_CUSTOMNPCS_PLACEMENT_SQL;
EXECUTE mod_customnpcs_placement;
DEALLOCATE PREPARE mod_customnpcs_placement;

DROP TEMPORARY TABLE `mod_customnpcs_darnassus_appearance`;
