-- mod-customNPCs: city guards know the additional capital trainers.
-- Generated by tools/generate_city_guard_trainers.py from data/npcs/*_trainers.json.
-- Apply after all six capital trainer rosters and their appearance/placement SQL.
-- Native gossip and POI packets work on an unmodified 3.3.5a client.
-- patch-F.MPQ is for flight maps; no client archive change is needed here.
-- Does not replace stock directions, guard AI, factions, or trainer services.
-- Direction menu/text/POI IDs: 4100005-4100599; native option slots: 100-199.
-- Reapply after changing roster positions; restart worldserver to reload gossip/POIs.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_guard_directions`;
CREATE TEMPORARY TABLE `mod_customnpcs_guard_directions` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `menu` INT UNSIGNED NOT NULL,
  `option` SMALLINT UNSIGNED NOT NULL,
  `root_menu` INT UNSIGNED NOT NULL,
  `direction_id` INT UNSIGNED NOT NULL UNIQUE,
  `label` VARCHAR(200) NOT NULL,
  `text` TEXT NOT NULL,
  `x` FLOAT NOT NULL,
  `y` FLOAT NOT NULL,
  UNIQUE KEY (`menu`, `option`)
);
INSERT INTO `mod_customnpcs_guard_directions`
  (`entry`, `menu`, `option`, `root_menu`, `direction_id`, `label`, `text`, `x`, `y`) VALUES
  (4000005, 1949, 105, 1951, 4100005, 'Druid: Shalla Whiteleaf', 'Speak to Shalla Whiteleaf for Druid training. I''ve marked the location on your map.', 1888.95, -4285.25),
  (4000006, 1949, 106, 1951, 4100006, 'Hunter: Nohi Plainswalker', 'Speak to Nohi Plainswalker for Hunter training. I''ve marked the location on your map.', 1872.91, -4280.95),
  (4000007, 1949, 107, 1951, 4100007, 'Mage: Conjurer Mixli', 'Speak to Conjurer Mixli for Mage training. I''ve marked the location on your map.', 1558.52, -4209.71),
  (4000008, 1949, 108, 1951, 4100008, 'Paladin: Sunwalker Atohmo', 'Speak to Sunwalker Atohmo for Paladin training. I''ve marked the location on your map.', 1863.88, -4292.69),
  (4000009, 1949, 109, 1951, 4100009, 'Priest: Seer Liwatha', 'Speak to Seer Liwatha for Priest training. I''ve marked the location on your map.', 1863.46, -4297.75),
  (4000010, 1949, 110, 1951, 4100010, 'Rogue: Night-Stalker Ku''nanji', 'Speak to Night-Stalker Ku''nanji for Rogue training. I''ve marked the location on your map.', 1758.12, -4069.09),
  (4000011, 1949, 111, 1951, 4100011, 'Shaman: Sahi Cloudsinger', 'Speak to Sahi Cloudsinger for Shaman training. I''ve marked the location on your map.', 1884.15, -4282.4),
  (4000012, 1949, 112, 1951, 4100012, 'Warlock: Unjari Feltongue', 'Speak to Unjari Feltongue for Warlock training. I''ve marked the location on your map.', 1675.61, -4132.1),
  (4000013, 1949, 113, 1951, 4100013, 'Warrior: Blademaster Ronakada', 'Speak to Blademaster Ronakada for Warrior training. I''ve marked the location on your map.', 1960.88, -4788.98),
  (4000014, 1942, 114, 1951, 4100014, 'Fishing: Old Umbehto', 'Speak to Old Umbehto for Fishing training. I''ve marked the location on your map.', 1705.74, -4118.14),
  (4000015, 1942, 115, 1951, 4100015, 'First Aid: Krenk Choplimb', 'Speak to Krenk Choplimb for First Aid training. I''ve marked the location on your map.', 1475.9, -4148.48),
  (4000016, 1942, 116, 1951, 4100016, 'Engineering: "Jack" Pisarek Slamfix', 'Speak to "Jack" Pisarek Slamfix for Engineering training. I''ve marked the location on your map.', 1482.48, -4143.12),
  (4000017, 1942, 117, 1951, 4100017, 'Blacksmithing: Kark Helmbreaker', 'Speak to Kark Helmbreaker for Blacksmithing training. I''ve marked the location on your map.', 1529.31, -4141.54),
  (4000018, 1942, 118, 1951, 4100018, 'Cooking: Zarbo Porkpatty', 'Speak to Zarbo Porkpatty for Cooking training. I''ve marked the location on your map.', 1477.67, -4201.27),
  (4000019, 1942, 119, 1951, 4100019, 'Tailoring: Nivi Weavewell', 'Speak to Nivi Weavewell for Tailoring training. I''ve marked the location on your map.', 1560.91, -4224.63),
  (4000020, 1942, 120, 1951, 4100020, 'Skinning: Rento', 'Speak to Rento for Skinning training. I''ve marked the location on your map.', 1920.54, -4190.88),
  (4000021, 1942, 121, 1951, 4100021, 'Mining: Gizzik Oregrab', 'Speak to Gizzik Oregrab for Mining training. I''ve marked the location on your map.', 1530.91, -4141.05),
  (4000022, 1942, 122, 1951, 4100022, 'Jewelcrafting: Lugrah', 'Speak to Lugrah for Jewelcrafting training. I''ve marked the location on your map.', 2088.8, -4767.27),
  (4000023, 1942, 123, 1951, 4100023, 'Inscription: Nerog', 'Speak to Nerog for Inscription training. I''ve marked the location on your map.', 1838.72, -4464.13),
  (4000024, 1942, 124, 1951, 4100024, 'Herbalism: Muraga', 'Speak to Muraga for Herbalism training. I''ve marked the location on your map.', 1907.59, -4460.51),
  (4000100, 401, 100, 435, 4100100, 'Hunter: Don Omar', 'Speak to Don Omar for Hunter training. I''ve marked the location on your map.', -8820.2, 346.051),
  (4000101, 435, 101, 435, 4100101, 'Riding: Darlene Stokx', 'Speak to Darlene Stokx for Riding training. I''ve marked the location on your map.', -8776.6, 375.56),
  (4000102, 435, 102, 435, 4100102, 'Flying: Bralla Cloudwing', 'Speak to Bralla Cloudwing for Flying training. I''ve marked the location on your map.', -8845.44, 502.14),
  (4000103, 401, 103, 435, 4100103, 'Hunter: Wulf Hansreim', 'Speak to Wulf Hansreim for Hunter training. I''ve marked the location on your map.', -8821.98, 351.431),
  (4000104, 401, 104, 435, 4100104, 'Hunter: Sarisse Jume', 'Speak to Sarisse Jume for Hunter training. I''ve marked the location on your map.', -8818.38, 348.658),
  (4000105, 435, 105, 435, 4100105, 'Pet training: Alma Deering', 'Speak to Alma Deering for hunter pet training. I''ve marked the location on your map.', -8811.93, 337.392),
  (4000106, 401, 106, 435, 4100106, 'Shaman: Bolner Hammerbeak', 'Speak to Bolner Hammerbeak for Shaman training. I''ve marked the location on your map.', -8347.68, 567.38),
  (4000107, 401, 107, 435, 4100107, 'Shaman: Dalga Hammerbeak', 'Speak to Dalga Hammerbeak for Shaman training. I''ve marked the location on your map.', -8349.36, 565.479),
  (4000108, 401, 108, 435, 4100108, 'Druid: Celestine of the Harvest', 'Speak to Celestine of the Harvest for Druid training. I''ve marked the location on your map.', -8773.65, 1110.91),
  (4000109, 421, 109, 435, 4100109, 'Jewelcrafting: Theresa Denman', 'Speak to Theresa Denman for Jewelcrafting training. I''ve marked the location on your map.', -8712.15, 620.003),
  (4000110, 401, 110, 435, 4100110, 'Priest: Chief Surgeon Gashweld', 'Speak to Chief Surgeon Gashweld for Priest training. I''ve marked the location on your map.', -8390.44, 628.439),
  (4000111, 401, 111, 435, 4100111, 'Rogue: Arthur Huwe', 'Speak to Arthur Huwe for Rogue training. I''ve marked the location on your map.', -8700.56, 344.705),
  (4000112, 421, 112, 435, 4100112, 'Blacksmithing: Jordan Smith', 'Speak to Jordan Smith for Blacksmithing training. I''ve marked the location on your map.', -8557.13, 593.646),
  (4000113, 421, 113, 435, 4100113, 'First Aid: Angela Leifeld', 'Speak to Angela Leifeld for First Aid training. I''ve marked the location on your map.', -8521.53, 816.257),
  (4000200, 2144, 100, 2121, 4100200, 'Mage: Pyromancer Scorchbrew', 'Speak to Pyromancer Scorchbrew for Mage training. I''ve marked the location on your map.', -4627.83, -913.788),
  (4000201, 2144, 101, 2121, 4100201, 'Mage: Flarna Flametongue', 'Speak to Flarna Flametongue for Mage training. I''ve marked the location on your map.', -4630.79, -914.106),
  (4000202, 2144, 102, 2121, 4100202, 'Mage: Lainda Gemgold', 'Speak to Lainda Gemgold for Mage training. I''ve marked the location on your map.', -4628.88, -916.18),
  (4000203, 2144, 103, 2121, 4100203, 'Warlock: Keric Smolderblade', 'Speak to Keric Smolderblade for Warlock training. I''ve marked the location on your map.', -4605.77, -1115.43),
  (4000204, 2144, 104, 2121, 4100204, 'Warlock: Darba the Crone', 'Speak to Darba the Crone for Warlock training. I''ve marked the location on your map.', -4599.31, -1107.49),
  (4000205, 2144, 105, 2121, 4100205, 'Warlock: Larn Caverndeep', 'Speak to Larn Caverndeep for Warlock training. I''ve marked the location on your map.', -4602.15, -1107.76),
  (4000206, 2144, 106, 2121, 4100206, 'Druid: Dareth', 'Speak to Dareth for Druid training. I''ve marked the location on your map.', -5081.38, -780.411),
  (4000207, 2168, 107, 2121, 4100207, 'Jewelcrafting: Hanner Gembold', 'Speak to Hanner Gembold for Jewelcrafting training. I''ve marked the location on your map.', -4706.71, -1110.23),
  (4000300, 2343, 100, 2352, 4100300, 'Hunter: Huntsman Blake', 'Speak to Huntsman Blake for Hunter training. I''ve marked the location on your map.', 10272.4, 2437.89),
  (4000301, 2343, 101, 2352, 4100301, 'Rogue: Loren the Fence', 'Speak to Loren the Fence for Rogue training. I''ve marked the location on your map.', 10307.4, 2455.99),
  (4000302, 2343, 102, 2352, 4100302, 'Mage: Myriam Spellwaker', 'Speak to Myriam Spellwaker for Mage training. I''ve marked the location on your map.', 10298.9, 2418.19),
  (4000303, 2343, 103, 2352, 4100303, 'Warrior: Sergeant Cleese', 'Speak to Sergeant Cleese for Warrior training. I''ve marked the location on your map.', 10275.8, 2440.53),
  (4000304, 2343, 104, 2352, 4100304, 'Priest: Sister Almyra', 'Speak to Sister Almyra for Priest training. I''ve marked the location on your map.', 10284.1, 2449.1),
  (4000305, 2343, 105, 2352, 4100305, 'Warlock: Vitus Darkwalker', 'Speak to Vitus Darkwalker for Warlock training. I''ve marked the location on your map.', 10301.8, 2418.08),
  (4000306, 2343, 106, 2352, 4100306, 'Priest: Belysra Starbreeze', 'Speak to Belysra Starbreeze for Priest training. I''ve marked the location on your map.', 10282.2, 2446.66),
  (4000307, 2343, 107, 2352, 4100307, 'Druid: Lyros Swiftwind', 'Speak to Lyros Swiftwind for Druid training. I''ve marked the location on your map.', 10280.3, 2428.95),
  (4000308, 2343, 108, 2352, 4100308, 'Druid: Talran of the Wild', 'Speak to Talran of the Wild for Druid training. I''ve marked the location on your map.', 10286.1, 2412.17),
  (4000309, 2343, 109, 2352, 4100309, 'Druid: Vassandra Stormclaw', 'Speak to Vassandra Stormclaw for Druid training. I''ve marked the location on your map.', 10282.3, 2424.13),
  (4000310, 2343, 110, 2352, 4100310, 'Mage: Tarelvir', 'Speak to Tarelvir for Mage training. I''ve marked the location on your map.', 9638.5, 2608.04),
  (4000311, 2343, 111, 2352, 4100311, 'Mage: Dyrhara', 'Speak to Dyrhara for Mage training. I''ve marked the location on your map.', 9629.12, 2609.46),
  (4000312, 2343, 112, 2352, 4100312, 'Mage: Maelir', 'Speak to Maelir for Mage training. I''ve marked the location on your map.', 9631.83, 2605.41),
  (4000313, 2343, 113, 2352, 4100313, 'Shaman: Droha', 'Speak to Droha for Shaman training. I''ve marked the location on your map.', 9654.44, 2510.81),
  (4000314, 2351, 114, 2352, 4100314, 'Engineering: Tana Lentner', 'Speak to Tana Lentner for Engineering training. I''ve marked the location on your map.', 10132.0, 2423.56),
  (4000315, 2351, 115, 2352, 4100315, 'Blacksmithing: Rolf Karner', 'Speak to Rolf Karner for Blacksmithing training. I''ve marked the location on your map.', 9923.4, 2309.81),
  (4000316, 2351, 116, 2352, 4100316, 'Mining: Foreman Pernic', 'Speak to Foreman Pernic for Mining training. I''ve marked the location on your map.', 10119.8, 2416.36),
  (4000317, 2351, 117, 2352, 4100317, 'Jewelcrafting: Aessa Silverdew', 'Speak to Aessa Silverdew for Jewelcrafting training. I''ve marked the location on your map.', 10145.0, 2356.48),
  (4000400, 740, 100, 721, 4100400, 'Paladin: Sunwalker Reha', 'Speak to Sunwalker Reha for Paladin training. I''ve marked the location on your map. Look on Hunter Rise.', -1402.11, -142.964),
  (4000401, 740, 101, 721, 4100401, 'Priest: Seer Kaya', 'Speak to Seer Kaya for Priest training. I''ve marked the location on your map. Look on Elder Rise.', -1036.79, -302.023),
  (4000402, 740, 102, 721, 4100402, 'Paladin: Aponi Brightmane', 'Speak to Aponi Brightmane for Paladin training. I''ve marked the location on your map. Look on Hunter Rise.', -1405.44, -146.394),
  (4000403, 740, 103, 721, 4100403, 'Priest: Tahu Sagewind', 'Speak to Tahu Sagewind for Priest training. I''ve marked the location on your map. Look on Elder Rise.', -1068.49, -295.332),
  (4000404, 740, 104, 721, 4100404, 'Priest: Seer Beryl', 'Speak to Seer Beryl for Priest training. I''ve marked the location on your map. Look on Elder Rise.', -1042.56, -269.509),
  (4000405, 740, 105, 721, 4100405, 'Warlock: Delano Morisett', 'Speak to Delano Morisett for Warlock training. I''ve marked the location on your map. Look below Spirit Rise, beneath the shaman platform.', -945.639, 253.208),
  (4000406, 740, 106, 721, 4100406, 'Warlock: Jensen Thomasson', 'Speak to Jensen Thomasson for Warlock training. I''ve marked the location on your map. Look below Spirit Rise, beneath the shaman platform.', -954.092, 247.661),
  (4000407, 740, 107, 721, 4100407, 'Warlock: Morairania Horton', 'Speak to Morairania Horton for Warlock training. I''ve marked the location on your map. Look below Spirit Rise, beneath the shaman platform.', -953.965, 255.233),
  (4000408, 740, 108, 721, 4100408, 'Shaman: Garn Cloudsong', 'Speak to Garn Cloudsong for Shaman training. I''ve marked the location on your map. Look on the Spirit Rise platform.', -980.775, 269.899),
  (4000409, 740, 109, 721, 4100409, 'Shaman: Kador Cloudsong', 'Speak to Kador Cloudsong for Shaman training. I''ve marked the location on your map. Look on the Spirit Rise platform.', -980.841, 287.174),
  (4000410, 740, 110, 721, 4100410, 'Shaman: Lama Cloudsong', 'Speak to Lama Cloudsong for Shaman training. I''ve marked the location on your map. Look on the Spirit Rise platform.', -996.925, 278.464),
  (4000411, 751, 111, 721, 4100411, 'Engineering: Engineer Palehoof', 'Speak to Engineer Palehoof for Engineering training. I''ve marked the location on your map. Look on the main bluff.', -1264.73, 140.592),
  (4000412, 751, 112, 721, 4100412, 'Jewelcrafting: Nahari Cloudchaser', 'Speak to Nahari Cloudchaser for Jewelcrafting training. I''ve marked the location on your map. Look on the main bluff.', -1225.76, 153.337),
  (4000500, 2848, 100, 2849, 4100500, 'Hunter: Apolos', 'Speak to Apolos for Hunter training. I''ve marked the location on your map. The trainer is inside the underground city.', 1688.03, 398.658),
  (4000501, 2848, 101, 2849, 4100501, 'Hunter: Nathanos Blightcaller', 'Speak to Nathanos Blightcaller for Hunter training. I''ve marked the location on your map. The trainer is inside the underground city.', 1691.97, 400.474),
  (4000502, 2848, 102, 2849, 4100502, 'Shaman: Mahala Cloudsong', 'Speak to Mahala Cloudsong for Shaman training. I''ve marked the location on your map. The trainer is inside the underground city.', 1558.5, 344.363),
  (4000503, 2848, 103, 2849, 4100503, 'Druid: Mala Skywatcher', 'Speak to Mala Skywatcher for Druid training. I''ve marked the location on your map. The trainer is inside the underground city.', 1556.23, 342.526),
  (4000504, 2847, 104, 2849, 4100504, 'Jewelcrafting: Neller Fayne', 'Speak to Neller Fayne for Jewelcrafting training. I''ve marked the location on your map. The trainer is inside the underground city.', 1645.46, 331.009);

-- Fail before touching persistent data if another addition owns one of these
-- native menu slots or if the required native city menus are absent.
DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_guard_check`;
CREATE TEMPORARY TABLE `mod_customnpcs_guard_check` (`id` TINYINT PRIMARY KEY);
INSERT INTO `mod_customnpcs_guard_check` VALUES (1);
INSERT INTO `mod_customnpcs_guard_check`
SELECT 1 FROM `gossip_menu_option` o
INNER JOIN `mod_customnpcs_guard_directions` d
  ON d.`menu` = o.`MenuID` AND d.`option` = o.`OptionID`
WHERE o.`ActionMenuID` <> d.`direction_id` OR o.`ActionPoiID` <> d.`direction_id`
LIMIT 1;
INSERT INTO `mod_customnpcs_guard_check`
SELECT 1 FROM `mod_customnpcs_guard_directions` d
WHERE NOT EXISTS (SELECT 1 FROM `gossip_menu` g WHERE g.`MenuID` = d.`menu`)
   OR NOT EXISTS (SELECT 1 FROM `gossip_menu` g WHERE g.`MenuID` = d.`root_menu`)
LIMIT 1;
-- The owned leaf menus must never refer to another module's text.
INSERT INTO `mod_customnpcs_guard_check`
SELECT 1 FROM `gossip_menu` g
INNER JOIN `mod_customnpcs_guard_directions` d ON d.`direction_id` = g.`MenuID`
WHERE g.`TextID` <> d.`direction_id`
LIMIT 1;
-- Guard against exceeding the client's 32-option gossip menu limit.
INSERT INTO `mod_customnpcs_guard_check`
SELECT 1 FROM (
  SELECT `MenuID`, `OptionID`, 0 AS `added` FROM `gossip_menu_option`
  UNION ALL
  SELECT `menu`, `option`, 1 FROM `mod_customnpcs_guard_directions`
) planned
GROUP BY `MenuID` HAVING MAX(`added`) = 1 AND COUNT(DISTINCT `OptionID`) > 32 LIMIT 1;
DROP TEMPORARY TABLE `mod_customnpcs_guard_check`;

START TRANSACTION;
INSERT INTO `points_of_interest` (`ID`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`)
SELECT `direction_id`, `x`, `y`, 7, 99, 0, `label` FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE
  `PositionX` = VALUES(`PositionX`), `PositionY` = VALUES(`PositionY`),
  `Icon` = VALUES(`Icon`), `Flags` = VALUES(`Flags`),
  `Importance` = VALUES(`Importance`), `Name` = VALUES(`Name`);

INSERT INTO `npc_text` (`ID`, `text0_0`, `text0_1`, `BroadcastTextID0`, `Probability0`)
SELECT `direction_id`, `text`, `text`, 0, 1 FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE
  `text0_0` = VALUES(`text0_0`), `text0_1` = VALUES(`text0_1`),
  `BroadcastTextID0` = 0, `Probability0` = 1;

INSERT INTO `gossip_menu` (`MenuID`, `TextID`)
SELECT `direction_id`, `direction_id` FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE `TextID` = VALUES(`TextID`);

-- These are GOSSIP options even though the book icon identifies training.
-- Using OptionType 5 would incorrectly ask the guard to train the player.
INSERT INTO `gossip_menu_option`
  (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`,
   `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`)
SELECT `menu`, `option`, 3, `label`, 0, 1, 1, `direction_id`, `direction_id`
FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE
  `OptionIcon` = 3, `OptionText` = VALUES(`OptionText`), `OptionBroadcastTextID` = 0,
  `OptionType` = 1, `OptionNpcFlag` = 1,
  `ActionMenuID` = VALUES(`ActionMenuID`), `ActionPoiID` = VALUES(`ActionPoiID`);

-- Keep the direction dialogue open, with navigation back to the trainer list
-- or to the same guard's main services menu.
INSERT INTO `gossip_menu_option`
  (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`,
   `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`)
SELECT `direction_id`, 0, 0, 'Back to trainers.', 0, 1, 1, `menu`, 0
FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE
  `OptionIcon` = 0, `OptionText` = VALUES(`OptionText`), `OptionBroadcastTextID` = 0,
  `OptionType` = 1, `OptionNpcFlag` = 1,
  `ActionMenuID` = VALUES(`ActionMenuID`), `ActionPoiID` = 0;

INSERT INTO `gossip_menu_option`
  (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`,
   `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`)
SELECT `direction_id`, 1, 0, 'Other city services.', 0, 1, 1, `root_menu`, 0
FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE
  `OptionIcon` = 0, `OptionText` = VALUES(`OptionText`), `OptionBroadcastTextID` = 0,
  `OptionType` = 1, `OptionNpcFlag` = 1,
  `ActionMenuID` = VALUES(`ActionMenuID`), `ActionPoiID` = 0;
COMMIT;
DROP TEMPORARY TABLE `mod_customnpcs_guard_directions`;
