-- mod-customNPCs: Cataclysm/MoP additions to Thunder Bluff, converted to Wrath.
-- Generated by tools/generate_city_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql. Includes new identities, native curricula,
-- checked appearances and map-1 placements. Does not alter existing stock NPCs.
-- Safe to reapply: existing spawn GUIDs and intentional spawn outfit overrides survive.
-- Restart worldserver after applying. See docs/thunder_bluff-trainers.md.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_thunder_bluff_roster`;
CREATE TEMPORARY TABLE `mod_customnpcs_thunder_bluff_roster` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `subname` VARCHAR(100) NOT NULL,
  `gossip_menu_id` INT UNSIGNED NOT NULL,
  `npcflag` INT UNSIGNED NOT NULL,
  `unit_class` TINYINT UNSIGNED NOT NULL,
  `minlevel` TINYINT UNSIGNED NOT NULL,
  `maxlevel` TINYINT UNSIGNED NOT NULL,
  `trainer_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL
);
INSERT INTO `mod_customnpcs_thunder_bluff_roster` VALUES
  (4000400, 'Sunwalker Reha', 'Paladin Trainer', 4556, 49, 2, 60, 60, 3, -1402.11, -142.964, 159.665, 3.9619),
  (4000401, 'Seer Kaya', 'Priest Trainer', 4466, 49, 8, 50, 50, 11, -1036.79, -302.023, 159.38, 2.3562),
  (4000402, 'Aponi Brightmane', 'Paladin Trainer', 4556, 49, 2, 80, 80, 3, -1405.44, -146.394, 159.608, 1.3963),
  (4000403, 'Tahu Sagewind', 'Priest Trainer', 4466, 49, 2, 55, 55, 11, -1068.49, -295.332, 159.235, 0.4189),
  (4000404, 'Seer Beryl', 'Priest Trainer', 4466, 49, 8, 60, 60, 11, -1042.56, -269.509, 159.38, 4.0666),
  (4000405, 'Delano Morisett', 'Warlock Trainer', 4566, 49, 1, 50, 50, 31, -945.639, 253.208, 97.589, 3.3161),
  (4000406, 'Jensen Thomasson', 'Warlock Trainer', 4566, 49, 1, 50, 50, 31, -954.092, 247.661, 98.075, 0.925),
  (4000407, 'Morairania Horton', 'Warlock Trainer', 4566, 49, 1, 50, 50, 31, -953.965, 255.233, 97.8566, 5.4629),
  (4000408, 'Garn Cloudsong', 'Shaman Trainer', 8110, 49, 1, 40, 40, 14, -980.775, 269.899, 137.822, 2.1991),
  (4000409, 'Kador Cloudsong', 'Shaman Trainer', 8110, 49, 1, 60, 60, 14, -980.841, 287.174, 137.822, 4.4331),
  (4000410, 'Lama Cloudsong', 'Shaman Trainer', 8110, 49, 1, 50, 50, 14, -996.925, 278.464, 137.822, 0.2793),
  (4000411, 'Engineer Palehoof', 'Engineering Trainer', 4146, 80, 1, 46, 46, 89, -1264.73, 140.592, 132.77, 4.852),
  (4000412, 'Nahari Cloudchaser', 'Jewelcrafting Trainer', 7815, 80, 1, 30, 30, 111, -1225.76, 153.337, 133.57, 5.0964);

-- Neutral custom-realm faction, valid creature stat classes, matching original titles/services.
INSERT INTO `creature_template`
  (`entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`,
   `npcflag`, `unit_class`, `unit_flags`, `type`, `AIName`, `ScriptName`, `flags_extra`)
SELECT `entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, 2, 35,
  `npcflag`, `unit_class`, 2, 7, 'NullCreatureAI', '', 2
FROM `mod_customnpcs_thunder_bluff_roster`
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`), `subname` = VALUES(`subname`),
  `gossip_menu_id` = VALUES(`gossip_menu_id`), `npcflag` = VALUES(`npcflag`),
  `unit_class` = VALUES(`unit_class`);

DELETE t FROM `creature_default_trainer` t
INNER JOIN `mod_customnpcs_thunder_bluff_roster` r ON r.`entry` = t.`CreatureId`;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`)
SELECT `entry`, `trainer_id` FROM `mod_customnpcs_thunder_bluff_roster`;

-- Retain only source supplies present in Wrath, without later currencies/recipes.
DELETE v FROM `npc_vendor` v
INNER JOIN `mod_customnpcs_thunder_bluff_roster` r ON r.`entry` = v.`entry`;

-- Seed only missing Thunder Bluff spawns. Do not delete/recreate existing NPCs or move outside-city copies.
SET @MOD_CUSTOMNPCS_THUNDER_BLUFF_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_thunder_bluff_existing`;
SET @MOD_CUSTOMNPCS_THUNDER_BLUFF_EXISTING_SQL := CONCAT(
  'CREATE TEMPORARY TABLE `mod_customnpcs_thunder_bluff_existing` AS ',
  'SELECT c.`guid`, c.`', @MOD_CUSTOMNPCS_THUNDER_BLUFF_ENTRY_COLUMN, '` AS `entry` ',
  'FROM `creature` c INNER JOIN `mod_customnpcs_thunder_bluff_roster` r ON r.`entry` = c.`',
  @MOD_CUSTOMNPCS_THUNDER_BLUFF_ENTRY_COLUMN, '` ',
  'WHERE c.`map` = 1 AND c.`position_x` BETWEEN -1700 AND -850 ',
  'AND c.`position_y` BETWEEN -400 AND 450'
);
PREPARE mod_customnpcs_thunder_bluff_existing FROM @MOD_CUSTOMNPCS_THUNDER_BLUFF_EXISTING_SQL;
EXECUTE mod_customnpcs_thunder_bluff_existing;
DEALLOCATE PREPARE mod_customnpcs_thunder_bluff_existing;
SET @MOD_CUSTOMNPCS_THUNDER_BLUFF_INSERT_SQL := CONCAT(
  'INSERT INTO `creature` (`', @MOD_CUSTOMNPCS_THUNDER_BLUFF_ENTRY_COLUMN,
  '`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `equipment_id`, ',
  '`position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `MovementType`) ',
  'SELECT r.`entry`, 1, 1638, 1638, 1, 1, 1, r.`position_x`, r.`position_y`, r.`position_z`, ',
  'r.`orientation`, 300, 0 FROM `mod_customnpcs_thunder_bluff_roster` r ',
  'LEFT JOIN `mod_customnpcs_thunder_bluff_existing` s ON s.`entry` = r.`entry` WHERE s.`guid` IS NULL'
);
PREPARE mod_customnpcs_thunder_bluff_insert FROM @MOD_CUSTOMNPCS_THUNDER_BLUFF_INSERT_SQL;
EXECUTE mod_customnpcs_thunder_bluff_insert;
DEALLOCATE PREPARE mod_customnpcs_thunder_bluff_insert;
DROP TEMPORARY TABLE `mod_customnpcs_thunder_bluff_existing`;
DROP TEMPORARY TABLE `mod_customnpcs_thunder_bluff_roster`;

-- mod-customNPCs: Cataclysm/MoP Thunder Bluff appearances and Wrath placements.
-- Generated by tools/generate_city_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql and the Thunder Bluff roster above.
-- Native displays, armor textures, customization and weapons were checked in build 12340.
-- Only this roster is updated. Existing spawn GUIDs and per-spawn outfit overrides survive.
-- Restart worldserver after applying: model/equipment/addon/spawn caches must also reload.
-- See docs/thunder_bluff-trainers.md for sources, substitutions and placement checks.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_thunder_bluff_appearance`;
CREATE TEMPORARY TABLE `mod_customnpcs_thunder_bluff_appearance` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `display_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL,
  `mainhand` INT UNSIGNED NOT NULL,
  `offhand` INT UNSIGNED NOT NULL,
  `ranged` INT UNSIGNED NOT NULL,
  `stand_state` TINYINT UNSIGNED NOT NULL,
  `sheath_state` TINYINT UNSIGNED NOT NULL
);

-- 4000400: Sunwalker Reha (source 43001, race 6, gender 0).
-- 4000401: Seer Kaya (source 43004, race 6, gender 1).
-- 4000402: Aponi Brightmane (source 43795, race 6, gender 1).
-- 4000403: Tahu Sagewind (source 43796, race 6, gender 0).
-- 4000404: Seer Beryl (source 43870, race 6, gender 0).
-- 4000405: Delano Morisett (source 43881, race 5, gender 0).
-- 4000406: Jensen Thomasson (source 43883, race 5, gender 0).
-- 4000407: Morairania Horton (source 43892, race 5, gender 1).
-- 4000408: Garn Cloudsong (source 51638, race 6, gender 0).
-- 4000409: Kador Cloudsong (source 51639, race 6, gender 0).
-- 4000410: Lama Cloudsong (source 51640, race 6, gender 1).
-- 4000411: Engineer Palehoof (source 52651, race 6, gender 0).
-- 4000412: Nahari Cloudchaser (source 52657, race 6, gender 1).
INSERT INTO `mod_customnpcs_thunder_bluff_appearance` VALUES
  (4000400, 15322, -1402.11, -142.964, 159.665, 3.9619, 48693, 12452, 0, 0, 1),
  (4000401, 15472, -1036.79, -302.023, 159.38, 2.3562, 14836, 0, 0, 0, 1),
  (4000402, 29249, -1405.44, -146.394, 159.608, 1.3963, 35724, 0, 0, 0, 1),
  (4000403, 3775, -1068.49, -295.332, 159.235, 0.4189, 46738, 0, 0, 0, 1),
  (4000404, 3845, -1042.56, -269.509, 159.38, 4.0666, 14873, 0, 0, 0, 1),
  (4000405, 2637, -945.639, 253.208, 97.589, 3.3161, 11019, 0, 0, 0, 1),
  (4000406, 2646, -954.092, 247.661, 98.075, 0.925, 13050, 0, 0, 0, 1),
  (4000407, 3944, -953.965, 255.233, 97.8566, 5.4629, 5276, 0, 0, 0, 1),
  (4000408, 10188, -980.775, 269.899, 137.822, 2.1991, 5304, 0, 0, 0, 1),
  (4000409, 3775, -980.841, 287.174, 137.822, 4.4331, 5291, 0, 0, 0, 1),
  (4000410, 19183, -996.925, 278.464, 137.822, 0.2793, 3361, 0, 0, 0, 1),
  (4000411, 18738, -1264.73, 140.592, 132.77, 4.852, 1902, 0, 0, 0, 1),
  (4000412, 7615, -1225.76, 153.337, 133.57, 5.0964, 0, 0, 0, 0, 1);

-- Use checked native outfits and fixed same-race/gender fallback displays.
DELETE a FROM `mod_customnpcs_outfit_entry` a
INNER JOIN `mod_customnpcs_thunder_bluff_appearance` r ON r.`entry` = a.`creature_entry`;

-- These outfit IDs belong to this module roster; unrelated outfits are untouched.
DELETE FROM `mod_customnpcs_outfit` WHERE `outfit_id` IN (
  4000400, 4000401, 4000402, 4000403, 4000404, 4000405, 4000406, 4000407, 4000408, 4000409, 4000410, 4000411, 4000412
);
INSERT INTO `mod_customnpcs_outfit`
  (`outfit_id`, `race`, `gender`, `class`, `skin`, `face`, `hair`, `hair_color`, `facial_hair`, `guild_id`, `head`, `shoulders`, `shirt`, `chest`, `waist`, `legs`, `feet`, `wrists`, `hands`, `back`, `tabard`, `mainhand`, `offhand`, `ranged`)
VALUES
  (4000400, 6, 0, 2, 4, 1, 9, 0, 2, 0, 0, -53491, -59787, -59788, -53494, -53495, -59789, -55482, -53497, -23045, 0, 48693, 12452, 0),
  (4000401, 6, 1, 5, 5, 3, 6, 3, 1, 0, 0, 0, -59915, -25425, -9203, -25426, -59918, -9206, 0, 0, -10959, 14836, 0, 0),
  (4000402, 6, 1, 2, 4, 1, 7, 0, 1, 0, 0, 0, -59912, -11102, -59913, -11104, -59914, -55482, -11106, -23045, 0, 35724, 0, 0),
  (4000403, 6, 0, 5, 15, 0, 9, 2, 2, 0, -63060, -59736, 0, -61757, -61758, -61759, 0, 0, -59444, 0, 0, 46738, 0, 0),
  (4000404, 6, 0, 5, 8, 2, 7, 0, 5, 0, 0, 0, -59915, -25425, -9203, -25426, -59918, -9206, 0, 0, -10959, 14873, 0, 0),
  (4000405, 5, 0, 9, 3, 9, 6, 0, 0, 0, -15391, -11560, -3816, -9005, -5583, -8166, -9022, 0, 0, 0, 0, 11019, 0, 0),
  (4000406, 5, 0, 9, 5, 5, 4, 4, 14, 0, -15391, -11560, -3816, -9005, -5583, -8166, -9022, 0, -8954, 0, 0, 13050, 0, 0),
  (4000407, 5, 1, 9, 0, 0, 0, 0, 0, 0, 0, 0, -4635, -5334, -5725, -6085, -5463, 0, 0, 0, 0, 5276, 0, 0),
  (4000408, 6, 0, 7, 10, 2, 7, 1, 1, 0, 0, 0, 0, -9202, -9203, -9204, 0, -9206, 0, 0, 0, 5304, 0, 0),
  (4000409, 6, 0, 7, 14, 1, 6, 2, 3, 0, 0, 0, 0, -9628, -11880, -9629, 0, 0, -11564, 0, 0, 5291, 0, 0),
  (4000410, 6, 1, 7, 6, 2, 5, 1, 1, 0, 0, 0, 0, -29417, -46550, -46551, -37886, -9206, -29419, 0, 0, 3361, 0, 0),
  (4000411, 6, 0, 1, 18, 0, 7, 2, 1, 0, 0, 0, 0, -47265, -16036, -15680, -16057, -16244, -16060, 0, 0, 1902, 0, 0),
  (4000412, 6, 1, 1, 6, 2, 3, 1, 1, 0, 0, 0, -14990, -9628, -11880, -11881, -9051, -12147, -11564, 0, 0, 0, 0, 0);

INSERT INTO `mod_customnpcs_outfit_entry` (`creature_entry`, `outfit_id`) VALUES
  (4000400, 4000400),
  (4000401, 4000401),
  (4000402, 4000402),
  (4000403, 4000403),
  (4000404, 4000404),
  (4000405, 4000405),
  (4000406, 4000406),
  (4000407, 4000407),
  (4000408, 4000408),
  (4000409, 4000409),
  (4000410, 4000410),
  (4000411, 4000411),
  (4000412, 4000412);

-- One fixed native fallback per NPC: matches the intended rendered race/gender with outfits disabled.
DELETE m FROM `creature_template_model` m
INNER JOIN `mod_customnpcs_thunder_bluff_appearance` r ON r.`entry` = m.`CreatureID`;
INSERT INTO `creature_template_model`
  (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`)
SELECT `entry`, 0, `display_id`, 1, 1 FROM `mod_customnpcs_thunder_bluff_appearance`;

-- Native held weapons/tools also apply to native fallback displays and to disabled-outfit fallbacks.
DELETE e FROM `creature_equip_template` e
INNER JOIN `mod_customnpcs_thunder_bluff_appearance` r ON r.`entry` = e.`CreatureID`;
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`)
SELECT `entry`, 1, `mainhand`, `offhand`, `ranged` FROM `mod_customnpcs_thunder_bluff_appearance`;

-- Preserve addon paths, mounts, auras and higher bytes; copy supported idle/sheath states only.
INSERT INTO `creature_template_addon` (`entry`, `bytes1`, `bytes2`)
SELECT `entry`, `stand_state`, `sheath_state` FROM `mod_customnpcs_thunder_bluff_appearance`
ON DUPLICATE KEY UPDATE
  `bytes1` = (`bytes1` & 4294967040) | VALUES(`bytes1`),
  `bytes2` = (`bytes2` & 4294967040) | VALUES(`bytes2`);

-- Support both older AzerothCore's creature.id and current creature.id1 schemas.
SET @MOD_CUSTOMNPCS_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
SET @MOD_CUSTOMNPCS_PLACEMENT_SQL := CONCAT(
  'UPDATE `creature` c INNER JOIN `mod_customnpcs_thunder_bluff_appearance` r ON c.`',
  @MOD_CUSTOMNPCS_ENTRY_COLUMN, '` = r.`entry` ',
  'SET c.`position_x` = r.`position_x`, c.`position_y` = r.`position_y`, ',
  'c.`position_z` = r.`position_z`, c.`orientation` = r.`orientation`, c.`equipment_id` = 1 ',
  'WHERE c.`map` = 1 AND c.`position_x` BETWEEN -1700 AND -850 ',
  'AND c.`position_y` BETWEEN -400 AND 450'
);
PREPARE mod_customnpcs_placement FROM @MOD_CUSTOMNPCS_PLACEMENT_SQL;
EXECUTE mod_customnpcs_placement;
DEALLOCATE PREPARE mod_customnpcs_placement;

DROP TEMPORARY TABLE `mod_customnpcs_thunder_bluff_appearance`;
