-- mod-customNPCs: Cataclysm/MoP additions to Undercity, converted to Wrath.
-- Generated by tools/generate_city_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql. Includes new identities, native curricula,
-- checked appearances and map-0 placements. Does not alter existing stock NPCs.
-- Safe to reapply: existing spawn GUIDs and intentional spawn outfit overrides survive.
-- Restart worldserver after applying. See docs/undercity-trainers.md.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_undercity_roster`;
CREATE TEMPORARY TABLE `mod_customnpcs_undercity_roster` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `subname` VARCHAR(100) NOT NULL,
  `gossip_menu_id` INT UNSIGNED NOT NULL,
  `npcflag` INT UNSIGNED NOT NULL,
  `unit_class` TINYINT UNSIGNED NOT NULL,
  `minlevel` TINYINT UNSIGNED NOT NULL,
  `maxlevel` TINYINT UNSIGNED NOT NULL,
  `trainer_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL
);
INSERT INTO `mod_customnpcs_undercity_roster` VALUES
  (4000500, 'Apolos', 'Hunter Trainer', 4474, 49, 2, 50, 50, 7, 1688.03, 398.658, -62.0095, 1.0123),
  (4000501, 'Nathanos Blightcaller', 'Hunter Trainer', 4474, 49, 2, 62, 62, 7, 1691.97, 400.474, -62.0095, 3.0369),
  (4000502, 'Mahala Cloudsong', 'Shaman Trainer', 8110, 49, 2, 60, 60, 14, 1558.5, 344.363, -62.0095, 3.8048),
  (4000503, 'Mala Skywatcher', 'Druid Trainer', 4508, 49, 2, 60, 60, 33, 1556.23, 342.526, -62.0095, 0.6807),
  (4000504, 'Neller Fayne', 'Jewelcrafting Trainer', 7815, 80, 1, 30, 30, 111, 1645.46, 331.009, -61.941, 1.9548);

-- Neutral custom-realm faction, valid creature stat classes, matching original titles/services.
INSERT INTO `creature_template`
  (`entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`,
   `npcflag`, `unit_class`, `unit_flags`, `type`, `AIName`, `ScriptName`, `flags_extra`)
SELECT `entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, 2, 35,
  `npcflag`, `unit_class`, 2, 7, 'NullCreatureAI', '', 2
FROM `mod_customnpcs_undercity_roster`
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`), `subname` = VALUES(`subname`),
  `gossip_menu_id` = VALUES(`gossip_menu_id`), `npcflag` = VALUES(`npcflag`),
  `unit_class` = VALUES(`unit_class`);

DELETE t FROM `creature_default_trainer` t
INNER JOIN `mod_customnpcs_undercity_roster` r ON r.`entry` = t.`CreatureId`;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`)
SELECT `entry`, `trainer_id` FROM `mod_customnpcs_undercity_roster`;

-- Retain only source supplies present in Wrath, without later currencies/recipes.
DELETE v FROM `npc_vendor` v
INNER JOIN `mod_customnpcs_undercity_roster` r ON r.`entry` = v.`entry`;

-- Seed only missing Undercity spawns. Do not delete/recreate existing NPCs or move outside-city copies.
SET @MOD_CUSTOMNPCS_UNDERCITY_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_undercity_existing`;
SET @MOD_CUSTOMNPCS_UNDERCITY_EXISTING_SQL := CONCAT(
  'CREATE TEMPORARY TABLE `mod_customnpcs_undercity_existing` AS ',
  'SELECT c.`guid`, c.`', @MOD_CUSTOMNPCS_UNDERCITY_ENTRY_COLUMN, '` AS `entry` ',
  'FROM `creature` c INNER JOIN `mod_customnpcs_undercity_roster` r ON r.`entry` = c.`',
  @MOD_CUSTOMNPCS_UNDERCITY_ENTRY_COLUMN, '` ',
  'WHERE c.`map` = 0 AND c.`position_x` BETWEEN 1300 AND 2100 ',
  'AND c.`position_y` BETWEEN -100 AND 800'
);
PREPARE mod_customnpcs_undercity_existing FROM @MOD_CUSTOMNPCS_UNDERCITY_EXISTING_SQL;
EXECUTE mod_customnpcs_undercity_existing;
DEALLOCATE PREPARE mod_customnpcs_undercity_existing;
SET @MOD_CUSTOMNPCS_UNDERCITY_INSERT_SQL := CONCAT(
  'INSERT INTO `creature` (`', @MOD_CUSTOMNPCS_UNDERCITY_ENTRY_COLUMN,
  '`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `equipment_id`, ',
  '`position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `MovementType`) ',
  'SELECT r.`entry`, 0, 1497, 1497, 1, 1, 1, r.`position_x`, r.`position_y`, r.`position_z`, ',
  'r.`orientation`, 300, 0 FROM `mod_customnpcs_undercity_roster` r ',
  'LEFT JOIN `mod_customnpcs_undercity_existing` s ON s.`entry` = r.`entry` WHERE s.`guid` IS NULL'
);
PREPARE mod_customnpcs_undercity_insert FROM @MOD_CUSTOMNPCS_UNDERCITY_INSERT_SQL;
EXECUTE mod_customnpcs_undercity_insert;
DEALLOCATE PREPARE mod_customnpcs_undercity_insert;
DROP TEMPORARY TABLE `mod_customnpcs_undercity_existing`;
DROP TEMPORARY TABLE `mod_customnpcs_undercity_roster`;

-- mod-customNPCs: Cataclysm/MoP Undercity appearances and Wrath placements.
-- Generated by tools/generate_city_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql and the Undercity roster above.
-- Native displays, armor textures, customization and weapons were checked in build 12340.
-- Only this roster is updated. Existing spawn GUIDs and per-spawn outfit overrides survive.
-- Restart worldserver after applying: model/equipment/addon/spawn caches must also reload.
-- See docs/undercity-trainers.md for sources, substitutions and placement checks.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_undercity_appearance`;
CREATE TEMPORARY TABLE `mod_customnpcs_undercity_appearance` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `display_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL,
  `mainhand` INT UNSIGNED NOT NULL,
  `offhand` INT UNSIGNED NOT NULL,
  `ranged` INT UNSIGNED NOT NULL,
  `stand_state` TINYINT UNSIGNED NOT NULL,
  `sheath_state` TINYINT UNSIGNED NOT NULL
);

-- 4000500: Apolos (source 39116, race 5, gender 0).
-- 4000501: Nathanos Blightcaller (source 50609, race 5, gender 0).
-- 4000502: Mahala Cloudsong (source 52317, race 6, gender 1).
-- 4000503: Mala Skywatcher (source 52319, race 6, gender 1).
-- 4000504: Neller Fayne (source 52587, race 5, gender 0).
INSERT INTO `mod_customnpcs_undercity_appearance` VALUES
  (4000500, 29652, 1688.03, 398.658, -62.0095, 1.0123, 41022, 0, 0, 0, 1),
  (4000501, 11814, 1691.97, 400.474, -62.0095, 3.0369, 2183, 2183, 5258, 0, 0),
  (4000502, 23239, 1558.5, 344.363, -62.0095, 3.8048, 15274, 0, 0, 0, 1),
  (4000503, 23651, 1556.23, 342.526, -62.0095, 0.6807, 13337, 0, 0, 0, 1),
  (4000504, 27589, 1645.46, 331.009, -61.941, 1.9548, 0, 0, 0, 0, 1);

-- Use checked native outfits and fixed same-race/gender fallback displays.
DELETE a FROM `mod_customnpcs_outfit_entry` a
INNER JOIN `mod_customnpcs_undercity_appearance` r ON r.`entry` = a.`creature_entry`;

-- These outfit IDs belong to this module roster; unrelated outfits are untouched.
DELETE FROM `mod_customnpcs_outfit` WHERE `outfit_id` IN (
  4000500, 4000501, 4000502, 4000503, 4000504
);
INSERT INTO `mod_customnpcs_outfit`
  (`outfit_id`, `race`, `gender`, `class`, `skin`, `face`, `hair`, `hair_color`, `facial_hair`, `guild_id`, `head`, `shoulders`, `shirt`, `chest`, `waist`, `legs`, `feet`, `wrists`, `hands`, `back`, `tabard`, `mainhand`, `offhand`, `ranged`)
VALUES
  (4000500, 5, 0, 3, 1, 7, 13, 5, 8, 0, -42259, 0, -44156, -44156, -44675, -44676, -56541, -44674, -45290, 0, 0, 41022, 0, 0),
  (4000501, 5, 0, 3, 0, 2, 0, 0, 1, 0, -24917, -11375, -25189, -25190, -18994, -4388, -21634, 0, -16686, 0, 0, 2183, 2183, 5258),
  (4000502, 6, 1, 7, 3, 2, 1, 1, 1, 0, 0, 0, 0, -45875, 0, -42526, -15643, 0, -43151, 0, 0, 15274, 0, 0),
  (4000503, 6, 1, 11, 7, 1, 8, 1, 4, 0, -10998, 0, 0, -34644, -34637, -34642, -6028, -34641, 0, 0, 0, 13337, 0, 0),
  (4000504, 5, 0, 1, 4, 3, 0, 0, 6, 0, -1170, 0, -5326, -27599, -9490, -27598, -25281, 0, 0, 0, 0, 0, 0, 0);

INSERT INTO `mod_customnpcs_outfit_entry` (`creature_entry`, `outfit_id`) VALUES
  (4000500, 4000500),
  (4000501, 4000501),
  (4000502, 4000502),
  (4000503, 4000503),
  (4000504, 4000504);

-- One fixed native fallback per NPC: matches the intended rendered race/gender with outfits disabled.
DELETE m FROM `creature_template_model` m
INNER JOIN `mod_customnpcs_undercity_appearance` r ON r.`entry` = m.`CreatureID`;
INSERT INTO `creature_template_model`
  (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`)
SELECT `entry`, 0, `display_id`, 1, 1 FROM `mod_customnpcs_undercity_appearance`;

-- Native held weapons/tools also apply to native fallback displays and to disabled-outfit fallbacks.
DELETE e FROM `creature_equip_template` e
INNER JOIN `mod_customnpcs_undercity_appearance` r ON r.`entry` = e.`CreatureID`;
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`)
SELECT `entry`, 1, `mainhand`, `offhand`, `ranged` FROM `mod_customnpcs_undercity_appearance`;

-- Preserve addon paths, mounts, auras and higher bytes; copy supported idle/sheath states only.
INSERT INTO `creature_template_addon` (`entry`, `bytes1`, `bytes2`)
SELECT `entry`, `stand_state`, `sheath_state` FROM `mod_customnpcs_undercity_appearance`
ON DUPLICATE KEY UPDATE
  `bytes1` = (`bytes1` & 4294967040) | VALUES(`bytes1`),
  `bytes2` = (`bytes2` & 4294967040) | VALUES(`bytes2`);

-- Support both older AzerothCore's creature.id and current creature.id1 schemas.
SET @MOD_CUSTOMNPCS_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
SET @MOD_CUSTOMNPCS_PLACEMENT_SQL := CONCAT(
  'UPDATE `creature` c INNER JOIN `mod_customnpcs_undercity_appearance` r ON c.`',
  @MOD_CUSTOMNPCS_ENTRY_COLUMN, '` = r.`entry` ',
  'SET c.`position_x` = r.`position_x`, c.`position_y` = r.`position_y`, ',
  'c.`position_z` = r.`position_z`, c.`orientation` = r.`orientation`, c.`equipment_id` = 1 ',
  'WHERE c.`map` = 0 AND c.`position_x` BETWEEN 1300 AND 2100 ',
  'AND c.`position_y` BETWEEN -100 AND 800'
);
PREPARE mod_customnpcs_placement FROM @MOD_CUSTOMNPCS_PLACEMENT_SQL;
EXECUTE mod_customnpcs_placement;
DEALLOCATE PREPARE mod_customnpcs_placement;

DROP TEMPORARY TABLE `mod_customnpcs_undercity_appearance`;
