#!/usr/bin/env python3
"""Generate Chapter 1 world SQL and C++ identifiers from its implementation manifest."""

import argparse
import json
import math
from pathlib import Path

from broken_seal_outfits import validate_outfits

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'data/quests/broken_seal_chapter1.json'
BASE = ROOT / 'data/sql/db-world/base/broken_seal_chapter1.sql'
UPDATE = ROOT / 'data/sql/db-world/updates/2026_10_06_00_broken_seal_chapter1.sql'
HEADER = ROOT / 'src/BrokenSealChapter1Data.h'


def quote(value):
    return "'" + str(value).replace('\\', '\\\\').replace("'", "''") + "'"


def rows(table, columns, values):
    def scalar(value):
        if isinstance(value, str):
            return quote(value)
        return str(value)
    return (f'INSERT INTO `{table}` (' + ', '.join(f'`{c}`' for c in columns) + ') VALUES\n'
            + ',\n'.join('  (' + ', '.join(scalar(v) for v in row) + ')' for row in values) + ';\n')


def upsert(table, columns, values, keys):
    return rows(table, columns, values).rstrip(';\n') + '\nON DUPLICATE KEY UPDATE\n  ' + ', '.join(
        f'`{c}` = VALUES(`{c}`)' for c in columns if c not in keys) + ';\n'


def validate(data):
    validate_outfits(data['actors'] + data['hostile'])
    ids = data['ids']
    assert len(data['quests']) == 9 and data['chapter'] == 'C01'
    for prefix in ('QUEST_', 'NPC_', 'CREDIT_', 'GO_', 'ITEM_'):
        values = [v for k, v in ids.items() if k.startswith(prefix)]
        assert len(values) == len(set(values)), prefix
    assert not {v for k, v in ids.items() if k.startswith('NPC_')} & {
        v for k, v in ids.items() if k.startswith('CREDIT_')}
    for p in data['points'].values():
        assert len(p) == 4 and all(math.isfinite(v) for v in p)
    for q in data['quests']:
        assert q['id'] == ids[q['key']]
        assert len(q.get('credits', {})) <= 4 and len(q.get('required_items', {})) <= 6
        if q.get('source_item'):
            assert q['source_item'] in ids
        assert len(q.get('reward_choices', [])) <= 6
    assert len(data['escort_routes']) == 3
    assert {r['credit'] for r in data['escort_routes']} == {
        'CREDIT_CAPTIVE_A', 'CREDIT_CAPTIVE_B', 'CREDIT_CAPTIVE_C'}
    assert data['quests'][-1]['reward_choices'] and not data['quests'][-1].get('next_quest')


def header(data):
    lines = ['// Generated by tools/generate_broken_seal_chapter1.py. Do not edit.',
             '#ifndef MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER1_DATA_H',
             '#define MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER1_DATA_H', '',
             '#include <array>', '#include <cstdint>', '', 'namespace BrokenSeal::Chapter1', '{',
             'enum Id : std::uint32_t', '{']
    lines += [f'    {name} = {value},' for name, value in data['ids'].items()]
    lines += ['};', '', 'struct Point', '{', '    float x;', '    float y;', '    float z;',
              '    float orientation;', '};', '', 'inline constexpr std::uint32_t MapId = 1;',
              'inline constexpr std::size_t DistinctCount = 3;', '']
    for name, keys in [('TrailCredits', ['CREDIT_TRAIL_A', 'CREDIT_TRAIL_B', 'CREDIT_TRAIL_C']),
                       ('WardCredits', ['CREDIT_WARD_A', 'CREDIT_WARD_B', 'CREDIT_WARD_C']),
                       ('CaptiveCredits', ['CREDIT_CAPTIVE_A', 'CREDIT_CAPTIVE_B', 'CREDIT_CAPTIVE_C']),
                       ('CaptiveEntries', ['NPC_CAPTIVE_A', 'NPC_CAPTIVE_B', 'NPC_CAPTIVE_C']),
                       ('CageEntries', ['GO_CAGE_A', 'GO_CAGE_B', 'GO_CAGE_C']),
                       ('WardEntries', ['GO_WARD_A', 'GO_WARD_B', 'GO_WARD_C']),
                       ('TrailEntries', ['GO_TRAIL_A', 'GO_TRAIL_B', 'GO_TRAIL_C'])]:
        lines += [f'inline constexpr std::array<std::uint32_t, 3> {name} =',
                  '{', '    ' + ', '.join(keys), '};', '']
    for name, points in [('CaptiveStarts', [f'cage_{i}' for i in range(1, 4)]),
                         ('RecruitPatrol', data['recruit_patrol'])]:
        lines += [f'inline constexpr std::array<Point, {len(points)}> {name} =', '{{']
        for key in points:
            lines += ['    {' + ', '.join(f'{v:.4f}f' for v in data['points'][key]) + '},']
        lines += ['}};', '']
    p = data['points'][data['safe_point']]
    lines += ['inline constexpr Point Refuge = {' + ', '.join(f'{v:.4f}f' for v in p) + '};',
              '}', '', '#endif', '']
    return '\n'.join(lines)


def sql(data):
    ids = data['ids']
    owned = [('creature', a['entry']) for a in data['actors'] + data['hostile']]
    owned += [('creature', ids['NPC_SCENE'])]
    owned += [('creature', v) for k, v in ids.items() if k.startswith('CREDIT_')]
    owned += [('gameobject', o['entry']) for o in data['objects']]
    owned += [('quest', q['id']) for q in data['quests']]
    owned += [('item', i['entry']) for i in data['items']]
    owned += [('outfit', a['entry']) for a in data['actors'] + data['hostile'] if a.get('outfit')]
    owned += [('npc_text', data['ids'][key]) for key in data['npc_texts']]
    owned += [('gossip_menu', data['ids'][key]) for key in data['npc_texts']]
    owned += [('page', i['page']) for i in data['items'] if i.get('page')]
    text = """-- mod-customNPCs: The Broken Seal, Chapter 1 (levels 20-25).
-- Generated from data/quests/broken_seal_chapter1.json. Native 3.3.5a assets only.
-- Requires custom_npc_appearances.sql and the rebuilt C++ module.
-- Ownership checks reject occupied custom IDs on first installation.
-- Reapplication preserves spawn GUIDs and unrelated world/character content.
-- See docs/broken-seal/chapter1-implementation.md before installation.

CREATE TABLE IF NOT EXISTS `mod_customnpcs_bs_content` (
  `kind` VARCHAR(16) NOT NULL,
  `entry` INT UNSIGNED NOT NULL,
  `chapter` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`kind`, `entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TEMPORARY TABLE IF EXISTS `bs_c01_ids`;
CREATE TEMPORARY TABLE `bs_c01_ids` (
  `kind` VARCHAR(16) NOT NULL,
  `entry` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`kind`, `entry`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
"""
    text += rows('bs_c01_ids', ['kind', 'entry'], owned)
    text += """
-- Duplicate-primary-key errors are intentional when an unowned ID is occupied.
-- This guard works without stored-procedure privileges and with permissive SQL modes.
DROP TEMPORARY TABLE IF EXISTS `bs_c01_collision_guard`;
CREATE TEMPORARY TABLE `bs_c01_collision_guard` (`id` TINYINT PRIMARY KEY);
INSERT INTO `bs_c01_collision_guard` VALUES (1);
"""
    for kind, table, column in [('creature', 'creature_template', 'entry'),
                                ('gameobject', 'gameobject_template', 'entry'),
                                ('quest', 'quest_template', 'ID'), ('item', 'item_template', 'entry'),
                                ('outfit', 'mod_customnpcs_outfit', 'outfit_id'),
                                ('npc_text', 'npc_text', 'ID'), ('gossip_menu', 'gossip_menu', 'MenuID'),
                                ('page', 'page_text', 'ID')]:
        text += f"""INSERT INTO `bs_c01_collision_guard`
SELECT 1 FROM `{table}` t
INNER JOIN `bs_c01_ids` r ON r.`kind` = '{kind}' AND r.`entry` = t.`{column}`
LEFT JOIN `mod_customnpcs_bs_content` o ON o.`kind` = r.`kind` AND o.`entry` = r.`entry` AND o.`chapter` = 1
WHERE o.`entry` IS NULL LIMIT 1;
"""
    text += """
DROP TEMPORARY TABLE `bs_c01_collision_guard`;
START TRANSACTION;
INSERT INTO `mod_customnpcs_bs_content` (`kind`, `entry`, `chapter`)
SELECT `kind`, `entry`, 1 FROM `bs_c01_ids`
ON DUPLICATE KEY UPDATE `chapter` = VALUES(`chapter`);

"""
    ccols = ['entry', 'name', 'subname', 'minlevel', 'maxlevel', 'exp', 'faction', 'npcflag',
             'unit_class', 'unit_flags', 'type', 'AIName', 'ScriptName', 'HealthModifier',
             'DamageModifier', 'ExperienceModifier', 'lootid', 'flags_extra']
    creatures = []
    model_rows = []
    for a in data['actors']:
        script = {'contact': 'npc_bs_c01_contact', 'captive': 'npc_bs_c01_captive',
                  'recruit': 'npc_bs_c01_recruit'}[a['script_role']]
        creatures.append([a['entry'], a['name'], 'The Vale Expedition' if a['script_role'] == 'contact' else '',
                          25, 25, 0, 35, a['npc_flags'], 1, 770, 7, '', script, 1, 1, 0, 0, 2])
        model_rows.append([a['entry'], 0, a['fallback_display'], 1, 1])
    for a in data['hostile']:
        creatures.append([a['entry'], a['name'], '', *a['level'], 0, 14, 0, 1, 0,
                          4 if a['key'] == 'NPC_EARTH' else 7, 'SmartAI' if a['key'] == 'NPC_EARTH' else '',
                          '' if a['key'] == 'NPC_EARTH' else 'npc_bs_c01_cult', 1, 1, 1,
                          a['entry'] if a.get('loot_item') else 0, 0])
        model_rows.append([a['entry'], 0, a['display'], 1, 1])
    creatures.append([ids['NPC_SCENE'], 'Expedition Observation Focus', '', 1, 1, 0, 35, 0,
                      1, 33555202, 10, '', 'npc_bs_c01_observation', 1, 1, 0, 0, 2])
    model_rows.append([ids['NPC_SCENE'], 0, 11686, 1, 1])
    for key, entry in ids.items():
        if key.startswith('CREDIT_'):
            creatures.append([entry, key.replace('CREDIT_', '').replace('_', ' ').title(), '', 1, 1, 0,
                              35, 0, 1, 33555202, 10, 'NullCreatureAI', '', 1, 1, 0, 0, 2])
            model_rows.append([entry, 0, 11686, 1, 1])
    text += upsert('creature_template', ccols, creatures, ['entry'])
    creature_ids = ', '.join(str(v) for k, v in owned if k == 'creature')
    text += f'DELETE FROM `creature_template_model` WHERE `CreatureID` IN ({creature_ids});\n'
    text += rows('creature_template_model', ['CreatureID', 'Idx', 'CreatureDisplayID', 'DisplayScale', 'Probability'], model_rows)
    outfit_rows = []
    outfit_cols = ['outfit_id', 'race', 'gender', 'class', 'skin', 'face', 'hair', 'hair_color', 'facial_hair',
                   'chest', 'shoulders', 'shirt', 'waist', 'legs', 'feet', 'hands', 'mainhand', 'ranged']
    dressed = [a for a in data['actors'] + data['hostile'] if a.get('outfit')]
    for a in dressed:
        outfit_rows.append([a['entry']] + [a['outfit'].get(c, 1 if c == 'class' else 0) for c in outfit_cols[1:]])
    text += upsert('mod_customnpcs_outfit', outfit_cols, outfit_rows, ['outfit_id'])
    text += upsert('mod_customnpcs_outfit_entry', ['creature_entry', 'outfit_id'],
                   [[a['entry'], a['entry']] for a in dressed], ['creature_entry'])
    text += f'DELETE FROM `creature_template_addon` WHERE `entry` = {ids["NPC_JAROD"]};\n'
    text += rows('creature_template_addon', ['entry', 'emote'], [[ids['NPC_JAROD'], 68]])

    # Enemy spell definitions are native; cosmetic outfits never supply combat stats.
    text += f'DELETE FROM `smart_scripts` WHERE `source_type` = 0 AND `entryorguid` IN ({", ".join(str(a["entry"]) for a in data["hostile"])});\n'
    smart = []
    for a in data['hostile']:
        smart.append([a['entry'], 0, 0, 0, 0, 0, 100, 0, 2500, 4000, 7000, 10000,
                      11, ids[a['spell']], 0, 0, 0, 0, 0, 2, 0, 0, 0,
                      f'Broken Seal C01: {a["name"]} - native combat spell'])
    text += rows('smart_scripts', ['entryorguid', 'source_type', 'id', 'link', 'event_type', 'event_phase_mask',
                                 'event_chance', 'event_flags', 'event_param1', 'event_param2', 'event_param3',
                                 'event_param4', 'action_type', 'action_param1', 'action_param2', 'action_param3',
                                 'action_param4', 'action_param5', 'action_param6', 'target_type', 'target_param1',
                                 'target_param2', 'target_param3', 'comment'], smart)

    icols = ['entry', 'class', 'subclass', 'name', 'displayid', 'Quality', 'InventoryType', 'AllowableClass',
             'AllowableRace', 'ItemLevel', 'RequiredLevel', 'maxcount', 'stackable', 'bonding',
             'stat_type1', 'stat_value1', 'stat_type2', 'stat_value2', 'stat_type3', 'stat_value3',
             'PageText', 'description', 'spellid_1', 'spelltrigger_1', 'ScriptName']
    ir = []
    for item in data['items']:
        equipment = item.get('equipment', False)
        stats = item.get('stats', []) + [[0, 0]] * 3
        ir.append([item['entry'], 4 if equipment else 12, 0, item['name'], item['display'], 2 if equipment else 1,
                   11 if equipment else 0, -1, -1, item.get('level', 1), item.get('required_level', 0), 1, 1,
                   1 if equipment else 4, *stats[0], *stats[1], *stats[2], item.get('page', 0),
                   item.get('description', 'The Vale Expedition'), ids[item['spell']] if item.get('spell') else 0,
                   0, item.get('script', '')])
    text += upsert('item_template', icols, ir, ['entry'])
    pages = [[i['page'], i['text'], 0] for i in data['items'] if i.get('page')]
    text += upsert('page_text', ['ID', 'Text', 'NextPageID'], pages, ['ID'])
    text += f'DELETE FROM `creature_loot_template` WHERE `Entry` = {ids["NPC_CULT_SCOUT"]};\n'
    text += rows('creature_loot_template', ['Entry', 'Item', 'Reference', 'Chance', 'QuestRequired', 'LootMode',
                                          'GroupId', 'MinCount', 'MaxCount'],
                 [[ids['NPC_CULT_SCOUT'], ids['ITEM_ORDERS'], 0, 100, 1, 1, 0, 1, 1]])

    qcols = ['ID', 'QuestType', 'QuestLevel', 'MinLevel', 'QuestSortID', 'RewardXPDifficulty', 'RewardMoney',
             'StartItem', 'Flags', 'AllowableRaces', 'LogTitle', 'LogDescription', 'QuestDescription',
             'QuestCompletionLog']
    qcols += [f'RequiredNpcOrGo{i}' for i in range(1, 5)] + [f'RequiredNpcOrGoCount{i}' for i in range(1, 5)]
    qcols += [f'ObjectiveText{i}' for i in range(1, 5)]
    qcols += [f'RequiredItemId{i}' for i in range(1, 7)] + [f'RequiredItemCount{i}' for i in range(1, 7)]
    qcols += [f'RewardChoiceItemID{i}' for i in range(1, 7)] + [f'RewardChoiceItemQuantity{i}' for i in range(1, 7)]
    qr, addons, starters, enders, offers, requests = [], [], [], [], [], []
    names = {'NPC_CULT_SCOUT': 'Twilight Scouts defeated', 'CREDIT_COMPARE': 'Orders and rubbing compared',
             'CREDIT_COMMANDER': 'Jarod observed safely', 'CREDIT_RECRUIT': 'Recruit watch change observed',
             'CREDIT_SIGNAL': 'Extraction signal agreed'}
    for q in data['quests']:
        credits = list(q.get('credits', {}).items())
        required = list(q.get('required_items', {}).items())
        rewards = q.get('reward_choices', [])
        labels = [names.get(k, k.replace('CREDIT_', '').replace('_', ' ').title() + ' completed') for k, _ in credits]
        qr.append([q['id'], 2, q['level'], q['min_level'], 406, q['xp_difficulty'], q['money'],
                   ids[q['source_item']] if q.get('source_item') else 0, 0,
                   1101 if q['faction'] == 'Alliance' else 690 if q['faction'] == 'Horde' else 0,
                   q['title'], q['objectives'], q['description'], q['objectives'],
                   *([ids[k] for k, _ in credits] + [0] * (4 - len(credits))),
                   *([v for _, v in credits] + [0] * (4 - len(credits))),
                   *(labels + [''] * (4 - len(labels))),
                   *([ids[k] for k, _ in required] + [0] * (6 - len(required))),
                   *([v for _, v in required] + [0] * (6 - len(required))),
                   *([ids[k] for k in rewards] + [0] * (6 - len(rewards))),
                   *([1] * len(rewards) + [0] * (6 - len(rewards)))])
        addons.append([q['id'], ids[q['previous']] if q['previous'] else 0,
                       ids['QUEST_WAGON'] if q['key'].startswith('QUEST_COMMISSION') else 0,
                       q.get('exclusive_group', 0), 1 if q.get('source_item') else 0, 256])
        starters.append([ids[q['giver']], q['id']])
        enders.append([ids[q['turn_in']], q['id']])
        offers.append([q['id'], q['completion']])
        requests.append([q['id'], q['objectives']])
    text += upsert('quest_template', qcols, qr, ['ID'])
    text += upsert('quest_template_addon', ['ID', 'PrevQuestID', 'NextQuestID', 'ExclusiveGroup', 'ProvidedItemCount', 'SpecialFlags'], addons, ['ID'])
    quest_ids = ', '.join(str(q['id']) for q in data['quests'])
    for table in ('creature_queststarter', 'creature_questender'):
        text += f'DELETE FROM `{table}` WHERE `quest` IN ({quest_ids});\n'
    text += rows('creature_queststarter', ['id', 'quest'], starters)
    text += rows('creature_questender', ['id', 'quest'], enders)
    text += upsert('quest_offer_reward', ['ID', 'RewardText'], offers, ['ID'])
    text += upsert('quest_request_items', ['ID', 'CompletionText'], requests, ['ID'])
    text += f'DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 19 AND `SourceEntry` IN ({quest_ids});\n'
    text += rows('conditions', ['SourceTypeOrReferenceId', 'SourceEntry', 'ElseGroup', 'ConditionTypeOrReference',
                              'ConditionValue1', 'Comment'],
                 [[19, ids['QUEST_WAGON'], n, 8, ids[key], 'Broken Seal C01: either faction invitation must be rewarded']
                  for n, key in enumerate(['QUEST_COMMISSION_A', 'QUEST_COMMISSION_H'])])

    text += f'DELETE FROM `quest_poi_points` WHERE `QuestID` IN ({quest_ids});\n'
    text += f'DELETE FROM `quest_poi` WHERE `QuestID` IN ({quest_ids});\n'
    actor_points = {a['key']: a['point'] for a in data['actors'] if a['point']}
    objective_points = {
        'QUEST_WAGON': [(0, 'wagon')],
        'QUEST_TRAIL': [(0, 'scout_5'), (1, 'trail_1'), (2, 'trail_2'), (3, 'trail_3')],
        'QUEST_RESCUE': [(0, 'cage_1'), (1, 'cage_2'), (2, 'cage_3')],
        'QUEST_WARDS': [(0, 'ward_1'), (1, 'ward_2'), (2, 'ward_3')],
        'QUEST_COMPARE': [(0, 'ortell')], 'QUEST_COMMANDER': [(0, 'cover')],
        'QUEST_RECRUIT': [(0, 'drop'), (1, 'ortell')],
    }
    poi_rows, poi_points = [], []
    for q in data['quests']:
        choices = [(-1, actor_points[q['turn_in']])] + objective_points.get(q['key'], [])
        for index, (objective, name) in enumerate(choices):
            p = data['points'][name]
            poi_rows.append([q['id'], index, objective, 1, data['world_map_area_id'], 0, 0, 0])
            poi_points.append([q['id'], index, 0, round(p[0]), round(p[1])])
    text += rows('quest_poi', ['QuestID', 'id', 'ObjectiveIndex', 'MapID', 'WorldMapAreaId', 'Floor', 'Priority', 'Flags'], poi_rows)
    text += rows('quest_poi_points', ['QuestID', 'Idx1', 'Idx2', 'X', 'Y'], poi_points)

    menus, ntexts = [], []
    for key, words in data['npc_texts'].items():
        entry = ids[key]
        menus.append([entry, entry]); ntexts.append([entry, words, 1])
    text += upsert('npc_text', ['ID', 'text0_0', 'Probability0'], ntexts, ['ID'])
    menu_ids = ', '.join(str(v[0]) for v in menus)
    text += f'DELETE FROM `gossip_menu` WHERE `MenuID` IN ({menu_ids});\n'
    text += rows('gossip_menu', ['MenuID', 'TextID'], menus)
    text += f'UPDATE `creature_template` SET `gossip_menu_id` = `entry` WHERE `entry` IN ({menu_ids});\n'

    gcols = ['entry', 'type', 'displayId', 'name', 'size', 'Data1', 'Data3', 'Data5', 'Data18', 'ScriptName']
    text += upsert('gameobject_template', gcols,
                   [[o['entry'], 5 if o['decorative'] else 10, o['display'], o['name'], o['scale'],
                     ids[o['quest']] if o['quest'] else 0, 0, 0, 1,
                     '' if o['decorative'] else 'go_bs_c01_interaction'] for o in data['objects']], ['entry'])

    # Dynamically allocated native GUIDs avoid collisions and preserve existing overrides.
    for kind in ('creature', 'gameobject'):
        text += f'DROP TEMPORARY TABLE IF EXISTS `bs_c01_{kind}_spawns`;\n'
        text += f'CREATE TEMPORARY TABLE `bs_c01_{kind}_spawns` (`spawn_key` VARCHAR(100) PRIMARY KEY, `entry` INT UNSIGNED, `x` FLOAT, `y` FLOAT, `z` FLOAT, `o` FLOAT) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n'
    spawns = [[f'BS-C01:{a["key"]}:{a["point"]}', a['entry'], *data['points'][a['point']]]
              for a in data['actors'] if a['point']]
    spawns += [[f'BS-C01:{a["key"]}:{p}', a['entry'], *data['points'][p]]
               for a in data['hostile'] for p in a['points']]
    text += rows('bs_c01_creature_spawns', ['spawn_key', 'entry', 'x', 'y', 'z', 'o'], spawns)
    text += rows('bs_c01_gameobject_spawns', ['spawn_key', 'entry', 'x', 'y', 'z', 'o'],
                 [[f'BS-C01:{o["key"]}', o['entry'], *data['points'][o['point']]] for o in data['objects']])
    text += """
SET @BS_C01_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature' AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
SET @BS_C01_INSERT := CONCAT(
  'INSERT INTO `creature` (`', @BS_C01_ENTRY_COLUMN, '`, `map`, `zoneId`, `spawnMask`, `phaseMask`, ',
  '`position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `curhealth`, `curmana`, `Comment`) ',
  'SELECT s.`entry`, 1, 406, 1, 1, s.`x`, s.`y`, s.`z`, s.`o`, 90, 0, 0, s.`spawn_key` ',
  'FROM `bs_c01_creature_spawns` s LEFT JOIN `creature` c ON c.`Comment` = s.`spawn_key` WHERE c.`guid` IS NULL'
);
PREPARE bs_c01_stmt FROM @BS_C01_INSERT;
EXECUTE bs_c01_stmt;
DEALLOCATE PREPARE bs_c01_stmt;
SET @BS_C01_UPDATE := CONCAT(
  'UPDATE `creature` c INNER JOIN `bs_c01_creature_spawns` s ON c.`Comment` = s.`spawn_key` ',
  'SET c.`', @BS_C01_ENTRY_COLUMN, '` = s.`entry`, c.`position_x` = s.`x`, c.`position_y` = s.`y`, ',
  'c.`position_z` = s.`z`, c.`orientation` = s.`o`'
);
PREPARE bs_c01_stmt FROM @BS_C01_UPDATE;
EXECUTE bs_c01_stmt;
DEALLOCATE PREPARE bs_c01_stmt;
INSERT INTO `gameobject`
  (`id`, `map`, `zoneId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`,
   `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `Comment`)
SELECT s.`entry`, 1, 406, 1, 1, s.`x`, s.`y`, s.`z`, s.`o`, SIN(s.`o` / 2), COS(s.`o` / 2), 90, 100, 1, s.`spawn_key`
FROM `bs_c01_gameobject_spawns` s LEFT JOIN `gameobject` g ON g.`Comment` = s.`spawn_key` WHERE g.`guid` IS NULL;
UPDATE `gameobject` g INNER JOIN `bs_c01_gameobject_spawns` s ON g.`Comment` = s.`spawn_key`
SET g.`id` = s.`entry`, g.`position_x` = s.`x`, g.`position_y` = s.`y`, g.`position_z` = s.`z`, g.`orientation` = s.`o`,
  g.`rotation2` = SIN(s.`o` / 2), g.`rotation3` = COS(s.`o` / 2);
DROP TEMPORARY TABLE `bs_c01_creature_spawns`;
DROP TEMPORARY TABLE `bs_c01_gameobject_spawns`;
DROP TEMPORARY TABLE `bs_c01_ids`;
COMMIT;
"""
    return text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = json.loads(MANIFEST.read_text())
    validate(data)
    content = sql(data)
    for path, value in [(BASE, content), (UPDATE, content), (HEADER, header(data))]:
        if args.check:
            assert path.is_file() and path.read_text() == value, f'Stale generated file: {path}'
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(value)
    print('Chapter 1: validated and generated matching base/update SQL and C++ identifiers.')


if __name__ == '__main__':
    main()
