#!/usr/bin/env python3
"""Generate shared hub scenery, safety identifiers and reversible spawn clearances."""
import argparse
import json
from pathlib import Path
from generate_broken_seal_chapter1 import rows, upsert
from generate_broken_seal_chapter3 import sql as chapter_sql

from broken_seal_outfits import validate_outfits

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'data/quests/broken_seal_hubs.json'
BASE = ROOT / 'data/sql/db-world/base/broken_seal_hubs.sql'
UPDATE = ROOT / 'data/sql/db-world/updates/2026_10_06_03_broken_seal_hubs.sql'
HEADER = ROOT / 'src/BrokenSealHubsData.h'


def validate(d):
    validate_outfits(d['guards'] + d['residents'])
    assert len(d['hubs']) == len(d['guards']) == len(d['residents'])
    assert len({h['key'] for h in d['hubs']}) == len(d['hubs'])
    npcs = [a['entry'] for a in d['guards'] + d['residents']]
    assert len(npcs) == len(set(npcs))
    assert len({o['entry'] for o in d['objects']}) == len(d['objects'])
    for hub in d['hubs']:
        assert hub['screen_radius'] > hub['radius'] > 0
        props = [o for o in d['objects'] if o['hub'] == hub['key']]
        roles = {o['role'] for o in props}
        assert {'shelter','supplies','lighting'} <= roles, (hub['key'], roles)
        assert roles & {'workstation','medicine','equipment'}, (hub['key'], roles)
        assert len(props) >= 5
        assert all(o['terrain_relief'] <= 1.2 for o in props)
    covered={entry for hub in d['hubs'] for entry in hub['contacts']}
    exceptions={int(entry) for entry in d['exceptions']}
    for n in [1,2,3]:
        chapter=json.loads((ROOT/f'data/quests/broken_seal_chapter{n}.json').read_text())
        public={a['entry'] for a in chapter['actors'] if a.get('point')}
        givers={chapter['ids'][q[k]] for q in chapter['quests'] for k in ['giver','turn_in']}
        assert givers & public <= covered | exceptions, ('Unregistered quest hub',givers & public - covered - exceptions)
    assert d['native_audit'].get('threats') is not None
    for r in d['relocations']:
        assert r['movement'] in [0, 1] and r['guid'] and r['entry']


def header(d):
    lines=['// Generated by tools/generate_broken_seal_hubs.py. Do not edit.',
           '#ifndef MOD_CUSTOMNPCS_BROKEN_SEAL_HUBS_DATA_H','#define MOD_CUSTOMNPCS_BROKEN_SEAL_HUBS_DATA_H',
           '', '#include <array>', '#include <cstdint>', '', 'namespace BrokenSeal::Hubs', '{',
           'struct Hub', '{', '    float x;', '    float y;', '    float z;', '    float radius;',
           '    float screen;', '    float height;', '    std::uint32_t chapter;', '    std::uint32_t guard;',
           '};', '', f'inline constexpr std::array<Hub, {len(d["hubs"])}> Areas =', '{{']
    for h in d['hubs']:
        values=h['center'][:3]+[h['radius'],h['screen_radius'],h['vertical_tolerance']]
        lines += ['    {'+', '.join(f'{v:.4f}f' for v in values)+f', {h.get("activation_chapter",h["chapter"])}, {h["guard_entry"]}'+'},']
    lines+=['}};', '', 'struct Footprint', '{', '    float left;', '    float bottom;',
            '    float right;', '    float top;', '    float z;', '    std::uint32_t area;', '};', '',
            f'inline constexpr std::array<Footprint, {len(d["objects"])}> Footprints =', '{{']
    indexes={h['key']:i for i,h in enumerate(d['hubs'])}
    for o in d['objects']:
        values=o['bounds']+[o['point'][2]]
        lines+=['    {'+', '.join(f'{v:.4f}f' for v in values)+f', {indexes[o["hub"]]}'+'},']
    lines+=['}};', '', 'inline constexpr std::array<std::uint32_t, 9> PublicQuestMobs =',
            '{', '    4001010, 4001011, 4001222, 4001225, 4001227, 4001228, 4001414, 4001415, 4001416',
            '};', '}', '', '#endif', '']
    return '\n'.join(lines)


def sql(d):
    actors=d['guards']+d['residents']
    owned=[('creature',a['entry']) for a in actors]+[('gameobject',o['entry']) for o in d['objects']]
    owned += [(kind,a['entry']) for kind in ['outfit','outfit_entry'] for a in actors]
    text='''-- The Broken Seal: quest hub safety and camp dressing, Chapters 1-3.
-- Generated from data/quests/broken_seal_hubs.json. Requires all three chapters and rebuilt module.
-- Occupied-ID checks precede content DML. Ordinary stock spawn moves are backed up and conditional.
-- No native spawn is deleted, no shared path or stock creature template is modified.
-- See docs/broken-seal/hub-implementation.md.
CREATE TABLE IF NOT EXISTS `mod_customnpcs_bs_content` (
  `kind` VARCHAR(16) NOT NULL, `entry` INT UNSIGNED NOT NULL, `chapter` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`kind`,`entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TEMPORARY TABLE IF EXISTS `bs_hub_ids`;
CREATE TEMPORARY TABLE `bs_hub_ids` (`kind` VARCHAR(16), `entry` INT UNSIGNED, PRIMARY KEY (`kind`,`entry`))
  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
'''
    text+=rows('bs_hub_ids',['kind','entry'],owned)
    text+='''DROP TEMPORARY TABLE IF EXISTS `bs_hub_guard`;
CREATE TEMPORARY TABLE `bs_hub_guard` (`id` TINYINT PRIMARY KEY);
INSERT INTO `bs_hub_guard` VALUES (1);
INSERT INTO `bs_hub_guard` SELECT 1 WHERE
  (SELECT COUNT(*) FROM `mod_customnpcs_bs_content` WHERE `kind`='quest' AND
    ((`entry`=900108 AND `chapter`=1) OR (`entry`=900222 AND `chapter`=2) OR (`entry`=900311 AND `chapter`=3))) <> 3
  OR (SELECT COUNT(*) FROM `quest_template` WHERE `ID` IN (900108,900222,900311)) <> 3;
'''
    for kind,table,col in [('creature','creature_template','entry'),('gameobject','gameobject_template','entry'),
                           ('outfit','mod_customnpcs_outfit','outfit_id'),('outfit_entry','mod_customnpcs_outfit_entry','creature_entry')]:
        text+=f'''INSERT INTO `bs_hub_guard`
SELECT 1 FROM `{table}` t INNER JOIN `bs_hub_ids` h ON h.`kind`='{kind}' AND h.`entry`=t.`{col}`
LEFT JOIN `mod_customnpcs_bs_content` o ON o.`kind`=h.`kind` AND o.`entry`=h.`entry` AND o.`chapter`=0
WHERE o.`entry` IS NULL LIMIT 1;
'''
    text+='''DROP TEMPORARY TABLE `bs_hub_guard`;
CREATE TABLE IF NOT EXISTS `mod_customnpcs_bs_hub_native` (
  `guid` INT UNSIGNED PRIMARY KEY, `entry` INT UNSIGNED NOT NULL, `map` SMALLINT UNSIGNED NOT NULL,
  `x` FLOAT NOT NULL, `y` FLOAT NOT NULL, `z` FLOAT NOT NULL, `o` FLOAT NOT NULL,
  `applied_x` FLOAT NOT NULL, `applied_y` FLOAT NOT NULL, `applied_z` FLOAT NOT NULL, `applied_o` FLOAT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
START TRANSACTION;
INSERT INTO `mod_customnpcs_bs_content` (`kind`,`entry`,`chapter`)
SELECT `kind`,`entry`,0 FROM `bs_hub_ids` ON DUPLICATE KEY UPDATE `chapter`=VALUES(`chapter`);
'''
    cols=['entry','name','minlevel','maxlevel','faction','npcflag','unit_class','unit_flags','type','AIName',
          'ScriptName','HealthModifier','DamageModifier','ExperienceModifier','lootid','flags_extra']
    text+=upsert('creature_template',cols,
        [[a['entry'],a['name'],45,45,250 if a in d['guards'] else 35,0,1,770,7,'',
          'npc_bs_hub_sentry' if a in d['guards'] else 'npc_bs_hub_resident',5,1,0,0,2] for a in actors],['entry'])
    ids=', '.join(str(a['entry']) for a in actors)
    text+=f'DELETE FROM `creature_template_model` WHERE `CreatureID` IN ({ids});\n'
    text+=rows('creature_template_model',['CreatureID','Idx','CreatureDisplayID','DisplayScale','Probability'],
               [[a['entry'],0,a['display'],1,1] for a in actors])
    outfit=['outfit_id','race','gender','class','skin','face','hair','hair_color','facial_hair','chest','legs','feet','hands','mainhand']
    text+=upsert('mod_customnpcs_outfit',outfit,[[a['entry']]+[a['outfit'].get(k,1 if k == 'class' else 0) for k in outfit[1:]] for a in actors],['outfit_id'])
    text+=upsert('mod_customnpcs_outfit_entry',['creature_entry','outfit_id'],[[a['entry'],a['entry']] for a in actors],['creature_entry'])
    text+=f'DELETE FROM `creature_template_addon` WHERE `entry` IN ({ids});\n'
    text+=rows('creature_template_addon',['entry','emote'],[[a['entry'],a['emote']] for a in d['residents']])
    text+=upsert('gameobject_template',['entry','type','displayId','name','size'],
                [[o['entry'],5,o['display'],o['name'],o['scale']] for o in d['objects']],['entry'])
    for kind in ['creature','gameobject']:
        text+=f'DROP TEMPORARY TABLE IF EXISTS `bs_hub_{kind}_spawns`;\n'
        text+=f'CREATE TEMPORARY TABLE `bs_hub_{kind}_spawns` (`spawn_key` VARCHAR(100) PRIMARY KEY, `entry` INT UNSIGNED, `zone` INT UNSIGNED, `x` FLOAT, `y` FLOAT, `z` FLOAT, `o` FLOAT) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n'
    hubmap={h['key']:h for h in d['hubs']}
    spawns=[]
    for a in actors:
        for n,p in enumerate(a.get('points') or [a['point']]):
            spawns.append([f'BS-HUB:{a["entry"]}:{n}',a['entry'],15 if hubmap[a['hub']]['chapter']==3 else 406,*p])
    text+=rows('bs_hub_creature_spawns',['spawn_key','entry','zone','x','y','z','o'],spawns)
    text+=rows('bs_hub_gameobject_spawns',['spawn_key','entry','zone','x','y','z','o'],
                [[f'BS-HUB:{o["key"]}',o['entry'],15 if hubmap[o['hub']]['chapter']==3 else 406,*o['point']] for o in d['objects']])
    # Use the already-tested native/legacy GUID-preserving spawn implementation.
    source=chapter_sql(json.loads((ROOT/'data/quests/broken_seal_chapter3.json').read_text()))
    part=source[source.index('SET @BS_C03_ENTRY_COLUMN'):source.index('DROP TEMPORARY TABLE `bs_c03_creature_spawns`')]
    part=part.replace('BS_C03','BS_HUB').replace('bs_c03','bs_hub');text+=part
    text+='''DROP TEMPORARY TABLE IF EXISTS `bs_hub_native_moves`;
CREATE TEMPORARY TABLE `bs_hub_native_moves` (`guid` INT UNSIGNED PRIMARY KEY, `entry` INT UNSIGNED,
  `ox` FLOAT, `oy` FLOAT, `oz` FLOAT, `oo` FLOAT, `nx` FLOAT, `ny` FLOAT, `nz` FLOAT, `no` FLOAT);
'''
    if d['relocations']:
        text+=rows('bs_hub_native_moves',['guid','entry','ox','oy','oz','oo','nx','ny','nz','no'],
                    [[r['guid'],r['entry'],*r['original'],*r['point']] for r in d['relocations']])
    text+='''-- Claim only the audited original spawn: changed realm placements are left alone.
SET @BS_HUB_BACKUP := CONCAT(
 'INSERT IGNORE INTO `mod_customnpcs_bs_hub_native` (`guid`,`entry`,`map`,`x`,`y`,`z`,`o`,`applied_x`,`applied_y`,`applied_z`,`applied_o`) ',
 'SELECT c.`guid`,m.`entry`,c.`map`,c.`position_x`,c.`position_y`,c.`position_z`,c.`orientation`,m.`nx`,m.`ny`,m.`nz`,m.`no` ',
 'FROM `creature` c INNER JOIN `bs_hub_native_moves` m ON c.`guid`=m.`guid` INNER JOIN `creature_template` t ON t.`entry`=m.`entry` ',
 'WHERE c.`',@BS_HUB_ENTRY_COLUMN,'`=m.`entry` AND c.`map`=1 AND ',
 "t.`ScriptName`='' AND t.`rank`=0 AND t.`npcflag`=0 AND (c.`ScriptName`='' OR c.`ScriptName` IS NULL) AND c.`npcflag`=0 AND c.`MovementType` IN (0,1) AND ",
 'ABS(c.`position_x`-m.`ox`)<0.1 AND ABS(c.`position_y`-m.`oy`)<0.1 AND ABS(c.`position_z`-m.`oz`)<0.1'
);
PREPARE bs_hub_stmt FROM @BS_HUB_BACKUP;
EXECUTE bs_hub_stmt;
DEALLOCATE PREPARE bs_hub_stmt;
SET @BS_HUB_MOVE := CONCAT(
 'UPDATE `creature` c INNER JOIN `bs_hub_native_moves` m ON c.`guid`=m.`guid` ',
 'INNER JOIN `mod_customnpcs_bs_hub_native` b ON b.`guid`=c.`guid` AND b.`entry`=m.`entry` INNER JOIN `creature_template` t ON t.`entry`=m.`entry` ',
 'SET c.`position_x`=m.`nx`,c.`position_y`=m.`ny`,c.`position_z`=m.`nz`,c.`orientation`=m.`no` ',
 'WHERE c.`',@BS_HUB_ENTRY_COLUMN,'`=m.`entry` AND c.`map`=b.`map` AND ',
 "t.`ScriptName`='' AND t.`rank`=0 AND t.`npcflag`=0 AND (c.`ScriptName`='' OR c.`ScriptName` IS NULL) AND c.`npcflag`=0 AND c.`MovementType` IN (0,1) AND ",
 '((ABS(c.`position_x`-b.`x`)<0.1 AND ABS(c.`position_y`-b.`y`)<0.1 AND ABS(c.`position_z`-b.`z`)<0.1) OR ',
 '(ABS(c.`position_x`-b.`applied_x`)<0.1 AND ABS(c.`position_y`-b.`applied_y`)<0.1 AND ABS(c.`position_z`-b.`applied_z`)<0.1))'
);
PREPARE bs_hub_stmt FROM @BS_HUB_MOVE;
EXECUTE bs_hub_stmt;
DEALLOCATE PREPARE bs_hub_stmt;
'''
    # Older installed chapter files get the same safe positions without replacing GUIDs or template behavior.
    for m in d['chapter_moves']:
        p=m['new']
        if m['kind']=='creature':
            text+=f"UPDATE `creature` SET `position_x`={p[0]},`position_y`={p[1]},`position_z`={p[2]},`orientation`={p[3]} WHERE `Comment`='{m['spawn_key']}';\n"
        else:
            text+=f"UPDATE `gameobject` SET `position_x`={p[0]},`position_y`={p[1]},`position_z`={p[2]},`orientation`={p[3]},`rotation2`=SIN({p[3]}/2),`rotation3`=COS({p[3]}/2) WHERE `Comment`='{m['spawn_key']}';\n"
    text+='''DROP TEMPORARY TABLE `bs_hub_creature_spawns`;
DROP TEMPORARY TABLE `bs_hub_gameobject_spawns`;
DROP TEMPORARY TABLE `bs_hub_native_moves`;
DROP TEMPORARY TABLE `bs_hub_ids`;
COMMIT;
'''
    return text


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    d=json.loads(MANIFEST.read_text());validate(d);content=sql(d)
    for path,value in [(BASE,content),(UPDATE,content),(HEADER,header(d))]:
        if args.check:assert path.is_file() and path.read_text()==value, f'Stale {path}'
        else:path.write_text(value)
    print(f"Hubs: {len(d['hubs'])} protected areas, {len(d['objects'])} scenery placements, {len(d['relocations'])} conditional native clearances.")


if __name__=='__main__':main()
