#!/usr/bin/env python3
"""Generate the Chapter 2 SQL and runtime inventory from one implementation manifest."""
import argparse
import json
import math
from pathlib import Path
from generate_broken_seal_chapter1 import rows, upsert

from broken_seal_outfits import validate_outfits
from broken_seal_content import equipment_sql, ordinary_loot_sql, quest_poi_rows, validate_quest_polish

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'data/quests/broken_seal_chapter2.json'
BASE = ROOT / 'data/sql/db-world/base/broken_seal_chapter2.sql'
UPDATE = ROOT / 'data/sql/db-world/updates/2026_10_06_01_broken_seal_chapter2.sql'
HEADER = ROOT / 'src/BrokenSealChapter2Data.h'


def validate(d):
    validate_quest_polish(d)
    validate_outfits(d['actors'])
    ids = d['ids']
    assert d['chapter'] == 'C02' and len(d['quests']) == 23
    for prefix in ('QUEST_', 'GO_', 'ITEM_'):
        values = [v for k, v in ids.items() if k.startswith(prefix)]
        assert len(values) == len(set(values)), prefix
    creatures = [v for k, v in ids.items() if k.startswith(('NPC_', 'CREDIT_'))]
    assert len(creatures) == len(set(creatures))
    for p in d['points'].values():
        assert len(p) == 4 and all(math.isfinite(v) for v in p)
    for q in d['quests']:
        assert q['id'] == ids[q['key']] and q['description'] and q['completion']
        assert len(q['credits']) <= 4 and len(q['required_items']) <= 6
        assert len(q['reward_choices']) <= 6
        assert q['previous'] == q['prerequisites'][0]
    assert d['quests'][-1]['reward_choices'] and not d['quests'][-1].get('next_quest')
    # The core's negative exclusive groups enforce ALL joins in both visibility and acceptance.
    by_key = {q['key']: q for q in d['quests']}
    for q in d['quests']:
        if len(q['prerequisites']) > 1:
            groups = {by_key[k]['exclusive_group'] for k in q['prerequisites']}
            assert len(groups) == 1 and next(iter(groups)) < 0
            assert {v['key'] for v in d['quests'] if v.get('exclusive_group') in groups} == set(q['prerequisites'])


def header(d):
    lines = ['// Generated by tools/generate_broken_seal_chapter2.py. Do not edit.',
             '#ifndef MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER2_DATA_H',
             '#define MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER2_DATA_H', '',
             '#include <array>', '#include <cstdint>', '', 'namespace BrokenSeal::Chapter2', '{',
             'enum Id : std::uint32_t', '{']
    lines += [f'    {k} = {v},' for k, v in d['ids'].items()]
    lines += ['};', '', f'inline constexpr std::uint32_t FireDisplay = {d["native_assets"]["fire_form"]["display"]};', '', 'struct Point', '{', '    float x;', '    float y;', '    float z;',
              '    float orientation;', '};', '', 'namespace Locations', '{']
    for key, p in d['points'].items():
        lines += [f'inline constexpr Point {key} = {{' + ', '.join(f'{v:.4f}f' for v in p) + '};']
    lines += ['}', '']
    for name, keys in d['routes'].items():
        lines += [f'inline constexpr std::array<Point, {len(keys)}> {name} =',
                  '{', '    ' + ', '.join('Locations::' + k for k in keys), '};', '']
    lines += ['struct QuestSupply', '{', '    std::uint32_t quest;',
              '    std::array<std::uint32_t, 2> items;', '};', '',
              'inline constexpr std::array<QuestSupply, 9> Supplies =', '{{']
    for q in d['quests']:
        if q['recovery_items']:
            keys = q['recovery_items'] + ['0'] * (2 - len(q['recovery_items']))
            lines += ['    {' + q['key'] + ', {' + ', '.join(keys) + '}},']
    lines += ['}};', '', 'inline constexpr std::array<std::uint32_t, 23> Quests =', '{',
              '    ' + ', '.join(q['key'] for q in d['quests']), '};',
              'inline constexpr std::array<std::uint32_t, 22> PersonalEntries =', '{',
              '    ' + ', '.join(a['key'] for a in d['actors'] if not a.get('point') and not a.get('points')), '};',
              '}', '', '#endif', '']
    # Infer lengths rather than leave silently padded entries in a cleanup inventory.
    lines = [l.replace('array<std::uint32_t, 22> PersonalEntries',
                       f'array<std::uint32_t, {sum(not a.get("point") and not a.get("points") for a in d["actors"])}> PersonalEntries') for l in lines]
    return '\n'.join(lines)


def sql(d):
    ids = d['ids']
    owned = [('creature', a['entry']) for a in d['actors']]
    owned += [('creature', v) for k, v in ids.items() if k.startswith('CREDIT_')]
    owned += [('gameobject', o['entry']) for o in d['objects']]
    owned += [('quest', q['id']) for q in d['quests']] + [('item', i['entry']) for i in d['items']]
    owned += [(kind, a['entry']) for kind in ('outfit', 'outfit_entry') for a in d['actors'] if a.get('outfit')]
    owned += [(kind, a['entry']) for kind in ('npc_text', 'gossip_menu') for a in d['actors'] if a['npc_flags']]
    owned += [(kind, ids['NPC_PRISONER']) for kind in ('npc_text', 'gossip_menu')]
    text = '''-- The Broken Seal, Chapter 2: Inside the Twilight (levels 25-30).
-- Generated from data/quests/broken_seal_chapter2.json. Native 3.3.5a assets only.
-- Requires Chapter 1, custom_npc_appearances.sql and the rebuilt module.
-- Reapplication preserves GUIDs. Occupied IDs and missing Chapter 1 reject before content DML.
-- See docs/broken-seal/chapter2-implementation.md.
CREATE TABLE IF NOT EXISTS `mod_customnpcs_bs_content` (
  `kind` VARCHAR(16) NOT NULL,
  `entry` INT UNSIGNED NOT NULL,
  `chapter` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`kind`, `entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TEMPORARY TABLE IF EXISTS `bs_c02_ids`;
CREATE TEMPORARY TABLE `bs_c02_ids` (
  `kind` VARCHAR(16) NOT NULL, `entry` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`kind`, `entry`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
'''
    text += rows('bs_c02_ids', ['kind', 'entry'], owned)
    text += '''DROP TEMPORARY TABLE IF EXISTS `bs_c02_collision_guard`;
CREATE TEMPORARY TABLE `bs_c02_collision_guard` (`id` TINYINT PRIMARY KEY);
INSERT INTO `bs_c02_collision_guard` VALUES (1);
-- Intentional duplicate-key error if the shared Chapter 1 entries are absent or unowned.
INSERT INTO `bs_c02_collision_guard`
SELECT 1 WHERE (SELECT COUNT(*) FROM `mod_customnpcs_bs_content`
  WHERE `chapter` = 1 AND ((`kind` = 'creature' AND `entry` IN (4001001, 4001002))
  OR (`kind` = 'quest' AND `entry` = 900108))) <> 3
  OR NOT EXISTS (SELECT 1 FROM `quest_template` WHERE `ID` = 900108)
  OR (SELECT COUNT(*) FROM `creature_template` WHERE `entry` IN (4001001, 4001002)) <> 2;
'''
    for kind, table, col in [('creature','creature_template','entry'),('gameobject','gameobject_template','entry'),
                            ('quest','quest_template','ID'),('item','item_template','entry'),
                            ('outfit','mod_customnpcs_outfit','outfit_id'),('outfit_entry','mod_customnpcs_outfit_entry','creature_entry'),
                            ('npc_text','npc_text','ID'),
                            ('gossip_menu','gossip_menu','MenuID')]:
        text += f'''INSERT INTO `bs_c02_collision_guard`
SELECT 1 FROM `{table}` t INNER JOIN `bs_c02_ids` r ON r.`kind` = '{kind}' AND r.`entry` = t.`{col}`
LEFT JOIN `mod_customnpcs_bs_content` o ON o.`kind` = r.`kind` AND o.`entry` = r.`entry` AND o.`chapter` = 2
WHERE o.`entry` IS NULL LIMIT 1;
'''
    text += '''DROP TEMPORARY TABLE `bs_c02_collision_guard`;
START TRANSACTION;
INSERT INTO `mod_customnpcs_bs_content` (`kind`, `entry`, `chapter`)
SELECT `kind`, `entry`, 2 FROM `bs_c02_ids` ON DUPLICATE KEY UPDATE `chapter` = VALUES(`chapter`);
'''
    cols = ['entry','name','minlevel','maxlevel','exp','faction','npcflag','unit_class','unit_flags','type',
            'AIName','ScriptName','HealthModifier','DamageModifier','ExperienceModifier','lootid','flags_extra']
    values = [[a['entry'],a['name'],a['level'],a['level'],0,a['faction'],a['npc_flags'],1,a['flags'],a['type'],'',
               a['script'],1.3 if a['key'] in ['NPC_GARNOTH','NPC_GROMMKO','NPC_OKROG'] else 1,1,
               a['experience_multiplier'],a['entry'] if a['key']=='NPC_MATRIARCH' or a.get('ordinary_loot') else 0,
               2 if a['faction']==35 else 0] for a in d['actors']]
    values += [[v,k.replace('CREDIT_','').replace('_',' ').title(),1,1,0,35,0,1,33555202,10,
                'NullCreatureAI','',1,1,0,0,2] for k,v in ids.items() if k.startswith('CREDIT_')]
    text += upsert('creature_template',cols,values,['entry'])
    creature_ids = ', '.join(str(v) for k,v in owned if k=='creature')
    text += f'DELETE FROM `creature_template_model` WHERE `CreatureID` IN ({creature_ids});\n'
    text += rows('creature_template_model',['CreatureID','Idx','CreatureDisplayID','DisplayScale','Probability'],
                 [[a['entry'],0,a['display'],a.get('scale',1),1] for a in d['actors']] + [[v,0,11686,1,1] for k,v in ids.items() if k.startswith('CREDIT_')])
    ocols=['outfit_id','race','gender','class','skin','face','hair','hair_color','facial_hair','chest','shoulders',
           'shirt','waist','legs','feet','hands','mainhand','ranged']
    dressed=[a for a in d['actors'] if a.get('outfit')]
    text += upsert('mod_customnpcs_outfit',ocols,[[a['entry']]+[a['outfit'].get(c,1 if c == 'class' else 0) for c in ocols[1:]] for a in dressed],['outfit_id'])
    text += upsert('mod_customnpcs_outfit_entry',['creature_entry','outfit_id'],[[a['entry'],0 if a.get('native_appearance') else a['entry']] for a in dressed],['creature_entry'])
    text += equipment_sql(d['actors'])
    icols=['entry','class','subclass','name','displayid','Quality','InventoryType','AllowableClass','AllowableRace',
           'ItemLevel','RequiredLevel','maxcount','stackable','bonding','stat_type1','stat_value1','stat_type2',
           'stat_value2','stat_type3','stat_value3','description','spellid_1','spelltrigger_1','ScriptName']
    iv=[]
    for item in d['items']:
        eq=item.get('equipment',False);stats=item.get('stats',[])+[[0,0]]*3
        iv.append([item['entry'],4 if eq else 12,0,item['name'],item['display'],2 if eq else 1,11 if eq else 0,-1,-1,
                   item.get('level',1),item.get('required_level',0),item.get('maxcount',1),item.get('stackable',1),
                   1 if eq else 4,*stats[0],*stats[1],*stats[2],item['description'],
                   ids[item['spell']] if item.get('spell') else 0,0,item.get('script','')])
    text += upsert('item_template',icols,iv,['entry'])
    text += f'DELETE FROM `creature_loot_template` WHERE `Entry` = {ids["NPC_MATRIARCH"]};\n'
    text += ordinary_loot_sql(d['actors'])
    text += rows('creature_loot_template',['Entry','Item','Chance','QuestRequired','LootMode','GroupId','MinCount','MaxCount'],
                 [[ids['NPC_MATRIARCH'],ids['ITEM_HIDE'],100,1,1,0,1,1]])
    qcols=['ID','QuestType','QuestLevel','MinLevel','QuestSortID','RewardXPDifficulty','RewardMoney','StartItem',
           'Flags','AllowableRaces','LogTitle','LogDescription','QuestDescription','QuestCompletionLog']
    for stem,n in [('RequiredNpcOrGo',4),('RequiredNpcOrGoCount',4),('ObjectiveText',4),('RequiredItemId',6),
                   ('RequiredItemCount',6),('RewardChoiceItemID',6),('RewardChoiceItemQuantity',6)]:
        qcols += [stem+str(i) for i in range(1,n+1)]
    qr=[];addons=[]
    for q in d['quests']:
        cr=list(q['credits'].items());req=list(q['required_items'].items());rewards=q['reward_choices']
        qr.append([q['id'],2,q['level'],25,406,q['xp_difficulty'],q['money'],ids[q['source_item']] if q['source_item'] else 0,
                   0,0,q['title'],q['objectives'],q['description'],q['return_text'],
                   *([ids[k] for k,v in cr]+[0]*(4-len(cr))),*([v for k,v in cr]+[0]*(4-len(cr))),
                   *([q['objective_labels'][k] for k,v in cr]+['']*(4-len(cr))),
                   *([ids[k] for k,v in req]+[0]*(6-len(req))),*([v for k,v in req]+[0]*(6-len(req))),
                   *([ids[k] for k in rewards]+[0]*(6-len(rewards))),*([1]*len(rewards)+[0]*(6-len(rewards)))])
        addons.append([q['id'],ids[q['previous']],0,q.get('exclusive_group',0),1 if q['source_item'] else 0,256])
    text += upsert('quest_template',qcols,qr,['ID'])
    text += upsert('quest_template_addon',['ID','PrevQuestID','NextQuestID','ExclusiveGroup','ProvidedItemCount','SpecialFlags'],addons,['ID'])
    qids=', '.join(str(q['id']) for q in d['quests'])
    for table in ('creature_queststarter','creature_questender'):
        text += f'DELETE FROM `{table}` WHERE `quest` IN ({qids});\n'
        field='giver' if table.endswith('starter') else 'turn_in'
        text += rows(table,['id','quest'],[[ids[q[field]],q['id']] for q in d['quests']])
    text += upsert('quest_offer_reward',['ID','RewardText'],[[q['id'],q['completion']] for q in d['quests']],['ID'])
    text += upsert('quest_request_items',['ID','CompletionText'],[[q['id'],q['request_text']] for q in d['quests']],['ID'])
    text += f'DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 19 AND `SourceEntry` IN ({qids});\n'
    text += rows('conditions',['SourceTypeOrReferenceId','SourceEntry','ElseGroup','ConditionTypeOrReference','ConditionValue1','Comment'],
                 [[19,q['id'],0,8,ids[k],'Broken Seal C02: every listed predecessor must be rewarded'] for q in d['quests'] for k in q['prerequisites']])
    for table in ('quest_poi_points','quest_poi'):
        text += f'DELETE FROM `{table}` WHERE `QuestID` IN ({qids});\n'
    actor_points={a['key']:a['point'] for a in d['actors'] if a['point']}
    actor_points.update(NPC_ORTELL='ortell',NPC_PRISONER='prison',NPC_JAROD_FREE='refuge')
    poi,pp = quest_poi_rows(d, actor_points)
    text += rows('quest_poi',['QuestID','id','ObjectiveIndex','MapID','WorldMapAreaId','Floor','Priority','Flags'],poi)
    text += rows('quest_poi_points',['QuestID','Idx1','Idx2','X','Y'],pp)
    talkers=[a for a in d['actors'] if a['npc_flags']]
    talkers += [dict(entry=ids['NPC_PRISONER'], greeting='Keep your voice down. My chains have a guard, and the crowd has a memory.')]
    text += upsert('npc_text',['ID','text0_0','Probability0'],[[a['entry'],a.get('greeting', 'Speak quietly. Every trial is watched.'),1] for a in talkers],['ID'])
    menus=', '.join(str(a['entry']) for a in talkers)
    text += f'DELETE FROM `gossip_menu` WHERE `MenuID` IN ({menus});\n'
    text += rows('gossip_menu',['MenuID','TextID'],[[a['entry'],a['entry']] for a in talkers])
    text += f'UPDATE `creature_template` SET `gossip_menu_id` = `entry` WHERE `entry` IN ({menus});\n'
    text += upsert('gameobject_template',['entry','type','displayId','name','size','Data3','Data5','Data18','ScriptName'],
                   [[o['entry'],5 if o.get('decorative') else 10,o['display'],o['name'],o['scale'],0,0,1,'' if o.get('decorative') else 'go_bs_c02_interaction'] for o in d['objects']],['entry'])
    for kind in ('creature','gameobject'):
        text += f'DROP TEMPORARY TABLE IF EXISTS `bs_c02_{kind}_spawns`;\n'
        text += f'CREATE TEMPORARY TABLE `bs_c02_{kind}_spawns` (`spawn_key` VARCHAR(100) PRIMARY KEY, `entry` INT UNSIGNED, `zone` INT UNSIGNED, `x` FLOAT, `y` FLOAT, `z` FLOAT, `o` FLOAT) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n'
    sp=[]
    for a in d['actors']:
        for p in a.get('points',[]) or ([a['point']] if a['point'] else []):
            sp.append([f'BS-C02:{a["key"]}:{p}',a['entry'],a.get('zone',406),*d['points'][p]])
    text += rows('bs_c02_creature_spawns',['spawn_key','entry','zone','x','y','z','o'],sp)
    text += rows('bs_c02_gameobject_spawns',['spawn_key','entry','zone','x','y','z','o'],
                 [[f'BS-C02:{o["key"]}:{p}',o['entry'],406,*d['points'][p]] for o in d['objects'] for p in o['points']])
    text += '''SET @BS_C02_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature' AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
SET @BS_C02_INSERT := CONCAT(
  'INSERT INTO `creature` (`', @BS_C02_ENTRY_COLUMN, '`, `map`, `zoneId`, `spawnMask`, `phaseMask`, ',
  '`position_x`, `position_y`, `position_z`, `orientation`, `equipment_id`, `spawntimesecs`, `curhealth`, `curmana`, `Comment`) ',
  'SELECT s.`entry`, 1, s.`zone`, 1, 1, s.`x`, s.`y`, s.`z`, s.`o`, -1, 60, 0, 0, s.`spawn_key` ',
  'FROM `bs_c02_creature_spawns` s LEFT JOIN `creature` c ON c.`Comment` = s.`spawn_key` WHERE c.`guid` IS NULL'
);
PREPARE bs_c02_stmt FROM @BS_C02_INSERT;
EXECUTE bs_c02_stmt;
DEALLOCATE PREPARE bs_c02_stmt;
SET @BS_C02_UPDATE := CONCAT(
  'UPDATE `creature` c INNER JOIN `bs_c02_creature_spawns` s ON c.`Comment` = s.`spawn_key` ',
  'SET c.`', @BS_C02_ENTRY_COLUMN, '` = s.`entry`, c.`zoneId` = s.`zone`, c.`position_x` = s.`x`, ',
  'c.`position_y` = s.`y`, c.`position_z` = s.`z`, c.`orientation` = s.`o`, c.`equipment_id` = -1'
);
PREPARE bs_c02_stmt FROM @BS_C02_UPDATE;
EXECUTE bs_c02_stmt;
DEALLOCATE PREPARE bs_c02_stmt;
INSERT INTO `gameobject`
  (`id`, `map`, `zoneId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`,
   `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `Comment`)
SELECT s.`entry`, 1, s.`zone`, 1, 1, s.`x`, s.`y`, s.`z`, s.`o`, SIN(s.`o` / 2), COS(s.`o` / 2), 60, 100, 1, s.`spawn_key`
FROM `bs_c02_gameobject_spawns` s LEFT JOIN `gameobject` g ON g.`Comment` = s.`spawn_key` WHERE g.`guid` IS NULL;
UPDATE `gameobject` g INNER JOIN `bs_c02_gameobject_spawns` s ON g.`Comment` = s.`spawn_key`
SET g.`id` = s.`entry`, g.`position_x` = s.`x`, g.`position_y` = s.`y`, g.`position_z` = s.`z`, g.`orientation` = s.`o`,
  g.`rotation2` = SIN(s.`o` / 2), g.`rotation3` = COS(s.`o` / 2);
-- Retire obsolete owned campaign placements; surviving spawn keys keep their GUIDs.
SET @BS_C02_PRUNE := CONCAT(
  'DELETE c FROM `creature` c LEFT JOIN `bs_c02_creature_spawns` s ON s.`spawn_key`=c.`Comment` ',
  'INNER JOIN `mod_customnpcs_bs_content` owner ON owner.`kind`=\\'creature\\' AND owner.`entry`=c.`',@BS_C02_ENTRY_COLUMN,'` AND owner.`chapter`=2 ',
  'WHERE c.`Comment` LIKE \\'BS-C02:%\\' AND s.`spawn_key` IS NULL'
);
PREPARE bs_c02_stmt FROM @BS_C02_PRUNE;
EXECUTE bs_c02_stmt;
DEALLOCATE PREPARE bs_c02_stmt;
DELETE g FROM `gameobject` g LEFT JOIN `bs_c02_gameobject_spawns` s ON s.`spawn_key`=g.`Comment`
INNER JOIN `mod_customnpcs_bs_content` owner ON owner.`kind`='gameobject' AND owner.`entry`=g.`id` AND owner.`chapter`=2
WHERE g.`Comment` LIKE 'BS-C02:%' AND s.`spawn_key` IS NULL;
DROP TEMPORARY TABLE `bs_c02_creature_spawns`;
DROP TEMPORARY TABLE `bs_c02_gameobject_spawns`;
DROP TEMPORARY TABLE `bs_c02_ids`;
-- Upgrade older Chapter 1 installs without replacing their SmartAI combat rows or template stats.
UPDATE `creature_template` c INNER JOIN `mod_customnpcs_bs_content` o
  ON o.`kind` = 'creature' AND o.`entry` = c.`entry` AND o.`chapter` = 1
SET c.`AIName` = '', c.`ScriptName` = 'npc_bs_c01_cult'
WHERE c.`entry` IN (4001010, 4001011);
COMMIT;
'''
    return text


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args();d=json.loads(MANIFEST.read_text());validate(d)
    content=sql(d)
    for path,value in [(BASE,content),(UPDATE,content),(HEADER,header(d))]:
        if args.check:
            assert path.is_file() and path.read_text()==value, f'Stale generated file: {path}'
        else:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_text(value)
    print('Chapter 2: validated 23 quests and generated matching SQL and runtime inventory.')


if __name__=='__main__':
    main()
