#!/usr/bin/env python3
"""Generate native city-guard gossip directions for the additional trainer rosters."""

import argparse
import json
import math
from pathlib import Path

from generate_city_trainers import quoted

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "data/sql/db-world/base/city_guard_trainers.sql"
UPDATE = ROOT / "data/sql/db-world/updates/2026_10_06_02_city_guard_trainers.sql"

# Native build-12340 city-guard root, class and profession menus. All guards
# sharing these menus receive the additions, including city patrollers.
CITIES = (
    ("orgrimmar", "Orgrimmar", 1951, 1949, 1942),
    ("stormwind", "Stormwind", 435, 401, 421),
    ("ironforge", "Ironforge", 2121, 2144, 2168),
    ("darnassus", "Darnassus", 2352, 2343, 2351),
    ("thunder_bluff", "Thunder Bluff", 721, 740, 751),
    ("undercity", "Undercity", 2849, 2848, 2847),
)
CLASS_SERVICES = {
    1: "Warrior", 3: "Paladin", 7: "Hunter", 9: "Rogue", 11: "Priest",
    14: "Shaman", 16: "Mage", 31: "Warlock", 33: "Druid",
}
PROFESSION_SERVICES = {
    59: "Blacksmithing", 60: "Blacksmithing", 69: "Herbalism", 74: "Tailoring",
    77: "Cooking", 78: "Mining", 80: "Mining", 81: "First Aid", 83: "First Aid",
    89: "Engineering", 92: "Engineering", 98: "Fishing", 100: "Skinning",
    111: "Jewelcrafting", 112: "Jewelcrafting", 121: "Inscription",
}
OTHER_SERVICES = {36: "Flying", 37: "Riding", 125: "Pet training"}
# Separate from the trainers' own gossip menus (some also offer supplies).
# Each ID is stable if a roster is reordered or an NPC is removed.
DIRECTION_OFFSET = 100000


def location_hint(slug, service):
    if slug == "thunder_bluff":
        return {
            "Paladin": "Look on Hunter Rise.",
            "Priest": "Look on Elder Rise.",
            "Shaman": "Look on the Spirit Rise platform.",
            "Warlock": "Look below Spirit Rise, beneath the shaman platform.",
            "Engineering": "Look on the main bluff.",
            "Jewelcrafting": "Look on the main bluff.",
        }[service]
    if slug == "undercity":
        return "The trainer is inside the underground city."
    return ""


def directions(rosters):
    result = []
    entries, slots = set(), set()
    for slug, city, root_menu, class_menu, profession_menu in CITIES:
        for npc in rosters[slug]["npcs"]:
            entry, trainer = npc["entry"], npc["trainer_id"]
            if trainer in CLASS_SERVICES:
                service, menu = CLASS_SERVICES[trainer], class_menu
            elif trainer in PROFESSION_SERVICES:
                service, menu = PROFESSION_SERVICES[trainer], profession_menu
            elif trainer in OTHER_SERVICES:
                service, menu = OTHER_SERVICES[trainer], root_menu
            else:
                raise ValueError(f"Unknown training service for {npc['name']}: {trainer}")
            # The original menus use low option IDs. Keep additions in stable
            # slots and reject occupied slots in SQL before changing any data.
            option = 100 + entry % 100
            if entry in entries or (menu, option) in slots:
                raise ValueError("Duplicate trainer or city-guard option")
            if not 4000005 <= entry <= 4000599:
                raise ValueError("Trainer entry is outside the reserved capital rosters")
            if len(npc["position"]) != 4 or not all(math.isfinite(v) for v in npc["position"]):
                raise ValueError(f"Invalid trainer position: {npc['name']}")
            entries.add(entry)
            slots.add((menu, option))
            training = "hunter pet" if service == "Pet training" else service
            text = f"Speak to {npc['name']} for {training} training. I've marked the location on your map."
            hint = location_hint(slug, service)
            if hint:
                text += " " + hint
            result.append({"entry": entry, "city": city, "menu": menu, "option": option,
                           "root_menu": root_menu, "id": entry + DIRECTION_OFFSET,
                           "label": f"{service}: {npc['name']}", "text": text,
                           "position": npc["position"][:2]})
    return result


def load_rosters():
    return {slug: json.loads((ROOT / f"data/npcs/{slug}_trainers.json").read_text())
            for slug, *_ in CITIES}


def generate(rosters):
    data = directions(rosters)
    sql = """-- mod-customNPCs: city guards know the additional capital trainers.
-- Generated by tools/generate_city_guard_trainers.py from data/npcs/*_trainers.json.
-- Apply after all six capital trainer rosters and their appearance/placement SQL.
-- Native gossip and POI packets work on an unmodified 3.3.5a client.
-- patch-F.MPQ is for flight maps; no client archive change is needed here.
-- Does not replace stock directions, guard AI, factions, or trainer services.
-- Direction menu/text/POI IDs: 4100005-4100599; native option slots: 100-199.
-- Reapply after changing roster positions; restart worldserver to reload gossip/POIs.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_guard_directions`;
CREATE TEMPORARY TABLE `mod_customnpcs_guard_directions` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `menu` INT UNSIGNED NOT NULL,
  `option` SMALLINT UNSIGNED NOT NULL,
  `root_menu` INT UNSIGNED NOT NULL,
  `direction_id` INT UNSIGNED NOT NULL UNIQUE,
  `label` VARCHAR(200) NOT NULL,
  `text` TEXT NOT NULL,
  `x` FLOAT NOT NULL,
  `y` FLOAT NOT NULL,
  UNIQUE KEY (`menu`, `option`)
);
INSERT INTO `mod_customnpcs_guard_directions`
  (`entry`, `menu`, `option`, `root_menu`, `direction_id`, `label`, `text`, `x`, `y`) VALUES
"""
    rows = []
    for d in data:
        row = [str(d[k]) for k in ("entry", "menu", "option", "root_menu", "id")]
        row += [quoted(d["label"]), quoted(d["text"])]
        row += [str(v) for v in d["position"]]
        rows.append("  (" + ", ".join(row) + ")")
    sql += ",\n".join(rows) + ";\n"
    sql += """
-- Fail before touching persistent data if another addition owns one of these
-- native menu slots or if the required native city menus are absent.
DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_guard_check`;
CREATE TEMPORARY TABLE `mod_customnpcs_guard_check` (`id` TINYINT PRIMARY KEY);
INSERT INTO `mod_customnpcs_guard_check` VALUES (1);
INSERT INTO `mod_customnpcs_guard_check`
SELECT 1 FROM `gossip_menu_option` o
INNER JOIN `mod_customnpcs_guard_directions` d
  ON d.`menu` = o.`MenuID` AND d.`option` = o.`OptionID`
WHERE o.`ActionMenuID` <> d.`direction_id` OR o.`ActionPoiID` <> d.`direction_id`
LIMIT 1;
INSERT INTO `mod_customnpcs_guard_check`
SELECT 1 FROM `mod_customnpcs_guard_directions` d
WHERE NOT EXISTS (SELECT 1 FROM `gossip_menu` g WHERE g.`MenuID` = d.`menu`)
   OR NOT EXISTS (SELECT 1 FROM `gossip_menu` g WHERE g.`MenuID` = d.`root_menu`)
LIMIT 1;
-- The owned leaf menus must never refer to another module's text.
INSERT INTO `mod_customnpcs_guard_check`
SELECT 1 FROM `gossip_menu` g
INNER JOIN `mod_customnpcs_guard_directions` d ON d.`direction_id` = g.`MenuID`
WHERE g.`TextID` <> d.`direction_id`
LIMIT 1;
-- Guard against exceeding the client's 32-option gossip menu limit.
INSERT INTO `mod_customnpcs_guard_check`
SELECT 1 FROM (
  SELECT `MenuID`, `OptionID`, 0 AS `added` FROM `gossip_menu_option`
  UNION ALL
  SELECT `menu`, `option`, 1 FROM `mod_customnpcs_guard_directions`
) planned
GROUP BY `MenuID` HAVING MAX(`added`) = 1 AND COUNT(DISTINCT `OptionID`) > 32 LIMIT 1;
DROP TEMPORARY TABLE `mod_customnpcs_guard_check`;

START TRANSACTION;
INSERT INTO `points_of_interest` (`ID`, `PositionX`, `PositionY`, `Icon`, `Flags`, `Importance`, `Name`)
SELECT `direction_id`, `x`, `y`, 7, 99, 0, `label` FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE
  `PositionX` = VALUES(`PositionX`), `PositionY` = VALUES(`PositionY`),
  `Icon` = VALUES(`Icon`), `Flags` = VALUES(`Flags`),
  `Importance` = VALUES(`Importance`), `Name` = VALUES(`Name`);

INSERT INTO `npc_text` (`ID`, `text0_0`, `text0_1`, `BroadcastTextID0`, `Probability0`)
SELECT `direction_id`, `text`, `text`, 0, 1 FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE
  `text0_0` = VALUES(`text0_0`), `text0_1` = VALUES(`text0_1`),
  `BroadcastTextID0` = 0, `Probability0` = 1;

INSERT INTO `gossip_menu` (`MenuID`, `TextID`)
SELECT `direction_id`, `direction_id` FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE `TextID` = VALUES(`TextID`);

-- These are GOSSIP options even though the book icon identifies training.
-- Using OptionType 5 would incorrectly ask the guard to train the player.
INSERT INTO `gossip_menu_option`
  (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`,
   `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`)
SELECT `menu`, `option`, 3, `label`, 0, 1, 1, `direction_id`, `direction_id`
FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE
  `OptionIcon` = 3, `OptionText` = VALUES(`OptionText`), `OptionBroadcastTextID` = 0,
  `OptionType` = 1, `OptionNpcFlag` = 1,
  `ActionMenuID` = VALUES(`ActionMenuID`), `ActionPoiID` = VALUES(`ActionPoiID`);

-- Keep the direction dialogue open, with navigation back to the trainer list
-- or to the same guard's main services menu.
INSERT INTO `gossip_menu_option`
  (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`,
   `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`)
SELECT `direction_id`, 0, 0, 'Back to trainers.', 0, 1, 1, `menu`, 0
FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE
  `OptionIcon` = 0, `OptionText` = VALUES(`OptionText`), `OptionBroadcastTextID` = 0,
  `OptionType` = 1, `OptionNpcFlag` = 1,
  `ActionMenuID` = VALUES(`ActionMenuID`), `ActionPoiID` = 0;

INSERT INTO `gossip_menu_option`
  (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`,
   `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`)
SELECT `direction_id`, 1, 0, 'Other city services.', 0, 1, 1, `root_menu`, 0
FROM `mod_customnpcs_guard_directions`
ON DUPLICATE KEY UPDATE
  `OptionIcon` = 0, `OptionText` = VALUES(`OptionText`), `OptionBroadcastTextID` = 0,
  `OptionType` = 1, `OptionNpcFlag` = 1,
  `ActionMenuID` = VALUES(`ActionMenuID`), `ActionPoiID` = 0;
COMMIT;
DROP TEMPORARY TABLE `mod_customnpcs_guard_directions`;
"""
    return sql


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify installation/update SQL.")
    args = parser.parse_args()
    rosters = load_rosters()
    sql = generate(rosters)
    for path in (BASE, UPDATE):
        if args.check:
            if not path.exists() or path.read_text() != sql:
                raise SystemExit(f"Regenerate {path.relative_to(ROOT)}")
        else:
            path.write_text(sql)
    print(f"{'Verified' if args.check else 'Generated'} guard directions for "
          f"{len(directions(rosters))} trainers in {len(CITIES)} cities.")


if __name__ == "__main__":
    main()
