#!/usr/bin/env python3
"""Generate a narrow, repeatable outfit-only repair for installed campaign presets."""
import argparse
import json
from pathlib import Path
from generate_broken_seal_chapter1 import rows

ROOT=Path(__file__).resolve().parents[1]
OUTPUT=ROOT/'data/sql/db-world/updates/2026_10_07_00_broken_seal_outfit_corrections.sql'


def generate():
    repairs=json.loads((ROOT/'data/quests/broken_seal_legacy_outfits.json').read_text())['rows']
    text='''-- The Broken Seal: repair missing trousers and invalid rendering class defaults.
-- Generated by tools/generate_broken_seal_outfit_fix.py. Appearance only; no spawn/quest/stat changes.
-- Owned preset records only. Preserve valid custom classes, nonzero clothing and all spawn overrides.
-- After importing: .customnpc outfit reload
CREATE TABLE IF NOT EXISTS `mod_customnpcs_bs_content` (
  `kind` VARCHAR(16) NOT NULL, `entry` INT UNSIGNED NOT NULL, `chapter` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`kind`,`entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TEMPORARY TABLE IF EXISTS `bs_outfit_repairs`;
CREATE TEMPORARY TABLE `bs_outfit_repairs` (
  `id` INT UNSIGNED PRIMARY KEY, `race` TINYINT UNSIGNED, `gender` TINYINT UNSIGNED,
  `chest` INT, `legs` INT, `feet` INT
);
'''
    text+=rows('bs_outfit_repairs',['id','race','gender','chest','legs','feet'],
               repairs)
    text+='''START TRANSACTION;
UPDATE `mod_customnpcs_outfit` o
INNER JOIN `bs_outfit_repairs` r ON r.`id`=o.`outfit_id`
INNER JOIN `mod_customnpcs_bs_content` owner ON owner.`kind`='outfit' AND owner.`entry`=o.`outfit_id`
  AND owner.`chapter` IN (0,1,2,3)
SET o.`class`=1 WHERE o.`class`=0;
-- Fill empty clothing only when the record still has the preset's race/gender and chest.
UPDATE `mod_customnpcs_outfit` o
INNER JOIN `bs_outfit_repairs` r ON r.`id`=o.`outfit_id`
INNER JOIN `mod_customnpcs_bs_content` owner ON owner.`kind`='outfit' AND owner.`entry`=o.`outfit_id`
  AND owner.`chapter` IN (0,1,2,3)
SET o.`legs`=IF(o.`legs`=0,r.`legs`,o.`legs`), o.`feet`=IF(o.`feet`=0,r.`feet`,o.`feet`)
WHERE o.`race`=r.`race` AND o.`gender`=r.`gender` AND o.`chest`=r.`chest`;
COMMIT;
DROP TEMPORARY TABLE `bs_outfit_repairs`;
'''
    return text


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args();text=generate()
    if args.check:assert OUTPUT.read_text()==text,'Stale outfit repair SQL'
    else:OUTPUT.write_text(text)
    print('Outfit-only repair generated/checked for 56 owned campaign/hub presets.')


if __name__=='__main__':main()
