#!/usr/bin/env python3
"""Generate researched Stormwind trainer definitions, appearances and placements."""

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from generate_orgrimmar_appearances import generate as appearance_template, number, values

MANIFEST = ROOT / "data/npcs/stormwind_trainers.json"
OUTPUTS = (
    ROOT / "data/sql/db-world/base/stormwind_trainers.sql",
    ROOT / "data/sql/db-world/updates/2026_10_05_02_stormwind_trainers.sql",
)


def quoted(value):
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def generate(manifest):
    npcs = manifest["npcs"]
    sql = """-- mod-customNPCs: Cataclysm/MoP additions to Stormwind, converted to Wrath.
-- Generated by tools/generate_stormwind_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql. Includes new identities, native curricula,
-- checked appearances and map-0 placements. Does not alter existing stock NPCs.
-- Safe to reapply: existing spawn GUIDs and intentional spawn outfit overrides survive.
-- Restart worldserver after applying. See docs/stormwind-trainers.md.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_stormwind_roster`;
CREATE TEMPORARY TABLE `mod_customnpcs_stormwind_roster` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `subname` VARCHAR(100) NOT NULL,
  `gossip_menu_id` INT UNSIGNED NOT NULL,
  `npcflag` INT UNSIGNED NOT NULL,
  `unit_class` TINYINT UNSIGNED NOT NULL,
  `minlevel` TINYINT UNSIGNED NOT NULL,
  `maxlevel` TINYINT UNSIGNED NOT NULL,
  `trainer_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL
);
INSERT INTO `mod_customnpcs_stormwind_roster` VALUES
"""
    rows = []
    for npc in npcs:
        menu = npc["entry"] if npc["vendors"] else npc["gossip_menu_id"]
        row = [number(npc["entry"]), quoted(npc["name"]), quoted(npc["subname"]),
               *[number(value) for value in [menu, npc["npcflag"], npc["unit_class"], npc["minlevel"],
                                            npc["maxlevel"], npc["trainer_id"], *npc["position"]]]]
        rows.append("  (" + ", ".join(row) + ")")
    sql += ",\n".join(rows) + ";\n"
    sql += """
-- Neutral custom-realm faction, valid creature stat classes, matching original titles/services.
INSERT INTO `creature_template`
  (`entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`,
   `npcflag`, `unit_class`, `unit_flags`, `type`, `AIName`, `ScriptName`, `flags_extra`)
SELECT `entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, 2, 35,
  `npcflag`, `unit_class`, 2, 7, 'NullCreatureAI', '', 2
FROM `mod_customnpcs_stormwind_roster`
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`), `subname` = VALUES(`subname`),
  `gossip_menu_id` = VALUES(`gossip_menu_id`), `npcflag` = VALUES(`npcflag`),
  `unit_class` = VALUES(`unit_class`);

DELETE t FROM `creature_default_trainer` t
INNER JOIN `mod_customnpcs_stormwind_roster` r ON r.`entry` = t.`CreatureId`;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`)
SELECT `entry`, `trainer_id` FROM `mod_customnpcs_stormwind_roster`;

-- Retain only source supplies present in Wrath, without later currencies/recipes.
DELETE v FROM `npc_vendor` v
INNER JOIN `mod_customnpcs_stormwind_roster` r ON r.`entry` = v.`entry`;
"""
    vendors = [[npc["entry"], vendor["slot"], vendor["item"], vendor["maxcount"],
                vendor["incrtime"], vendor["ExtendedCost"]] for npc in npcs for vendor in npc["vendors"]]
    if vendors:
        sql += "INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`) VALUES\n"
        sql += values(vendors)
    for npc in npcs:
        if not npc["vendors"]:
            continue
        menu = npc["entry"]
        sql += f"""
-- {npc['name']}: both training and supplies must be reachable from gossip.
DELETE FROM `gossip_menu_option` WHERE `MenuID` = {menu};
DELETE FROM `gossip_menu` WHERE `MenuID` = {menu};
INSERT INTO `gossip_menu` (`MenuID`, `TextID`)
SELECT {menu}, `TextID` FROM `gossip_menu` WHERE `MenuID` = {npc['gossip_menu_id']};
INSERT INTO `gossip_menu_option`
  (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`)
VALUES
  ({menu}, 0, 3, 'Train me.', 3266, 5, 16),
  ({menu}, 1, 1, 'Let me browse your goods.', 8097, 3, 128);
"""
    sql += """
-- Seed only missing Stormwind spawns. Do not delete/recreate existing NPCs or move outside-city copies.
SET @MOD_CUSTOMNPCS_SW_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_stormwind_existing`;
SET @MOD_CUSTOMNPCS_SW_EXISTING_SQL := CONCAT(
  'CREATE TEMPORARY TABLE `mod_customnpcs_stormwind_existing` AS ',
  'SELECT c.`guid`, c.`', @MOD_CUSTOMNPCS_SW_ENTRY_COLUMN, '` AS `entry` ',
  'FROM `creature` c INNER JOIN `mod_customnpcs_stormwind_roster` r ON r.`entry` = c.`',
  @MOD_CUSTOMNPCS_SW_ENTRY_COLUMN, '` ',
  'WHERE c.`map` = 0 AND c.`position_x` BETWEEN -9200 AND -7700 ',
  'AND c.`position_y` BETWEEN 100 AND 2500'
);
PREPARE mod_customnpcs_sw_existing FROM @MOD_CUSTOMNPCS_SW_EXISTING_SQL;
EXECUTE mod_customnpcs_sw_existing;
DEALLOCATE PREPARE mod_customnpcs_sw_existing;
SET @MOD_CUSTOMNPCS_SW_INSERT_SQL := CONCAT(
  'INSERT INTO `creature` (`', @MOD_CUSTOMNPCS_SW_ENTRY_COLUMN,
  '`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `equipment_id`, ',
  '`position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `MovementType`) ',
  'SELECT r.`entry`, 0, 1519, 1519, 1, 1, 1, r.`position_x`, r.`position_y`, r.`position_z`, ',
  'r.`orientation`, 300, 0 FROM `mod_customnpcs_stormwind_roster` r ',
  'LEFT JOIN `mod_customnpcs_stormwind_existing` s ON s.`entry` = r.`entry` WHERE s.`guid` IS NULL'
);
PREPARE mod_customnpcs_sw_insert FROM @MOD_CUSTOMNPCS_SW_INSERT_SQL;
EXECUTE mod_customnpcs_sw_insert;
DEALLOCATE PREPARE mod_customnpcs_sw_insert;
DROP TEMPORARY TABLE `mod_customnpcs_stormwind_existing`;
DROP TEMPORARY TABLE `mod_customnpcs_stormwind_roster`;

"""
    appearance = appearance_template(manifest)
    appearance = appearance.replace("Orgrimmar", "Stormwind").replace("orgrimmar", "stormwind")
    appearance = appearance.replace("tools/generate_stormwind_appearances.py", "tools/generate_stormwind_trainers.py")
    appearance = appearance.replace("the later_expansion_trainers.sql roster", "the Stormwind roster above")
    appearance = appearance.replace("The seven legacy goblins use fixed native goblin displays, not player-race substitutes.",
                                    "Native Wildhammer displays retain NPC-only tattoos; other NPCs use player outfits.")
    appearance = appearance.replace("c.`map` = 1", "c.`map` = 0")
    appearance = appearance.replace("BETWEEN 1200 AND 2300", "BETWEEN -9200 AND -7700")
    appearance = appearance.replace("BETWEEN -5100 AND -3800", "BETWEEN 100 AND 2500")
    return sql + appearance


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify both generated SQL files.")
    args = parser.parse_args()
    sql = generate(json.loads(MANIFEST.read_text()))
    for path in OUTPUTS:
        if args.check:
            if not path.exists() or path.read_text() != sql:
                raise SystemExit(f"Regenerate {path.relative_to(ROOT)}")
        else:
            path.write_text(sql)
    print("Stormwind SQL matches the roster." if args.check else "Generated Stormwind trainer SQL.")


if __name__ == "__main__":
    main()
