#!/usr/bin/env python3
"""Deliver source-gameplay corrections to already-installed Chapter 1/2 realms."""
import argparse
from pathlib import Path
from generate_broken_seal_polish import generate as polish_sql

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'data/sql/db-world/updates/2026_10_08_00_broken_seal_source_gameplay.sql'


def generate():
    return '''-- The Broken Seal: source gameplay, meaningful travel and natural interactions.
-- Requires installed Chapters 1/2 and a rebuilt/restarted worldserver.
-- Installed Chapters 3/4 must also reapply their current base SQL before restarting.
-- Preserves quest IDs/history, surviving spawn GUIDs and spawn appearance overrides.
-- Native phase masks, quests, spawn homes and patrols remain unchanged.
-- Generated by tools/generate_broken_seal_source_gameplay.py; see docs/broken-seal/source-review.md.
''' + polish_sql(include_later=False)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = generate()
    if args.check:
        assert OUT.read_text() == content, 'Stale source-gameplay upgrade'
    else:
        OUT.write_text(content)
    print('Generated/checked source-gameplay upgrade; optional chapter bases are documented separately.')


if __name__ == '__main__':
    main()
