#!/usr/bin/env python3
"""Generate an ownership-gated quality upgrade for any installed campaign chapters."""
import argparse
import json
from pathlib import Path

from broken_seal_content import ordinary_loot_sql, owned_rows, ownership, quest_poi_rows, validate_quest_polish
from generate_broken_seal_chapter1 import quote

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/sql/db-world/updates/2026_10_07_04_broken_seal_campaign_quality.sql'


def generate():
    chapters=[json.loads((ROOT/f'data/quests/broken_seal_chapter{n}.json').read_text()) for n in range(1,5)]
    hubs=json.loads((ROOT/'data/quests/broken_seal_hubs.json').read_text())
    text='''-- The Broken Seal: authored quests, objective maps, enemy rewards and hub directions.
-- Generated by tools/generate_broken_seal_quality.py. Rebuild/restart for runtime changes.
-- Updates only installed module-owned entries; Chapters 3/4 and hubs are optional.
-- Quest IDs, progression, spawn GUIDs, outfits and native world placements are preserved.
-- See docs/broken-seal/quality-review.md.
CREATE TABLE IF NOT EXISTS `mod_customnpcs_bs_content` (
  `kind` VARCHAR(16) NOT NULL, `entry` INT UNSIGNED NOT NULL, `chapter` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`kind`,`entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TEMPORARY TABLE IF EXISTS `bs_quality_guard`;
CREATE TEMPORARY TABLE `bs_quality_guard` (`id` TINYINT PRIMARY KEY);
INSERT INTO `bs_quality_guard` VALUES (1);
'''
    # Existing hub installs gain two new owned namespaces. Check them before any content changes.
    for actor in hubs['residents']:
        entry=actor['entry']
        for kind,table,column in [('npc_text','npc_text','ID'),('gossip_menu','gossip_menu','MenuID')]:
            text+=f'''INSERT INTO `bs_quality_guard` SELECT 1
WHERE {ownership('creature',entry,0)}
  AND EXISTS (SELECT 1 FROM `{table}` WHERE `{column}`={entry})
  AND NOT {ownership(kind,entry,0)};
'''
    for chapter,data in enumerate(chapters,1):
        for key,value in data.get('story_greetings',{}).items():
            entry=data['ids'][key]
            text+=f'''INSERT INTO `bs_quality_guard` SELECT 1
WHERE {ownership('creature',data['ids'][value['actor']],chapter)}
  AND EXISTS (SELECT 1 FROM `npc_text` WHERE `ID`={entry})
  AND NOT {ownership('npc_text',entry,chapter)};
'''
    text+='DROP TEMPORARY TABLE `bs_quality_guard`;\nSTART TRANSACTION;\n'
    for chapter,data in enumerate(chapters,1):
        validate_quest_polish(data)
        actors=data['actors']+data.get('hostile',[])
        for key,value in data.get('story_greetings',{}).items():
            entry=data['ids'][key]
            text+=f"INSERT INTO `mod_customnpcs_bs_content` SELECT 'npc_text',{entry},{chapter} WHERE {ownership('creature',data['ids'][value['actor']],chapter)} ON DUPLICATE KEY UPDATE `chapter`=VALUES(`chapter`);\n"
            text+=owned_rows('npc_text',['ID','text0_0','Probability0'],[[entry,value['text'],1]],'npc_text',chapter,['ID'])
        for actor in actors:
            entry=actor['entry']
            text+=f"UPDATE `creature_template` SET `name`={quote(actor['name'])} WHERE `entry`={entry} AND {ownership('creature',entry,chapter)};\n"
            if actor.get('npc_flags'):
                # Chapter 1's hand-authored npc_texts are already complete.
                if chapter>1:
                    text+=owned_rows('npc_text',['ID','text0_0','Probability0'],
                                     [[entry,actor['greeting'],1]],'creature',chapter,['ID'])
            outfit=actor.get('outfit',{})
            weapons=actor.get('weapons',[outfit.get('mainhand',0),outfit.get('offhand',0),outfit.get('ranged',0)])
            if any(weapons):
                text+=owned_rows('creature_equip_template',['CreatureID','ID','ItemID1','ItemID2','ItemID3'],
                                 [[entry,1,*weapons]],'creature',chapter,['CreatureID','ID'])
        text+=ordinary_loot_sql(actors,chapter)
        # The ordinary table replacement must restore the quest-only drops too.
        quest_loot=([{'actor':'NPC_CULT_SCOUT','item':'ITEM_ORDERS'}] if chapter==1 else
                    [{'actor':'NPC_MATRIARCH','item':'ITEM_HIDE'}] if chapter==2 else data.get('loot',[]))
        text+=owned_rows('creature_loot_template',
                         ['Entry','Item','Reference','Chance','QuestRequired','LootMode','GroupId','MinCount','MaxCount'],
                         [[data['ids'][v['actor']],data['ids'][v['item']],0,100,1,1,0,1,1] for v in quest_loot],
                         'creature',chapter,['Entry','Item'])
        for obj in data['objects']:
            text+=f"UPDATE `gameobject_template` SET `name`={quote(obj['name'])} WHERE `entry`={obj['entry']} AND {ownership('gameobject',obj['entry'],chapter)};\n"
        for item in data['items']:
            text+=f"UPDATE `item_template` SET `displayid`={item['display']},`description`={quote(item['description'])} WHERE `entry`={item['entry']} AND {ownership('item',item['entry'],chapter)};\n"
        for quest in data['quests']:
            cols=['ID','LogDescription','QuestDescription','QuestCompletionLog']+[f'ObjectiveText{i}' for i in range(1,5)]
            labels=list(quest['objective_labels'].values())
            text+=owned_rows('quest_template',cols,[[quest['id'],quest['objectives'],quest['description'],quest['return_text'],
                                                  *labels,*['']*(4-len(labels))]],'quest',chapter,['ID'])
            text+=owned_rows('quest_offer_reward',['ID','RewardText'],[[quest['id'],quest['completion']]],'quest',chapter,['ID'])
            text+=owned_rows('quest_request_items',['ID','CompletionText'],[[quest['id'],quest['request_text']]],'quest',chapter,['ID'])
            for table in ['quest_poi_points','quest_poi']:
                text+=f"DELETE FROM `{table}` WHERE `QuestID`={quest['id']} AND {ownership('quest',quest['id'],chapter)};\n"
        actor_points={a['key']:a['point'] for a in data['actors'] if a.get('point')}
        actor_points.update(NPC_ORTELL='ortell',NPC_PRISONER='prison',NPC_JAROD_FREE='refuge',NPC_DEZCO='dezco',NPC_MEI='mei')
        actor_points.update(NPC_YIMO='yimo')
        actor_points.update({o['key']:o['points'][0] for o in data['objects'] if o.get('questgiver')})
        poi,points=quest_poi_rows(data,actor_points)
        text+=owned_rows('quest_poi',['QuestID','id','ObjectiveIndex','MapID','WorldMapAreaId','Floor','Priority','Flags'],poi,'quest',chapter)
        text+=owned_rows('quest_poi_points',['QuestID','Idx1','Idx2','X','Y'],points,'quest',chapter)
    for actor in hubs['residents']:
        entry=actor['entry']
        for kind in ['npc_text','gossip_menu']:
            text+=f"INSERT INTO `mod_customnpcs_bs_content` SELECT '{kind}',{entry},0 WHERE {ownership('creature',entry,0)} ON DUPLICATE KEY UPDATE `chapter`=VALUES(`chapter`);\n"
        text+=f"UPDATE `creature_template` SET `name`={quote(actor['name'])},`npcflag`=1,`gossip_menu_id`={entry} WHERE `entry`={entry} AND {ownership('creature',entry,0)};\n"
        text+=owned_rows('npc_text',['ID','text0_0','Probability0'],[[entry,actor['greeting'],1]],'creature',0,['ID'])
        text+=f"DELETE FROM `gossip_menu` WHERE `MenuID`={entry} AND {ownership('gossip_menu',entry,0)};\n"
        text+=owned_rows('gossip_menu',['MenuID','TextID'],[[entry,entry]],'creature',0)
    return text+'COMMIT;\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    text=generate()
    if args.check:
        assert OUT.read_text()==text, 'Stale campaign quality upgrade'
    else:
        OUT.write_text(text)
    print('Generated/checked ownership-gated campaign quality upgrade for Chapters 1-4.')


if __name__=='__main__':
    main()
