#!/usr/bin/env python3
"""Generate the module's Orgrimmar appearance/placement SQL from its checked roster."""

import argparse
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "data/npcs/orgrimmar_trainers.json"
OUTPUTS = (
    ROOT / "data/sql/db-world/base/later_expansion_appearances.sql",
    ROOT / "data/sql/db-world/updates/2026_10_05_01_orgrimmar_appearances.sql",
)
ARMOR = ("head", "shoulders", "shirt", "chest", "waist", "legs", "feet", "wrists", "hands", "back", "tabard")


def number(value):
    if type(value) not in (int, float) or not math.isfinite(value):
        raise ValueError(f"SQL value must be a finite number: {value!r}")
    return str(value) if isinstance(value, int) else f"{value:.4f}".rstrip("0").rstrip(".")


def values(records):
    return ",\n".join("  (" + ", ".join(number(value) for value in record) + ")" for record in records) + ";\n"


def generate(manifest):
    npcs = manifest["npcs"]
    outfits = [npc for npc in npcs if npc["outfit"]]
    sql = """-- mod-customNPCs: Cataclysm/MoP Orgrimmar appearances and Wrath placements.
-- Generated by tools/generate_orgrimmar_appearances.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql and the later_expansion_trainers.sql roster.
-- Native displays, armor textures, customization and weapons were checked in build 12340.
-- Only this roster is updated. Existing spawn GUIDs and per-spawn outfit overrides survive.
-- Restart worldserver after applying: model/equipment/addon/spawn caches must also reload.
-- See docs/orgrimmar-trainers.md for sources, substitutions and placement checks.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_orgrimmar_appearance`;
CREATE TEMPORARY TABLE `mod_customnpcs_orgrimmar_appearance` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `display_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL,
  `mainhand` INT UNSIGNED NOT NULL,
  `offhand` INT UNSIGNED NOT NULL,
  `ranged` INT UNSIGNED NOT NULL,
  `stand_state` TINYINT UNSIGNED NOT NULL,
  `sheath_state` TINYINT UNSIGNED NOT NULL
);

"""
    for npc in npcs:
        name = npc["name"].replace("\n", " ").replace("\r", " ")
        sql += f"-- {npc['entry']}: {name} (source {npc['source_entry']}, race {npc['race']}, gender {npc['gender']}).\n"
    sql += "INSERT INTO `mod_customnpcs_orgrimmar_appearance` VALUES\n"
    sql += values([[npc["entry"], npc["fallback_display"], *npc["position"], *npc["equipment"],
                    npc["stand_state"], npc["sheath_state"]] for npc in npcs])
    sql += """
-- The seven legacy goblins use fixed native goblin displays, not player-race substitutes.
DELETE a FROM `mod_customnpcs_outfit_entry` a
INNER JOIN `mod_customnpcs_orgrimmar_appearance` r ON r.`entry` = a.`creature_entry`;

-- These outfit IDs belong to this module roster; unrelated outfits are untouched.
DELETE FROM `mod_customnpcs_outfit` WHERE `outfit_id` IN (
"""
    sql += "  " + ", ".join(str(npc["entry"]) for npc in outfits) + "\n);\n"
    columns = ("outfit_id", "race", "gender", "class", "skin", "face", "hair", "hair_color",
               "facial_hair", "guild_id", *ARMOR, "mainhand", "offhand", "ranged")
    sql += "INSERT INTO `mod_customnpcs_outfit`\n  (" + ", ".join(f"`{column}`" for column in columns) + ")\nVALUES\n"
    rows = []
    for npc in outfits:
        outfit = npc["outfit"]
        rows.append([npc["entry"], *[outfit[field] for field in columns[1:9]], 0,
                     *[outfit[field] for field in ARMOR], *npc["equipment"]])
    sql += values(rows)
    sql += "\nINSERT INTO `mod_customnpcs_outfit_entry` (`creature_entry`, `outfit_id`) VALUES\n"
    sql += values([[npc["entry"], npc["entry"]] for npc in outfits])
    sql += """
-- One fixed native fallback per NPC: correct race/gender even with outfits disabled.
DELETE m FROM `creature_template_model` m
INNER JOIN `mod_customnpcs_orgrimmar_appearance` r ON r.`entry` = m.`CreatureID`;
INSERT INTO `creature_template_model`
  (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`)
SELECT `entry`, 0, `display_id`, 1, 1 FROM `mod_customnpcs_orgrimmar_appearance`;

-- Native held weapons/tools also apply to legacy goblins and to disabled-outfit fallbacks.
DELETE e FROM `creature_equip_template` e
INNER JOIN `mod_customnpcs_orgrimmar_appearance` r ON r.`entry` = e.`CreatureID`;
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`)
SELECT `entry`, 1, `mainhand`, `offhand`, `ranged` FROM `mod_customnpcs_orgrimmar_appearance`;

-- Preserve addon paths, mounts, auras and higher bytes; copy supported idle/sheath states only.
INSERT INTO `creature_template_addon` (`entry`, `bytes1`, `bytes2`)
SELECT `entry`, `stand_state`, `sheath_state` FROM `mod_customnpcs_orgrimmar_appearance`
ON DUPLICATE KEY UPDATE
  `bytes1` = (`bytes1` & 4294967040) | VALUES(`bytes1`),
  `bytes2` = (`bytes2` & 4294967040) | VALUES(`bytes2`);

-- Support both older AzerothCore's creature.id and current creature.id1 schemas.
SET @MOD_CUSTOMNPCS_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
SET @MOD_CUSTOMNPCS_PLACEMENT_SQL := CONCAT(
  'UPDATE `creature` c INNER JOIN `mod_customnpcs_orgrimmar_appearance` r ON c.`',
  @MOD_CUSTOMNPCS_ENTRY_COLUMN, '` = r.`entry` ',
  'SET c.`position_x` = r.`position_x`, c.`position_y` = r.`position_y`, ',
  'c.`position_z` = r.`position_z`, c.`orientation` = r.`orientation`, c.`equipment_id` = 1 ',
  'WHERE c.`map` = 1 AND c.`position_x` BETWEEN 1200 AND 2300 ',
  'AND c.`position_y` BETWEEN -5100 AND -3800'
);
PREPARE mod_customnpcs_placement FROM @MOD_CUSTOMNPCS_PLACEMENT_SQL;
EXECUTE mod_customnpcs_placement;
DEALLOCATE PREPARE mod_customnpcs_placement;

DROP TEMPORARY TABLE `mod_customnpcs_orgrimmar_appearance`;
"""
    return sql


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if checked-in SQL differs from the roster.")
    args = parser.parse_args()
    sql = generate(json.loads(MANIFEST.read_text()))
    for path in OUTPUTS:
        if args.check:
            if not path.exists() or path.read_text() != sql:
                raise SystemExit(f"Regenerate {path.relative_to(ROOT)}")
        else:
            path.write_text(sql)
    print("Orgrimmar appearance SQL matches the roster." if args.check else "Generated Orgrimmar appearance SQL.")


if __name__ == "__main__":
    main()
