#!/usr/bin/env python3
"""Build the Chapter 1/2 polish upgrade without requiring later installed chapters."""
import argparse
import copy
import json
from pathlib import Path
from generate_broken_seal_chapter1 import sql as chapter1_sql
from generate_broken_seal_chapter2 import sql as chapter2_sql
from generate_broken_seal_hubs import sql as hub_sql

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data/sql/db-world/updates/2026_10_07_03_broken_seal_world_polish.sql'


def generate():
    chapters=[json.loads((ROOT/f'data/quests/broken_seal_chapter{i}.json').read_text()) for i in [1,2]]
    hubs=copy.deepcopy(json.loads((ROOT/'data/quests/broken_seal_hubs.json').read_text()))
    hubs['max_chapter']=2
    hubs['hubs']=[h for h in hubs['hubs'] if h['chapter']<=2]
    keys={h['key'] for h in hubs['hubs']}
    hubs['guards']=[a for a in hubs['guards'] if a['hub'] in keys]
    hubs['residents']=[a for a in hubs['residents'] if a['hub'] in keys]
    hubs['objects']=[o for o in hubs['objects'] if o['hub'] in keys]
    hubs['encounter_camps']=[h for h in hubs.get('encounter_camps',[]) if h.get('chapter',2)<=2]
    hubs['encounter_scenery']=[o for o in hubs.get('encounter_scenery',[]) if o['hub'] in {h['key'] for h in hubs['encounter_camps']}]
    hubs['retired_spawn_keys']=[k for k in hubs.get('retired_spawn_keys',[]) if not k.startswith(('BS-HUB:dawnchasers_','BS-HUB:village_'))]
    text='''-- The Broken Seal: normal-world camp, appearance, loot and rescue polish.
-- Requires installed Chapters 1/2 and the rebuilt module. No phasing or character migrations.
-- Native quest templates, spawns and objects are retained. Optional later resource fixes are owner-gated.
-- Generated by tools/generate_broken_seal_polish.py; see docs/broken-seal/world-polish.md.
'''
    text+=chapter1_sql(chapters[0])+chapter2_sql(chapters[1])+hub_sql(hubs)
    # Existing add-on backups restore only still-unmodified applied homes. No fresh stock move is authored.
    text+='\n'+(ROOT/'data/sql/support/restore_broken_seal_hub_native_spawns.sql').read_text()
    # Stock-textured fallbacks and replacement sign models also reach installed Chapters 3/4.
    for n in [3,4]:
        d=json.loads((ROOT/f'data/quests/broken_seal_chapter{n}.json').read_text())
        for a in d['actors']:
            if not a.get('outfit'):continue
            text+=f'''UPDATE `creature_template_model` m INNER JOIN `mod_customnpcs_bs_content` owner
ON owner.`kind`='creature' AND owner.`entry`=m.`CreatureID` AND owner.`chapter`={n}
SET m.`CreatureDisplayID`={a['display']} WHERE m.`CreatureID`={a['entry']} AND m.`Idx`=0;
'''
        for o in d['objects']:
            name=o['name'].replace("'","''")
            text+=f'''UPDATE `gameobject_template` g INNER JOIN `mod_customnpcs_bs_content` owner
ON owner.`kind`='gameobject' AND owner.`entry`=g.`entry` AND owner.`chapter`={n}
SET g.`displayId`={o['display']},g.`size`={o['scale']},g.`name`='{name}' WHERE g.`entry`={o['entry']};
'''
    return text


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args();text=generate()
    if a.check:assert OUT.read_text()==text,'Stale world polish upgrade'
    else:OUT.write_text(text)
    print('Generated/checked normal-world polish upgrade, compatible with Chapters 1/2 alone.')


if __name__=='__main__':main()
