#!/usr/bin/env python3
"""Generate the four later capital rosters in their installation order."""

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from generate_orgrimmar_appearances import generate as appearance_template, number, values

CITIES = (("ironforge", "03"), ("darnassus", "04"), ("thunder_bluff", "05"), ("undercity", "06"))


def quoted(value):
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def generate(manifest):
    city, slug = manifest["city"], manifest["slug"]
    map_id, zone = manifest["map"], manifest["zone"]
    xmin, xmax, ymin, ymax = manifest["bounds"]
    npcs = manifest["npcs"]
    sql = f"""-- mod-customNPCs: Cataclysm/MoP additions to {city}, converted to Wrath.
-- Generated by tools/generate_city_trainers.py; edit the JSON roster first.
-- Requires custom_npc_appearances.sql. Includes new identities, native curricula,
-- checked appearances and map-{map_id} placements. Does not alter existing stock NPCs.
-- Safe to reapply: existing spawn GUIDs and intentional spawn outfit overrides survive.
-- Restart worldserver after applying. See docs/{slug}-trainers.md.

DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_{slug}_roster`;
CREATE TEMPORARY TABLE `mod_customnpcs_{slug}_roster` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `subname` VARCHAR(100) NOT NULL,
  `gossip_menu_id` INT UNSIGNED NOT NULL,
  `npcflag` INT UNSIGNED NOT NULL,
  `unit_class` TINYINT UNSIGNED NOT NULL,
  `minlevel` TINYINT UNSIGNED NOT NULL,
  `maxlevel` TINYINT UNSIGNED NOT NULL,
  `trainer_id` INT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL,
  `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL,
  `orientation` FLOAT NOT NULL
);
INSERT INTO `mod_customnpcs_{slug}_roster` VALUES
"""
    rows = []
    for npc in npcs:
        menu = npc["entry"] if npc["vendors"] else npc["gossip_menu_id"]
        row = [number(npc["entry"]), quoted(npc["name"]), quoted(npc["subname"]),
               *[number(value) for value in [menu, npc["npcflag"], npc["unit_class"], npc["minlevel"],
                                            npc["maxlevel"], npc["trainer_id"], *npc["position"]]]]
        rows.append("  (" + ", ".join(row) + ")")
    sql += ",\n".join(rows) + ";\n"
    sql += f"""
-- Neutral custom-realm faction, valid creature stat classes, matching original titles/services.
INSERT INTO `creature_template`
  (`entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`,
   `npcflag`, `unit_class`, `unit_flags`, `type`, `AIName`, `ScriptName`, `flags_extra`)
SELECT `entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, 2, 35,
  `npcflag`, `unit_class`, 2, 7, 'NullCreatureAI', '', 2
FROM `mod_customnpcs_{slug}_roster`
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`), `subname` = VALUES(`subname`),
  `gossip_menu_id` = VALUES(`gossip_menu_id`), `npcflag` = VALUES(`npcflag`),
  `unit_class` = VALUES(`unit_class`);

DELETE t FROM `creature_default_trainer` t
INNER JOIN `mod_customnpcs_{slug}_roster` r ON r.`entry` = t.`CreatureId`;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`)
SELECT `entry`, `trainer_id` FROM `mod_customnpcs_{slug}_roster`;

-- Retain only source supplies present in Wrath, without later currencies/recipes.
DELETE v FROM `npc_vendor` v
INNER JOIN `mod_customnpcs_{slug}_roster` r ON r.`entry` = v.`entry`;
"""
    vendors = [[npc["entry"], vendor["slot"], vendor["item"], vendor["maxcount"],
                vendor["incrtime"], vendor["ExtendedCost"]] for npc in npcs for vendor in npc["vendors"]]
    if vendors:
        sql += "INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`) VALUES\n"
        sql += values(vendors)
    for npc in npcs:
        if not npc["vendors"]:
            continue
        menu = npc["entry"]
        sql += f"""
-- {npc['name']}: both training and supplies must be reachable from gossip.
DELETE FROM `gossip_menu_option` WHERE `MenuID` = {menu};
DELETE FROM `gossip_menu` WHERE `MenuID` = {menu};
INSERT INTO `gossip_menu` (`MenuID`, `TextID`)
SELECT {menu}, `TextID` FROM `gossip_menu` WHERE `MenuID` = {npc['gossip_menu_id']};
INSERT INTO `gossip_menu_option`
  (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`)
VALUES
  ({menu}, 0, 3, 'Train me.', 3266, 5, 16),
  ({menu}, 1, 1, 'Let me browse your goods.', 8097, 3, 128);
"""
    sql += f"""
-- Seed only missing {city} spawns. Do not delete/recreate existing NPCs or move outside-city copies.
SET @MOD_CUSTOMNPCS_{slug.upper()}_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id')
  ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_{slug}_existing`;
SET @MOD_CUSTOMNPCS_{slug.upper()}_EXISTING_SQL := CONCAT(
  'CREATE TEMPORARY TABLE `mod_customnpcs_{slug}_existing` AS ',
  'SELECT c.`guid`, c.`', @MOD_CUSTOMNPCS_{slug.upper()}_ENTRY_COLUMN, '` AS `entry` ',
  'FROM `creature` c INNER JOIN `mod_customnpcs_{slug}_roster` r ON r.`entry` = c.`',
  @MOD_CUSTOMNPCS_{slug.upper()}_ENTRY_COLUMN, '` ',
  'WHERE c.`map` = {map_id} AND c.`position_x` BETWEEN {xmin} AND {xmax} ',
  'AND c.`position_y` BETWEEN {ymin} AND {ymax}'
);
PREPARE mod_customnpcs_{slug}_existing FROM @MOD_CUSTOMNPCS_{slug.upper()}_EXISTING_SQL;
EXECUTE mod_customnpcs_{slug}_existing;
DEALLOCATE PREPARE mod_customnpcs_{slug}_existing;
SET @MOD_CUSTOMNPCS_{slug.upper()}_INSERT_SQL := CONCAT(
  'INSERT INTO `creature` (`', @MOD_CUSTOMNPCS_{slug.upper()}_ENTRY_COLUMN,
  '`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `equipment_id`, ',
  '`position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `MovementType`) ',
  'SELECT r.`entry`, {map_id}, {zone}, {zone}, 1, 1, 1, r.`position_x`, r.`position_y`, r.`position_z`, ',
  'r.`orientation`, 300, 0 FROM `mod_customnpcs_{slug}_roster` r ',
  'LEFT JOIN `mod_customnpcs_{slug}_existing` s ON s.`entry` = r.`entry` WHERE s.`guid` IS NULL'
);
PREPARE mod_customnpcs_{slug}_insert FROM @MOD_CUSTOMNPCS_{slug.upper()}_INSERT_SQL;
EXECUTE mod_customnpcs_{slug}_insert;
DEALLOCATE PREPARE mod_customnpcs_{slug}_insert;
DROP TEMPORARY TABLE `mod_customnpcs_{slug}_existing`;
DROP TEMPORARY TABLE `mod_customnpcs_{slug}_roster`;

"""
    appearance = appearance_template(manifest)
    appearance = appearance.replace("Orgrimmar", city).replace("orgrimmar", slug)
    appearance = appearance.replace(f"tools/generate_{slug}_appearances.py", "tools/generate_city_trainers.py")
    appearance = appearance.replace("the later_expansion_trainers.sql roster", f"the {city} roster above")
    appearance = appearance.replace("The seven legacy goblins use fixed native goblin displays, not player-race substitutes.",
                                    "Use checked native outfits and fixed same-race/gender fallback displays.")
    appearance = appearance.replace("legacy goblins", "native fallback displays")
    appearance = appearance.replace("correct race/gender even with outfits disabled",
                                    "matches the intended rendered race/gender with outfits disabled")
    appearance = appearance.replace("c.`map` = 1", f"c.`map` = {map_id}")
    appearance = appearance.replace("BETWEEN 1200 AND 2300", f"BETWEEN {xmin} AND {xmax}")
    appearance = appearance.replace("BETWEEN -5100 AND -3800", f"BETWEEN {ymin} AND {ymax}")
    return sql + appearance


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify generated installation/update SQL.")
    parser.add_argument("--city", choices=[city for city, _ in CITIES], help="Generate one city only.")
    args = parser.parse_args()
    for city, sequence in CITIES:
        if args.city and city != args.city:
            continue
        manifest = json.loads((ROOT / f"data/npcs/{city}_trainers.json").read_text())
        sql = generate(manifest)
        paths = (ROOT / f"data/sql/db-world/base/{city}_trainers.sql",
                 ROOT / f"data/sql/db-world/updates/2026_10_05_{sequence}_{city}_trainers.sql")
        for path in paths:
            if args.check:
                if not path.exists() or path.read_text() != sql:
                    raise SystemExit(f"Regenerate {path.relative_to(ROOT)}")
            else:
                path.write_text(sql)
        print(f"{manifest['city']} SQL {'matches the roster' if args.check else 'generated'}.")


if __name__ == "__main__":
    main()
