#!/usr/bin/env python3
"""Ship the opening-route revision to realms whose earlier polish is already applied."""
import argparse
from pathlib import Path
from generate_broken_seal_polish import generate as polish_sql

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'data/sql/db-world/updates/2026_10_07_05_broken_seal_chapter1_flow.sql'


def generate():
    return '''-- The Broken Seal: separate rescue camp, defended ward sites and spyglass observation.
-- Requires installed Chapters 1/2 and a rebuilt/restarted worldserver.
-- Reuses ownership/collision checks; preserves quest counters, spawn GUIDs and spawn outfit overrides.
-- Generated by tools/generate_broken_seal_flow.py; see docs/broken-seal/chapter1-implementation.md.
''' + polish_sql(include_later=False)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = generate()
    if args.check:
        assert OUT.read_text() == content, 'Stale Chapter 1 flow upgrade'
    else:
        OUT.write_text(content)
    print('Generated/checked Chapter 1 route and interaction upgrade.')


if __name__ == '__main__':
    main()
