#!/usr/bin/env python3
"""Generate flight masters and their owned native taxi additions for both world schemas."""

import argparse
import json
from pathlib import Path

from generate_orgrimmar_appearances import generate as appearance_template, number, values
from generate_city_trainers import quoted

ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = (ROOT / "data/sql/db-world/base/flight_masters.sql",
           ROOT / "data/sql/db-world/updates/2026_10_05_07_flight_masters.sql")


def generate(manifest, network):
    npcs, routes = manifest["npcs"], network["routes"]
    entries = ", ".join(str(n["entry"]) for n in npcs)
    sql = """-- mod-customNPCs: additional flight masters in existing Wrath settlements only.
-- Generated by tools/generate_flight_masters.py; edit the researched JSON first.
-- Requires custom_npc_appearances.sql and native taxi *_dbc override tables.
-- Install data/client/flight-masters/patch-F.MPQ on clients before enabling these stops.
-- Preserves the original Wrath taxi network. New IDs fit its 448-node mask.
-- Existing GUIDs and spawn outfit overrides survive; copied NPCs outside their town survive.
-- Restart worldserver after applying. See docs/flight-masters.md.

CREATE TABLE IF NOT EXISTS `mod_customnpcs_flight_node` (
  `node_id` INT UNSIGNED NOT NULL PRIMARY KEY,
  `creature_entry` INT UNSIGNED NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `mod_customnpcs_flight_path` (
  `path_id` INT UNSIGNED NOT NULL PRIMARY KEY,
  `creature_entry` INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

START TRANSACTION;
-- Remove only overrides previously registered to this module's reserved entries.
-- Plain INSERTs below reject collisions with unowned custom taxi overrides.
"""
    for table, column, owner, owner_column in (("taxipathnode_dbc", "PathID", "path", "path_id"),
                                                ("taxipath_dbc", "ID", "path", "path_id"),
                                                ("taxinodes_dbc", "ID", "node", "node_id")):
        sql += f"DELETE t FROM `{table}` t INNER JOIN `mod_customnpcs_flight_{owner}` o ON t.`{column}` = o.`{owner_column}` WHERE o.`creature_entry` IN ({entries});\n"
    sql += f"DELETE FROM `mod_customnpcs_flight_node` WHERE `creature_entry` IN ({entries});\n"
    sql += f"DELETE FROM `mod_customnpcs_flight_path` WHERE `creature_entry` IN ({entries});\n"
    sql += "\nINSERT INTO `taxinodes_dbc`\n  (`ID`, `ContinentID`, `X`, `Y`, `Z`, "
    languages = ("enUS", "enGB", "koKR", "frFR", "deDE", "enCN", "zhCN", "enTW", "zhTW", "esES", "esMX", "ruRU", "ptPT", "ptBR", "itIT", "Unk")
    sql += ", ".join(f"`Name_Lang_{lang}`" for lang in languages)
    sql += ", `Name_Lang_Mask`, `MountCreatureID_1`, `MountCreatureID_2`) VALUES\n"
    node_rows = []
    for n in npcs:
        row = [number(n["taxi_node_id"]), number(n["map"]), *map(number, n["landing_position"]),
               *([quoted(n["town"])] * 16), "65535", *map(number, n["mount_creatures"])]
        node_rows.append("  (" + ", ".join(row) + ")")
    sql += ",\n".join(node_rows) + ";\n"
    sql += "INSERT INTO `taxipath_dbc` (`ID`, `FromTaxiNode`, `ToTaxiNode`, `Cost`) VALUES\n"
    sql += values([[r["id"], r["from"], r["to"], r["cost"]] for r in routes])
    waypoints = [[r["first_waypoint_id"] + i, r["id"], i, r["map"], *p, 0, 0, 0, 0]
                 for r in routes for i, p in enumerate(r["points"])]
    for offset in range(0, len(waypoints), 100):
        sql += "INSERT INTO `taxipathnode_dbc`\n  (`ID`, `PathID`, `NodeIndex`, `ContinentID`, `LocX`, `LocY`, `LocZ`, `Flags`, `Delay`, `ArrivalEventID`, `DepartureEventID`) VALUES\n"
        sql += values(waypoints[offset:offset + 100])
    sql += "INSERT INTO `mod_customnpcs_flight_node` (`node_id`, `creature_entry`) VALUES\n"
    sql += values([[n["taxi_node_id"], n["entry"]] for n in npcs])
    sql += "INSERT INTO `mod_customnpcs_flight_path` (`path_id`, `creature_entry`) VALUES\n"
    sql += values([[r["id"], r["entry"]] for r in routes])
    sql += """
DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_flight_masters`;
CREATE TEMPORARY TABLE `mod_customnpcs_flight_masters` (
  `entry` INT UNSIGNED NOT NULL PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL, `subname` VARCHAR(100) NOT NULL,
  `faction` INT UNSIGNED NOT NULL, `minlevel` TINYINT UNSIGNED NOT NULL,
  `maxlevel` TINYINT UNSIGNED NOT NULL, `display_id` INT UNSIGNED NOT NULL,
  `map_id` SMALLINT UNSIGNED NOT NULL,
  `position_x` FLOAT NOT NULL, `position_y` FLOAT NOT NULL,
  `position_z` FLOAT NOT NULL, `orientation` FLOAT NOT NULL,
  `mainhand` INT UNSIGNED NOT NULL, `offhand` INT UNSIGNED NOT NULL,
  `ranged` INT UNSIGNED NOT NULL, `stand_state` TINYINT UNSIGNED NOT NULL,
  `sheath_state` TINYINT UNSIGNED NOT NULL,
  `min_x` FLOAT NOT NULL, `max_x` FLOAT NOT NULL,
  `min_y` FLOAT NOT NULL, `max_y` FLOAT NOT NULL
);
INSERT INTO `mod_customnpcs_flight_masters` VALUES
"""
    rows = []
    for n in npcs:
        x, y = n["source_position"][:2]
        data = [n["faction"], n["minlevel"], n["maxlevel"], n["fallback_display"], n["map"],
                *n["position"], *n["equipment"], n["stand_state"], n["sheath_state"], x - 450, x + 450, y - 450, y + 450]
        row = [number(n["entry"]), quoted(n["name"]), quoted(n["subname"]), *map(number, data)]
        rows.append("  (" + ", ".join(row) + ")")
    sql += ",\n".join(rows) + ";\n"
    sql += """
INSERT INTO `creature_template`
  (`entry`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`,
   `npcflag`, `unit_class`, `unit_flags`, `rank`, `type`, `AIName`, `ScriptName`, `flags_extra`)
SELECT `entry`, `name`, `subname`, 0, `minlevel`, `maxlevel`, 2, `faction`,
  8192, 1, 2, 1, 7, 'NullCreatureAI', '', 2 FROM `mod_customnpcs_flight_masters`
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `subname` = VALUES(`subname`),
  `npcflag` = VALUES(`npcflag`), `gossip_menu_id` = VALUES(`gossip_menu_id`);

SET @MOD_CUSTOMNPCS_FM_ENTRY_COLUMN := (
  SELECT `COLUMN_NAME` FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE() AND `TABLE_NAME` = 'creature'
    AND `COLUMN_NAME` IN ('id1', 'id') ORDER BY `COLUMN_NAME` DESC LIMIT 1
);
DROP TEMPORARY TABLE IF EXISTS `mod_customnpcs_flight_existing`;
SET @MOD_CUSTOMNPCS_FM_EXISTING_SQL := CONCAT(
  'CREATE TEMPORARY TABLE `mod_customnpcs_flight_existing` AS SELECT c.`guid`, r.`entry` ',
  'FROM `creature` c INNER JOIN `mod_customnpcs_flight_masters` r ON c.`',
  @MOD_CUSTOMNPCS_FM_ENTRY_COLUMN, '` = r.`entry` ',
  'WHERE c.`map` = r.`map_id` AND c.`position_x` BETWEEN r.`min_x` AND r.`max_x` ',
  'AND c.`position_y` BETWEEN r.`min_y` AND r.`max_y`'
);
PREPARE mod_customnpcs_fm_existing FROM @MOD_CUSTOMNPCS_FM_EXISTING_SQL;
EXECUTE mod_customnpcs_fm_existing;
DEALLOCATE PREPARE mod_customnpcs_fm_existing;
SET @MOD_CUSTOMNPCS_FM_INSERT_SQL := CONCAT(
  'INSERT INTO `creature` (`', @MOD_CUSTOMNPCS_FM_ENTRY_COLUMN, '`, `map`, ',
  '`spawnMask`, `phaseMask`, `equipment_id`, `position_x`, `position_y`, `position_z`, ',
  '`orientation`, `spawntimesecs`, `MovementType`) ',
  'SELECT r.`entry`, r.`map_id`, 1, 1, 1, r.`position_x`, r.`position_y`, r.`position_z`, ',
  'r.`orientation`, 300, 0 FROM `mod_customnpcs_flight_masters` r ',
  'LEFT JOIN `mod_customnpcs_flight_existing` s ON s.`entry`=r.`entry` WHERE s.`guid` IS NULL'
);
PREPARE mod_customnpcs_fm_insert FROM @MOD_CUSTOMNPCS_FM_INSERT_SQL;
EXECUTE mod_customnpcs_fm_insert;
DEALLOCATE PREPARE mod_customnpcs_fm_insert;
DROP TEMPORARY TABLE `mod_customnpcs_flight_existing`;

"""
    appearance = appearance_template({"npcs": npcs})
    appearance = appearance[appearance.index("-- The seven legacy goblins"):appearance.index("-- Support both older AzerothCore")]
    appearance = appearance.replace("mod_customnpcs_orgrimmar_appearance", "mod_customnpcs_flight_masters")
    appearance = appearance.replace("-- The seven legacy goblins use fixed native goblin displays, not player-race substitutes.",
                                    "-- Checked player outfits and fixed native fallback displays.")
    appearance = appearance.replace("legacy goblins", "fallback displays")
    sql += appearance
    sql += """
SET @MOD_CUSTOMNPCS_FM_PLACEMENT_SQL := CONCAT(
  'UPDATE `creature` c INNER JOIN `mod_customnpcs_flight_masters` r ON c.`',
  @MOD_CUSTOMNPCS_FM_ENTRY_COLUMN, '` = r.`entry` ',
  'SET c.`position_x`=r.`position_x`, c.`position_y`=r.`position_y`, ',
  'c.`position_z`=r.`position_z`, c.`orientation`=r.`orientation`, c.`equipment_id`=1 ',
  'WHERE c.`map`=r.`map_id` AND c.`position_x` BETWEEN r.`min_x` AND r.`max_x` ',
  'AND c.`position_y` BETWEEN r.`min_y` AND r.`max_y`'
);
PREPARE mod_customnpcs_fm_placement FROM @MOD_CUSTOMNPCS_FM_PLACEMENT_SQL;
EXECUTE mod_customnpcs_fm_placement;
DEALLOCATE PREPARE mod_customnpcs_fm_placement;
DROP TEMPORARY TABLE `mod_customnpcs_flight_masters`;
COMMIT;
"""
    return sql


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads((ROOT / "data/npcs/flight_masters.json").read_text())
    network = json.loads((ROOT / "data/taxi/later_flight_network.json").read_text())
    sql = generate(manifest, network)
    for path in OUTPUTS:
        if args.check:
            if not path.exists() or path.read_text() != sql:
                raise SystemExit(f"Regenerate {path.relative_to(ROOT)}")
        else:
            path.write_text(sql)
    print("Flight-master SQL matches the roster." if args.check else "Generated flight-master SQL.")


if __name__ == "__main__":
    main()
