// Generated by tools/generate_broken_seal_chapter2.py. Do not edit.
#ifndef MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER2_DATA_H
#define MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER2_DATA_H

#include <array>
#include <cstdint>

namespace BrokenSeal::Chapter2
{
enum Id : std::uint32_t
{
    QUEST_SIGNED = 900200,
    QUEST_IDENTITY = 900201,
    QUEST_FIRE = 900202,
    QUEST_BLOOM = 900203,
    QUEST_WASTE = 900204,
    QUEST_TRAINING = 900205,
    QUEST_LABOR = 900206,
    QUEST_AGILITY = 900207,
    QUEST_MENTAL = 900208,
    QUEST_MERCY = 900209,
    QUEST_DOG = 900210,
    QUEST_COLLAR = 900211,
    QUEST_GRUDGE = 900212,
    QUEST_INTELLIGENCE = 900213,
    QUEST_DISCORD = 900214,
    QUEST_GREATER = 900215,
    QUEST_TERRITORY = 900216,
    QUEST_WRITING = 900217,
    QUEST_HEAD = 900218,
    QUEST_SPEECH = 900219,
    QUEST_RIOT = 900220,
    QUEST_BUYERS = 900221,
    QUEST_LETTER = 900222,
    NPC_CONDENNA = 4001200,
    NPC_CARGALL = 4001201,
    NPC_MYLVA = 4001202,
    NPC_DEVORAN = 4001203,
    NPC_JAROD_FREE = 4001204,
    NPC_DEZCO = 4001205,
    NPC_RECRUIT = 4001206,
    NPC_SUPPLICANT_A = 4001207,
    NPC_SUPPLICANT_B = 4001208,
    NPC_SUPPLICANT_C = 4001209,
    NPC_HOUND = 4001210,
    NPC_ORB = 4001211,
    NPC_CROWD = 4001212,
    NPC_OGRE = 4001213,
    NPC_KARRGONN = 4001214,
    NPC_AZENNIOS = 4001215,
    NPC_GARNOTH = 4001216,
    NPC_GROMMKO = 4001217,
    NPC_OKROG = 4001218,
    NPC_RESTRAINT = 4001219,
    NPC_ENFORCER = 4001220,
    NPC_SCENE = 4001221,
    NPC_FIRE = 4001222,
    NPC_SMOLDEROS = 4001223,
    NPC_MATRIARCH = 4001224,
    NPC_FAILED = 4001225,
    NPC_HORRORGUARD = 4001226,
    NPC_GUARD = 4001227,
    NPC_SCOUT = 4001228,
    CREDIT_KNOCKOUT = 4001250,
    CREDIT_IDENTITY = 4001251,
    CREDIT_FIRE = 4001252,
    CREDIT_SUPPLICANT_A = 4001253,
    CREDIT_SUPPLICANT_B = 4001254,
    CREDIT_SUPPLICANT_C = 4001255,
    CREDIT_MYLVA = 4001256,
    CREDIT_DEVORAN = 4001257,
    CREDIT_LOADS = 4001258,
    CREDIT_COURSE = 4001259,
    CREDIT_MENTAL = 4001260,
    CREDIT_MERCY = 4001261,
    CREDIT_DOG_A = 4001262,
    CREDIT_DOG_B = 4001263,
    CREDIT_DOG_C = 4001264,
    CREDIT_GRUDGE = 4001265,
    CREDIT_DROP = 4001266,
    CREDIT_DISCORD = 4001267,
    CREDIT_GARNOTH = 4001268,
    CREDIT_TERRITORY = 4001269,
    CREDIT_OKROG = 4001270,
    CREDIT_HEAD = 4001271,
    CREDIT_SPEECH = 4001272,
    CREDIT_ALTAR = 4001273,
    CREDIT_RIOT = 4001274,
    GO_RENDEZVOUS = 4001300,
    GO_FLOWER = 4001301,
    GO_STONES = 4001302,
    GO_DELIVERY = 4001303,
    GO_COURSE_START = 4001304,
    GO_CHECK_A = 4001305,
    GO_CHECK_B = 4001306,
    GO_CHECK_C = 4001307,
    GO_CHECK_D = 4001308,
    GO_DOG_A = 4001309,
    GO_DOG_B = 4001310,
    GO_DOG_C = 4001311,
    GO_COMMUNIQUE = 4001312,
    GO_PLANS = 4001313,
    GO_DROP = 4001314,
    GO_DISCORD = 4001315,
    GO_GARNOTH = 4001316,
    GO_OKROG = 4001317,
    GO_PODIUM = 4001318,
    GO_PRISON = 4001319,
    GO_BUYERS = 4001320,
    ITEM_BLACKJACK = 900200,
    ITEM_PAPERS = 900201,
    ITEM_IDENTITY = 900202,
    ITEM_BLOSSOMS = 900203,
    ITEM_GEM = 900204,
    ITEM_LEASH = 900205,
    ITEM_COLLAR = 900206,
    ITEM_HIDE = 900207,
    ITEM_COMMUNIQUE = 900208,
    ITEM_PLANS = 900209,
    ITEM_TALISMAN = 900210,
    ITEM_ORB = 900211,
    ITEM_NOTES = 900212,
    ITEM_KEY = 900213,
    ITEM_LEDGER = 900214,
    ITEM_LETTER = 900215,
    ITEM_MIGHT = 900216,
    ITEM_PRECISION = 900217,
    ITEM_SORCERY = 900218,
    ITEM_RESTORATION = 900219,
    ITEM_GUARDING = 900220,
    ITEM_BALANCE = 900221,
    NPC_ORTELL = 4001001,
    NPC_PRISONER = 4001002,
    QUEST_C01_END = 900108,
    SPELL_DISGUISE = 4329,
    SPELL_FIRE_FORM = 4933,
    SPELL_BLACKJACK = 41358,
    SPELL_OPENING = 3365,
    SPELL_STRIKE = 11976,
    SPELL_FIREBALL = 133,
    SPELL_BURNING = 42726,
    NPC_BUTCHER = 4001229,
    SPELL_BLACKJACK_TARGET = 39865,
    SPELL_GEM_TARGET = 34665,
};

inline constexpr std::uint32_t FireDisplay = 2172;

struct Point
{
    float x;
    float y;
    float z;
    float orientation;
};

namespace Locations
{
inline constexpr Point condenna = {892.0000f, 1610.0000f, -20.9751f, 3.1400f};
inline constexpr Point cargall = {894.0000f, 1643.0000f, -12.0580f, 3.1400f};
inline constexpr Point mylva = {862.0000f, 1592.0000f, -24.1901f, 3.1400f};
inline constexpr Point devoran = {915.0000f, 1600.0000f, -15.9102f, 3.1400f};
inline constexpr Point ortell = {1120.0000f, 1550.0000f, 34.5478f, 3.1400f};
inline constexpr Point prison = {990.0000f, 1730.0000f, -9.6758f, 3.1400f};
inline constexpr Point refuge = {1110.0000f, 1545.0000f, 29.1725f, 3.1400f};
inline constexpr Point rendezvous = {966.0000f, 1660.0000f, -9.5552f, 3.1400f};
inline constexpr Point recruit_start = {990.0000f, 1684.0000f, -6.3194f, 3.1400f};
inline constexpr Point recruit_hide = {962.0000f, 1661.0000f, -10.3684f, 3.1400f};
inline constexpr Point supplicant_a = {885.0000f, 1650.0000f, -9.5204f, 3.1400f};
inline constexpr Point supplicant_b = {879.0000f, 1652.0000f, -13.7258f, 3.1400f};
inline constexpr Point supplicant_c = {873.0000f, 1650.0000f, -16.2150f, 3.1400f};
inline constexpr Point stones = {850.0000f, 1600.0000f, -24.1780f, 3.1400f};
inline constexpr Point delivery = {845.0000f, 1630.0000f, -25.4678f, 3.1400f};
inline constexpr Point course_start = {850.0000f, 1570.0000f, -23.4783f, 3.1400f};
inline constexpr Point check_a = {815.0000f, 1570.0000f, -28.8523f, 3.1400f};
inline constexpr Point check_b = {795.0000f, 1605.0000f, -31.4848f, 3.1400f};
inline constexpr Point check_c = {815.0000f, 1630.0000f, -30.1276f, 3.1400f};
inline constexpr Point check_d = {851.0000f, 1564.0000f, -22.6011f, 3.1400f};
inline constexpr Point dog_a = {920.0000f, 1570.0000f, -15.9218f, 3.1400f};
inline constexpr Point dog_b = {944.0000f, 1575.0000f, -12.7843f, 3.1400f};
inline constexpr Point dog_c = {951.0060f, 1610.0000f, -11.6460f, 3.1400f};
inline constexpr Point hound = {918.0000f, 1595.0000f, -16.1545f, 3.1400f};
inline constexpr Point communique = {861.0000f, 1660.0000f, -21.5522f, 3.1400f};
inline constexpr Point plans = {838.0000f, 1685.0000f, -25.3046f, 3.1400f};
inline constexpr Point drop = {950.0000f, 1670.0000f, -11.7303f, 3.1400f};
inline constexpr Point discord = {890.0000f, 1685.0000f, -19.6770f, 3.1400f};
inline constexpr Point karrgonn = {885.0000f, 1690.0000f, -18.8017f, 3.1400f};
inline constexpr Point azennios = {879.0000f, 1685.0000f, -19.2199f, 3.1400f};
inline constexpr Point garnoth = {815.0000f, 1725.0000f, -20.6844f, 3.1400f};
inline constexpr Point okrog = {906.0000f, 1714.0000f, -16.1351f, 3.1400f};
inline constexpr Point podium = {988.0000f, 1710.0000f, -9.1711f, 3.1400f};
inline constexpr Point crowd_a = {997.0000f, 1705.0000f, -6.8197f, 3.1400f};
inline constexpr Point crowd_b = {992.0000f, 1701.0000f, -7.7631f, 3.1400f};
inline constexpr Point crowd_c = {987.0000f, 1703.0000f, -8.8423f, 3.1400f};
inline constexpr Point buyers = {857.0000f, 1676.0000f, -21.9220f, 3.1400f};
inline constexpr Point restraint = {983.0000f, 1725.0000f, -9.3798f, 3.1400f};
inline constexpr Point escape_a = {995.0000f, 1700.0000f, -6.8312f, 3.1400f};
inline constexpr Point escape_b = {1010.0000f, 1655.0000f, 3.3445f, 3.1400f};
inline constexpr Point escape_c = {1060.0000f, 1640.0000f, 23.9755f, 3.1400f};
inline constexpr Point flower_0 = {776.0000f, 1588.0000f, -29.7012f, 3.1400f};
inline constexpr Point flower_1 = {790.0000f, 1580.0000f, -29.9624f, 3.1400f};
inline constexpr Point flower_2 = {805.0000f, 1590.0000f, -29.7299f, 3.1400f};
inline constexpr Point flower_3 = {782.0000f, 1603.0000f, -31.0779f, 3.1400f};
inline constexpr Point flower_4 = {798.0000f, 1608.0000f, -31.6043f, 3.1400f};
inline constexpr Point flower_5 = {774.0000f, 1620.0000f, -32.7476f, 3.1400f};
inline constexpr Point flower_6 = {808.0000f, 1625.0000f, -29.9382f, 3.1400f};
inline constexpr Point flower_7 = {790.0000f, 1638.0000f, -33.7101f, 3.1400f};
inline constexpr Point smolderos = {784.0000f, 1628.0000f, -33.9268f, 3.1400f};
inline constexpr Point fire_0 = {835.0000f, 1664.0000f, -27.0599f, 3.1400f};
inline constexpr Point fire_1 = {824.0000f, 1669.0000f, -28.4060f, 3.1400f};
inline constexpr Point fire_2 = {819.0000f, 1682.0000f, -26.4018f, 3.1400f};
inline constexpr Point fire_3 = {839.0000f, 1679.0000f, -25.5763f, 3.1400f};
inline constexpr Point fire_4 = {852.0000f, 1697.0000f, -22.1805f, 3.1400f};
inline constexpr Point fire_5 = {825.0000f, 1694.0000f, -24.3259f, 3.1400f};
inline constexpr Point fire_6 = {810.0000f, 1672.0000f, -29.0308f, 3.1400f};
inline constexpr Point fire_7 = {844.0000f, 1712.0000f, -20.6457f, 3.1400f};
inline constexpr Point failed_0 = {846.0000f, 1534.0000f, -19.4165f, 3.1400f};
inline constexpr Point failed_1 = {862.0000f, 1528.0000f, -17.8964f, 3.1400f};
inline constexpr Point failed_2 = {880.0000f, 1527.0000f, -16.2161f, 3.1400f};
inline constexpr Point failed_3 = {885.0000f, 1541.0000f, -18.6750f, 3.1400f};
inline constexpr Point failed_4 = {842.0000f, 1548.0000f, -23.4771f, 3.1400f};
inline constexpr Point horrorguard_0 = {811.0000f, 1710.0000f, -19.9715f, 3.1400f};
inline constexpr Point horrorguard_1 = {800.0000f, 1720.0000f, -15.0456f, 3.1400f};
inline constexpr Point horrorguard_2 = {804.0000f, 1740.0000f, -20.7443f, 3.1400f};
inline constexpr Point horrorguard_3 = {827.0000f, 1748.0000f, -17.9652f, 3.1400f};
inline constexpr Point horrorguard_4 = {794.0000f, 1754.0000f, -19.5734f, 3.1400f};
inline constexpr Point horrorguard_5 = {821.0000f, 1757.0000f, -17.2247f, 3.1400f};
inline constexpr Point horrorguard_6 = {790.0000f, 1734.0000f, -20.4124f, 3.1400f};
inline constexpr Point horrorguard_7 = {832.0000f, 1729.0000f, -17.3188f, 3.1400f};
inline constexpr Point horrorguard_8 = {807.0000f, 1771.0000f, -15.7415f, 3.1400f};
inline constexpr Point horrorguard_9 = {829.0000f, 1774.0000f, -13.3625f, 3.1400f};
inline constexpr Point guard_0 = {857.0000f, 1664.0000f, -22.0909f, 3.1400f};
inline constexpr Point guard_1 = {835.0000f, 1681.0000f, -25.9745f, 3.1400f};
inline constexpr Point scout_0 = {859.0000f, 1657.0000f, -22.5584f, 3.1400f};
inline constexpr Point scout_1 = {854.0000f, 1662.0000f, -22.9738f, 3.1400f};
inline constexpr Point matriarch = {955.0000f, 1570.0000f, -10.1519f, 3.1400f};
inline constexpr Point dezco = {-3970.0000f, -3350.0000f, 39.3928f, 3.1400f};
inline constexpr Point garnoth_foe = {810.0000f, 1725.0000f, -20.4484f, 3.1400f};
}

inline constexpr std::array<Point, 4> Course =
{
    Locations::check_a, Locations::check_b, Locations::check_c, Locations::check_d
};

inline constexpr std::array<Point, 3> DogStations =
{
    Locations::dog_a, Locations::dog_b, Locations::dog_c
};

inline constexpr std::array<Point, 4> EscapeRoute =
{
    Locations::escape_a, Locations::escape_b, Locations::escape_c, Locations::refuge
};

struct QuestSupply
{
    std::uint32_t quest;
    std::array<std::uint32_t, 2> items;
};

inline constexpr std::array<QuestSupply, 9> Supplies =
{{
    {QUEST_SIGNED, {ITEM_BLACKJACK, 0}},
    {QUEST_IDENTITY, {ITEM_IDENTITY, 0}},
    {QUEST_WASTE, {ITEM_GEM, 0}},
    {QUEST_MENTAL, {ITEM_ORB, 0}},
    {QUEST_DOG, {ITEM_LEASH, 0}},
    {QUEST_GRUDGE, {ITEM_LEASH, ITEM_COLLAR}},
    {QUEST_GREATER, {ITEM_TALISMAN, 0}},
    {QUEST_WRITING, {ITEM_NOTES, 0}},
    {QUEST_LETTER, {ITEM_LETTER, 0}},
}};

inline constexpr std::array<std::uint32_t, 23> Quests =
{
    QUEST_SIGNED, QUEST_IDENTITY, QUEST_FIRE, QUEST_BLOOM, QUEST_WASTE, QUEST_TRAINING, QUEST_LABOR, QUEST_AGILITY, QUEST_MENTAL, QUEST_MERCY, QUEST_DOG, QUEST_COLLAR, QUEST_GRUDGE, QUEST_INTELLIGENCE, QUEST_DISCORD, QUEST_GREATER, QUEST_TERRITORY, QUEST_WRITING, QUEST_HEAD, QUEST_SPEECH, QUEST_RIOT, QUEST_BUYERS, QUEST_LETTER
};
inline constexpr std::array<std::uint32_t, 18> PersonalEntries =
{
    NPC_JAROD_FREE, NPC_RECRUIT, NPC_SUPPLICANT_A, NPC_SUPPLICANT_B, NPC_SUPPLICANT_C, NPC_HOUND, NPC_ORB, NPC_CROWD, NPC_OGRE, NPC_KARRGONN, NPC_AZENNIOS, NPC_GARNOTH, NPC_GROMMKO, NPC_OKROG, NPC_RESTRAINT, NPC_ENFORCER, NPC_SCENE, NPC_BUTCHER
};
}

#endif
