// Generated by tools/generate_broken_seal_chapter3.py. Do not edit.
#ifndef MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER3_DATA_H
#define MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER3_DATA_H

#include <array>
#include <cstdint>

namespace BrokenSeal::Chapter3
{
enum Id : std::uint32_t
{
    QUEST_SEARCH = 900300,
    QUEST_POISON = 900301,
    QUEST_STEW = 900302,
    QUEST_BLIND = 900303,
    QUEST_THREAT = 900304,
    QUEST_HERBS = 900305,
    QUEST_AGENDA = 900306,
    QUEST_POOLS = 900307,
    QUEST_LIFE = 900308,
    QUEST_VIGIL = 900309,
    QUEST_LIVING = 900310,
    QUEST_LETTER = 900311,
    NPC_KANG = 4001400,
    NPC_KOR = 4001401,
    NPC_NALA = 4001402,
    NPC_CHEZIN = 4001403,
    NPC_LEZA = 4001404,
    NPC_MEI = 4001405,
    NPC_REDHORN = 4001406,
    NPC_CLOUDHOOF = 4001407,
    NPC_REFUGEE_A = 4001408,
    NPC_REFUGEE_B = 4001409,
    NPC_REFUGEE_C = 4001410,
    NPC_DEZCO_SCENE = 4001411,
    NPC_NALA_SCENE = 4001412,
    NPC_SCENE = 4001413,
    NPC_RAIDER = 4001414,
    NPC_HEXER = 4001415,
    NPC_SKITTERER = 4001416,
    CREDIT_TREATED = 4001450,
    CREDIT_STEW = 4001451,
    CREDIT_LOOKOUT_A = 4001452,
    CREDIT_LOOKOUT_B = 4001453,
    CREDIT_LOOKOUT_C = 4001454,
    CREDIT_REMEDY = 4001455,
    CREDIT_AGENDA = 4001456,
    CREDIT_LIFE = 4001457,
    CREDIT_VIGIL = 4001458,
    CREDIT_REFUGEE_A = 4001459,
    CREDIT_REFUGEE_B = 4001460,
    CREDIT_REFUGEE_C = 4001461,
    CREDIT_PROMISE = 4001462,
    GO_TRACK = 4001500,
    GO_TENT = 4001501,
    GO_HEARTH = 4001502,
    GO_LOOKOUT_A = 4001503,
    GO_LOOKOUT_B = 4001504,
    GO_LOOKOUT_C = 4001505,
    GO_HERB = 4001506,
    GO_ORDERS = 4001507,
    GO_DEVICE = 4001508,
    GO_POOL = 4001509,
    GO_MEMORIAL = 4001510,
    GO_SUPPLY_A = 4001511,
    GO_SUPPLY_B = 4001512,
    GO_SUPPLY_C = 4001513,
    GO_COT_A = 4001514,
    GO_COT_B = 4001515,
    GO_RUINED_TENT = 4001516,
    GO_VILLAGE_SIGN = 4001517,
    ITEM_ORDERS = 900300,
    ITEM_ANTIDOTE = 900301,
    ITEM_MEAT = 900302,
    ITEM_INSIGNIA = 900303,
    ITEM_LEAVES = 900304,
    ITEM_SAMPLE = 900305,
    ITEM_KEEPSAKE = 900306,
    ITEM_FOOD = 900307,
    ITEM_LETTER = 900308,
    ITEM_MIGHT = 900309,
    ITEM_PRECISION = 900310,
    ITEM_SORCERY = 900311,
    ITEM_RESTORATION = 900312,
    ITEM_GUARDING = 900313,
    ITEM_BALANCE = 900314,
    NPC_DEZCO = 4001205,
    QUEST_C02_END = 900222,
    SPELL_ANTIDOTE_TARGET = 34665,
    SPELL_HEAL_VISUAL = 635,
    SPELL_STRIKE = 11976,
    SPELL_HEX = 11641,
    SPELL_HEX_BOLT = 20816,
    CREDIT_DEVICE = 4001463,
    TEXT_DEZCO = 4001464,
};

struct Point
{
    float x;
    float y;
    float z;
    float orientation;
};

namespace Locations
{
inline constexpr Point dezco = {-3970.0000f, -3350.0000f, 39.3928f, 3.1400f};
inline constexpr Point kang = {-3955.0000f, -3348.0000f, 39.2671f, 3.1400f};
inline constexpr Point kor = {-3970.0000f, -3328.0000f, 37.1837f, 3.1400f};
inline constexpr Point nala = {-3982.0000f, -3358.0000f, 40.2625f, 3.1400f};
inline constexpr Point tent = {-3986.0000f, -3367.0000f, 40.6291f, 3.1400f};
inline constexpr Point leza = {-3988.0000f, -3370.0000f, 40.7525f, 3.1400f};
inline constexpr Point dezco_scene = {-3980.0000f, -3368.0000f, 40.2017f, 3.1400f};
inline constexpr Point nala_scene = {-3987.0000f, -3372.0000f, 40.9401f, 3.1400f};
inline constexpr Point cot_a = {-3990.0000f, -3358.0000f, 40.0327f, 3.1400f};
inline constexpr Point cot_b = {-3993.0000f, -3358.0000f, 39.5845f, 3.1400f};
inline constexpr Point redhorn = {-3990.0000f, -3358.0000f, 40.0327f, 3.1400f};
inline constexpr Point cloudhoof = {-3993.0000f, -3358.0000f, 39.5845f, 3.1400f};
inline constexpr Point hearth = {-3947.0000f, -3357.0000f, 38.1619f, 3.1400f};
inline constexpr Point memorial = {-4010.0000f, -3340.0000f, 37.1098f, 3.1400f};
inline constexpr Point chezin = {-3785.0000f, -3488.0000f, 30.9048f, 3.1400f};
inline constexpr Point track = {-3780.0000f, -3484.0000f, 30.6635f, 3.1400f};
inline constexpr Point ruined_tent = {-3792.0000f, -3486.9400f, 31.2307f, 3.1400f};
inline constexpr Point lookout_a = {-3813.9200f, -3509.8400f, 30.1454f, 3.1400f};
inline constexpr Point lookout_b = {-3890.0000f, -3560.0000f, 37.4181f, 3.1400f};
inline constexpr Point lookout_c = {-3999.6300f, -3594.6100f, 30.7692f, 3.1400f};
inline constexpr Point orders = {-3940.0000f, -3620.0000f, 35.3829f, 3.1400f};
inline constexpr Point device = {-3946.0000f, -3620.0000f, 35.8394f, 3.1400f};
inline constexpr Point pool = {-4010.0000f, -3660.0000f, 43.2612f, 3.1400f};
inline constexpr Point refugee_a = {-3952.0000f, -3320.0000f, 37.4515f, 3.1400f};
inline constexpr Point refugee_b = {-3917.0000f, -3360.0000f, 34.7054f, 3.1400f};
inline constexpr Point refugee_c = {-3965.0000f, -3390.0000f, 34.7951f, 3.1400f};
inline constexpr Point supply_a = {-3950.0000f, -3320.0000f, 37.8024f, 3.1400f};
inline constexpr Point supply_b = {-3915.0000f, -3360.0000f, 34.4604f, 3.1400f};
inline constexpr Point supply_c = {-3963.0000f, -3390.0000f, 34.4951f, 3.1400f};
inline constexpr Point mei = {-4535.0000f, -3235.0000f, 31.0057f, 3.1400f};
inline constexpr Point village_sign = {-4533.0000f, -3233.0000f, 30.0854f, 3.1400f};
inline constexpr Point raider_0 = {-3817.0000f, -3510.0000f, 31.6450f, 3.1400f};
inline constexpr Point raider_1 = {-3807.0000f, -3520.0000f, 31.1908f, 3.1400f};
inline constexpr Point raider_2 = {-3877.0000f, -3554.0000f, 39.8758f, 3.1400f};
inline constexpr Point raider_3 = {-3898.0000f, -3550.0000f, 37.5560f, 3.1400f};
inline constexpr Point raider_4 = {-3986.0000f, -3592.0000f, 35.1444f, 3.1400f};
inline constexpr Point raider_5 = {-4007.0000f, -3586.0000f, 30.9076f, 3.1400f};
inline constexpr Point raider_6 = {-3913.2700f, -3606.5800f, 30.7396f, 3.1400f};
inline constexpr Point raider_7 = {-3888.2300f, -3596.1500f, 30.8409f, 3.1400f};
inline constexpr Point hexer_0 = {-3904.8000f, -3586.9300f, 30.7318f, 3.1400f};
inline constexpr Point hexer_1 = {-3860.0000f, -3615.0000f, 33.6543f, 3.1400f};
inline constexpr Point hexer_2 = {-4003.7200f, -3607.2700f, 30.8550f, 3.1400f};
inline constexpr Point skitterer_0 = {-3925.0000f, -3460.0000f, 30.7283f, 3.1400f};
inline constexpr Point skitterer_1 = {-3958.4000f, -3466.6700f, 30.3586f, 3.1400f};
inline constexpr Point skitterer_2 = {-3930.1300f, -3494.9300f, 30.8673f, 3.1400f};
inline constexpr Point skitterer_3 = {-3966.9200f, -3498.0500f, 30.6955f, 3.1400f};
inline constexpr Point skitterer_4 = {-4005.0000f, -3480.0000f, 30.5893f, 3.1400f};
inline constexpr Point skitterer_5 = {-4016.0000f, -3458.0000f, 32.2797f, 3.1400f};
inline constexpr Point skitterer_6 = {-4004.0000f, -3428.0000f, 44.8079f, 3.1400f};
inline constexpr Point skitterer_7 = {-3941.7400f, -3439.9600f, 30.8324f, 3.1400f};
inline constexpr Point herb_0 = {-3865.4200f, -3471.6100f, 30.7510f, 3.1400f};
inline constexpr Point herb_1 = {-3869.3300f, -3490.6700f, 30.8590f, 3.1400f};
inline constexpr Point herb_2 = {-3898.0000f, -3472.0000f, 31.8962f, 3.1400f};
inline constexpr Point herb_3 = {-3920.0000f, -3520.0000f, 36.2081f, 3.1400f};
inline constexpr Point herb_4 = {-3939.4700f, -3548.0000f, 41.1224f, 3.1400f};
inline constexpr Point herb_5 = {-3957.0000f, -3558.0000f, 39.2579f, 3.1400f};
inline constexpr Point herb_6 = {-3975.0000f, -3540.0000f, 40.9579f, 3.1400f};
inline constexpr Point herb_7 = {-4002.5400f, -3530.1200f, 30.7372f, 3.1400f};
inline constexpr Point herb_8 = {-4020.9800f, -3554.9800f, 30.9206f, 3.1400f};
inline constexpr Point herb_9 = {-4018.0000f, -3565.0000f, 31.9401f, 3.1400f};
inline constexpr Point herb_10 = {-4025.0000f, -3505.0000f, 35.6623f, 3.1400f};
inline constexpr Point herb_11 = {-3870.0000f, -3536.0000f, 38.8539f, 3.1400f};
}

inline constexpr std::array<std::uint32_t, 3> LookoutCredits =
{
    CREDIT_LOOKOUT_A, CREDIT_LOOKOUT_B, CREDIT_LOOKOUT_C
};

inline constexpr std::array<std::uint32_t, 3> LookoutEntries =
{
    GO_LOOKOUT_A, GO_LOOKOUT_B, GO_LOOKOUT_C
};

inline constexpr std::array<std::uint32_t, 3> RefugeeCredits =
{
    CREDIT_REFUGEE_A, CREDIT_REFUGEE_B, CREDIT_REFUGEE_C
};

inline constexpr std::array<std::uint32_t, 3> RefugeeEntries =
{
    NPC_REFUGEE_A, NPC_REFUGEE_B, NPC_REFUGEE_C
};

inline constexpr std::array<std::uint32_t, 3> SupplyEntries =
{
    GO_SUPPLY_A, GO_SUPPLY_B, GO_SUPPLY_C
};

inline constexpr std::array<std::uint32_t, 6> PersonalEntries =
{
    NPC_LEZA, NPC_REDHORN, NPC_CLOUDHOOF, NPC_DEZCO_SCENE, NPC_NALA_SCENE, NPC_SCENE
};

}

#endif
