// Generated by tools/generate_broken_seal_chapter4.py. Do not edit.
#ifndef MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER4_DATA_H
#define MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER4_DATA_H

#include <array>
#include <cstdint>

namespace BrokenSeal::Chapter4
{
enum Id : std::uint32_t
{
    QUEST_INTRO = 900400,
    QUEST_FOOD = 900401,
    QUEST_FIND = 900402,
    QUEST_CHEER = 900403,
    QUEST_MEDICINE = 900404,
    QUEST_TEST = 900405,
    QUEST_TREAT = 900406,
    QUEST_WARD = 900407,
    QUEST_DESPAIR = 900408,
    QUEST_WORK = 900409,
    QUEST_PLEDGE = 900410,
    QUEST_LETTER = 900411,
    NPC_KEN = 4001600,
    NPC_YIMO = 4001601,
    NPC_KANG = 4001602,
    NPC_MARUUT = 4001603,
    NPC_IAIN = 4001604,
    NPC_VILLAGER_0 = 4001605,
    NPC_VILLAGER_1 = 4001606,
    NPC_VILLAGER_2 = 4001607,
    NPC_VILLAGER_3 = 4001608,
    NPC_VILLAGER_4 = 4001609,
    NPC_VILLAGER_5 = 4001610,
    NPC_VILLAGER_6 = 4001611,
    NPC_VILLAGER_7 = 4001612,
    NPC_YIMO_SCENE = 4001613,
    NPC_KEN_SCENE = 4001614,
    NPC_SCENE = 4001615,
    NPC_STALKER = 4001616,
    NPC_ESSENCE = 4001617,
    NPC_QUINTESSENCE = 4001618,
    CREDIT_INSPECT = 4001650,
    CREDIT_QUESTION_A = 4001651,
    CREDIT_QUESTION_B = 4001652,
    CREDIT_QUESTION_C = 4001653,
    CREDIT_ESCORT = 4001654,
    CREDIT_CHEER = 4001655,
    CREDIT_HERBS = 4001656,
    CREDIT_TEST_A = 4001657,
    CREDIT_TEST_B = 4001658,
    CREDIT_TEST_C = 4001659,
    CREDIT_TREATED = 4001660,
    CREDIT_WELL = 4001661,
    CREDIT_ESSENCES = 4001662,
    CREDIT_YIMO = 4001663,
    CREDIT_BOSS = 4001664,
    CREDIT_HEARTH_A = 4001665,
    CREDIT_HEARTH_B = 4001666,
    CREDIT_HEARTH_C = 4001667,
    CREDIT_SERVICES = 4001668,
    CREDIT_LIAISON = 4001669,
    TEXT_MEI = 4001670,
    GO_TRAIL = 4001700,
    GO_HERB = 4001701,
    GO_WELL = 4001702,
    GO_WARD = 4001703,
    GO_SUPPLY = 4001704,
    GO_LOST_SUPPLY = 4001705,
    GO_HEARTH_A = 4001706,
    GO_HEARTH_B = 4001707,
    GO_HEARTH_C = 4001708,
    ITEM_WARD = 900400,
    ITEM_FOOD = 900401,
    ITEM_MEDICINE = 900402,
    ITEM_MASK = 900403,
    ITEM_RESIDUE = 900404,
    ITEM_PLEDGE = 900405,
    ITEM_LETTER = 900406,
    ITEM_MIGHT = 900410,
    ITEM_PRECISION = 900411,
    ITEM_SORCERY = 900412,
    ITEM_RESTORATION = 900413,
    ITEM_GUARDING = 900414,
    ITEM_BALANCE = 900415,
    NPC_MEI = 4001405,
    QUEST_C03_END = 900311,
    SPELL_MASK_TARGET = 34665,
    SPELL_SHADOW_BOLT = 20816,
    SPELL_HEAL_VISUAL = 635,
    SPELL_STRIKE = 11976,
    NPC_HEARTH_FLAME = 4001619,
    TEXT_RECOVERED = 4001671,
    SPELL_POISON = 744,
    NPC_WEEPING_HORROR = 4001620,
    NPC_PANTHER = 4001621,
    GO_HONEYCOMB = 4001709,
    GO_MUDFISH = 4001710,
    GO_PIGMENT = 4001711,
    ITEM_SALTY_CORE = 900416,
    ITEM_MUDFISH = 900417,
    ITEM_HONEYCOMB = 900418,
    ITEM_FANGS = 900419,
    ITEM_PIGMENT = 900420,
};

struct Point
{
    float x;
    float y;
    float z;
    float orientation;
};

namespace Locations
{
inline constexpr Point mei = {-4535.0000f, -3235.0000f, 31.0057f, 3.1400f};
inline constexpr Point ken = {-4580.0000f, -3250.0000f, 33.4200f, 3.1400f};
inline constexpr Point yimo = {-4588.0000f, -3252.0000f, 32.2169f, 3.1400f};
inline constexpr Point kang = {-4575.0000f, -3255.0000f, 32.5780f, 3.1400f};
inline constexpr Point maruut = {-4582.0000f, -3260.0000f, 32.2219f, 3.1400f};
inline constexpr Point trail = {-4515.0000f, -3300.0000f, 31.4065f, 3.1400f};
inline constexpr Point escort_0 = {-4512.0000f, -3300.0000f, 30.9483f, 3.1400f};
inline constexpr Point escort_1 = {-4525.0000f, -3290.0000f, 34.8251f, 3.1400f};
inline constexpr Point escort_2 = {-4545.0000f, -3280.0000f, 35.8583f, 3.1400f};
inline constexpr Point escort_3 = {-4560.0000f, -3270.0000f, 36.6152f, 3.1400f};
inline constexpr Point escort_4 = {-4570.0000f, -3260.0000f, 35.0564f, 3.1400f};
inline constexpr Point stalker = {-4521.0000f, -3284.0000f, 37.3333f, 3.1400f};
inline constexpr Point well = {-4532.0000f, -3324.0000f, 34.5583f, 3.1400f};
inline constexpr Point ward = {-4535.0000f, -3326.0000f, 35.4566f, 3.1400f};
inline constexpr Point boss = {-4540.0000f, -3316.8000f, 36.3334f, 3.1400f};
inline constexpr Point ken_scene = {-4528.0000f, -3320.0000f, 33.4474f, 3.1400f};
inline constexpr Point yimo_scene = {-4527.0000f, -3319.0000f, 32.7556f, 3.1400f};
inline constexpr Point supply = {-4565.0000f, -3258.0000f, 34.1955f, 3.1400f};
inline constexpr Point lost_supply = {-4516.5700f, -3301.5700f, 30.7761f, 3.1400f};
inline constexpr Point hearth_a = {-4590.0000f, -3260.0000f, 30.6445f, 3.1400f};
inline constexpr Point hearth_b = {-4565.0000f, -3245.0000f, 31.7819f, 3.1400f};
inline constexpr Point hearth_c = {-4575.0000f, -3259.0000f, 33.2115f, 3.1400f};
inline constexpr Point villager_0 = {-4586.0000f, -3240.0000f, 35.0152f, 3.1400f};
inline constexpr Point villager_1 = {-4588.0000f, -3246.0000f, 33.4952f, 3.1400f};
inline constexpr Point villager_2 = {-4590.0000f, -3250.0000f, 32.4036f, 3.1400f};
inline constexpr Point villager_3 = {-4590.0000f, -3256.0000f, 31.0324f, 3.1400f};
inline constexpr Point villager_4 = {-4586.0000f, -3264.0000f, 31.4333f, 3.1400f};
inline constexpr Point villager_5 = {-4575.0000f, -3264.0000f, 35.1583f, 3.1400f};
inline constexpr Point villager_6 = {-4568.0000f, -3255.0000f, 33.0767f, 3.1400f};
inline constexpr Point villager_7 = {-4568.0000f, -3242.0000f, 34.0830f, 3.1400f};
inline constexpr Point essence_0 = {-4511.5100f, -3288.8200f, 31.2000f, 3.1400f};
inline constexpr Point essence_1 = {-4520.3800f, -3309.9200f, 30.9333f, 3.1400f};
inline constexpr Point essence_2 = {-4525.0000f, -3325.0000f, 33.1680f, 3.1400f};
inline constexpr Point essence_3 = {-4535.0000f, -3335.0000f, 37.4952f, 3.1400f};
inline constexpr Point essence_4 = {-4550.0000f, -3335.0000f, 40.2314f, 3.1400f};
inline constexpr Point essence_5 = {-4560.0000f, -3325.0000f, 40.0296f, 3.1400f};
inline constexpr Point essence_6 = {-4560.0000f, -3310.0000f, 37.2032f, 3.1400f};
inline constexpr Point essence_7 = {-4550.0000f, -3300.0000f, 32.5238f, 3.1400f};
inline constexpr Point herb_0 = {-4570.0000f, -3280.0000f, 35.2580f, 3.1400f};
inline constexpr Point herb_1 = {-4578.0000f, -3280.0000f, 35.7328f, 3.1400f};
inline constexpr Point herb_2 = {-4586.0000f, -3280.0000f, 36.6777f, 3.1400f};
inline constexpr Point herb_3 = {-4594.0000f, -3280.0000f, 36.6221f, 3.1400f};
inline constexpr Point herb_4 = {-4595.0000f, -3290.0000f, 37.9738f, 3.1400f};
inline constexpr Point herb_5 = {-4585.0000f, -3290.0000f, 35.8287f, 3.1400f};
inline constexpr Point herb_6 = {-4574.0000f, -3290.0000f, 32.8500f, 3.1400f};
inline constexpr Point herb_7 = {-4565.0000f, -3290.0000f, 31.5415f, 3.1400f};
inline constexpr Point iain = {80.0000f, -2050.0000f, 117.2310f, 3.1400f};
inline constexpr Point hinterlands_road = {-100.0000f, -2200.0000f, 227.2290f, 3.1400f};
inline constexpr Point mei_approach = {-4559.0000f, -3238.0000f, 32.1796f, 3.1400f};
inline constexpr Point honey_0 = {-4564.0000f, -3291.0000f, 30.5657f, 3.1400f};
inline constexpr Point honey_1 = {-4621.0000f, -3280.0000f, 39.9388f, 3.1400f};
inline constexpr Point fish_0 = {-4610.0000f, -3208.0000f, 34.9247f, 3.1400f};
inline constexpr Point pigment = {-4475.0000f, -3280.0000f, 35.2906f, 3.1400f};
inline constexpr Point horror_0 = {-4629.0000f, -3337.0000f, 29.8381f, 3.1400f};
inline constexpr Point horror_1 = {-4597.0000f, -3333.0000f, 36.4756f, 3.1400f};
inline constexpr Point horror_2 = {-4607.0000f, -3365.0000f, 37.3277f, 3.1400f};
inline constexpr Point horror_3 = {-4638.0000f, -3362.0000f, 30.1221f, 3.1400f};
inline constexpr Point panther_0 = {-4472.0000f, -3287.0000f, 37.6517f, 3.1400f};
inline constexpr Point panther_1 = {-4496.0000f, -3296.0000f, 32.4287f, 3.1400f};
inline constexpr Point panther_2 = {-4518.0000f, -3285.0000f, 36.1146f, 3.1400f};
inline constexpr Point panther_3 = {-4510.0000f, -3315.0000f, 29.6488f, 3.1400f};
inline constexpr Point panther_4 = {-4470.0000f, -3317.0000f, 39.0547f, 3.1400f};
inline constexpr Point panther_5 = {-4485.0000f, -3334.0000f, 32.5304f, 3.1400f};
}

inline constexpr std::array<std::uint32_t, 8> VillagerEntries =
{
    NPC_VILLAGER_0, NPC_VILLAGER_1, NPC_VILLAGER_2, NPC_VILLAGER_3, NPC_VILLAGER_4, NPC_VILLAGER_5, NPC_VILLAGER_6, NPC_VILLAGER_7
};

inline constexpr std::array<std::uint32_t, 3> QuestionCredits =
{
    CREDIT_QUESTION_A, CREDIT_QUESTION_B, CREDIT_QUESTION_C
};

inline constexpr std::array<std::uint32_t, 3> TestCredits =
{
    CREDIT_TEST_A, CREDIT_TEST_B, CREDIT_TEST_C
};

inline constexpr std::array<std::uint32_t, 3> HearthCredits =
{
    CREDIT_HEARTH_A, CREDIT_HEARTH_B, CREDIT_HEARTH_C
};

inline constexpr std::array<std::uint32_t, 3> HearthEntries =
{
    GO_HEARTH_A, GO_HEARTH_B, GO_HEARTH_C
};

inline constexpr std::array<std::uint32_t, 8> PersonalEntries =
{
    NPC_YIMO, NPC_YIMO_SCENE, NPC_KEN_SCENE, NPC_SCENE, NPC_STALKER, NPC_ESSENCE, NPC_QUINTESSENCE, NPC_HEARTH_FLAME
};

inline constexpr std::array<char const*, 8> VillagerNames =
{
    "Village Provisioner", "Village Herbalist", "Village Toolkeeper", "Village Cook", "Village Laborer", "Village Wardkeeper", "Village Tailor", "Village Scout"
};

inline constexpr std::array<Point, 5> EscortPath =
{{
    Locations::escort_0,
    Locations::escort_1,
    Locations::escort_2,
    Locations::escort_3,
    Locations::escort_4,
}};

inline constexpr std::array<Point, 8> VillagerPoints =
{{
    Locations::villager_0,
    Locations::villager_1,
    Locations::villager_2,
    Locations::villager_3,
    Locations::villager_4,
    Locations::villager_5,
    Locations::villager_6,
    Locations::villager_7,
}};

inline constexpr std::array<Point, 8> EssencePoints =
{{
    Locations::essence_0,
    Locations::essence_1,
    Locations::essence_2,
    Locations::essence_3,
    Locations::essence_4,
    Locations::essence_5,
    Locations::essence_6,
    Locations::essence_7,
}};

}

#endif
