// Generated by tools/generate_broken_seal_chapter1.py. Do not edit.
#ifndef MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER1_DATA_H
#define MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER1_DATA_H

#include <array>
#include <cstdint>

namespace BrokenSeal::Chapter1
{
enum Id : std::uint32_t
{
    QUEST_COMMISSION_A = 900100,
    QUEST_COMMISSION_H = 900101,
    QUEST_WAGON = 900102,
    QUEST_TRAIL = 900103,
    QUEST_RESCUE = 900104,
    QUEST_WARDS = 900105,
    QUEST_COMPARE = 900106,
    QUEST_COMMANDER = 900107,
    QUEST_RECRUIT = 900108,
    NPC_MARUUT = 4001000,
    NPC_ORTELL = 4001001,
    NPC_JAROD = 4001002,
    NPC_RECRUIT = 4001003,
    NPC_CAPTIVE_A = 4001004,
    NPC_SCOUT = 4001005,
    NPC_COURIER_A = 4001006,
    NPC_COURIER_H = 4001007,
    NPC_CAPTIVE_B = 4001008,
    NPC_CAPTIVE_C = 4001009,
    NPC_CULT_SCOUT = 4001010,
    NPC_CULT_GUARD = 4001011,
    NPC_EARTH = 4001012,
    NPC_SCENE = 4001013,
    CREDIT_TRAIL_A = 4001050,
    CREDIT_TRAIL_B = 4001051,
    CREDIT_TRAIL_C = 4001052,
    CREDIT_CAPTIVE_A = 4001053,
    CREDIT_CAPTIVE_B = 4001054,
    CREDIT_CAPTIVE_C = 4001055,
    CREDIT_WARD_A = 4001056,
    CREDIT_WARD_B = 4001057,
    CREDIT_WARD_C = 4001058,
    CREDIT_COMPARE = 4001059,
    CREDIT_COMMANDER = 4001060,
    CREDIT_RECRUIT = 4001061,
    CREDIT_SIGNAL = 4001062,
    GO_WAGON = 4001100,
    GO_TRAIL_A = 4001101,
    GO_TRAIL_B = 4001102,
    GO_TRAIL_C = 4001103,
    GO_CAGE_A = 4001104,
    GO_CAGE_B = 4001105,
    GO_CAGE_C = 4001106,
    GO_WARD_A = 4001107,
    GO_WARD_B = 4001108,
    GO_WARD_C = 4001109,
    GO_COVER = 4001110,
    GO_DEAD_DROP = 4001111,
    GO_ALTAR = 4001112,
    GO_RALLY = 4001113,
    ITEM_INVITATION = 900100,
    ITEM_LOG = 900101,
    ITEM_ORDERS = 900102,
    ITEM_RUBBING = 900103,
    ITEM_TRACING_KIT = 900104,
    ITEM_MIGHT = 900110,
    ITEM_PRECISION = 900111,
    ITEM_SORCERY = 900112,
    ITEM_RESTORATION = 900113,
    ITEM_GUARDING = 900114,
    ITEM_BALANCE = 900115,
    SPELL_OPENING = 3365,
    SPELL_SHOOT = 6660,
    SPELL_STRIKE = 11976,
    SPELL_THUNDERCLAP = 8078,
    TEXT_MARUUT = 4001000,
    TEXT_ORTELL = 4001001,
    TEXT_SCOUT = 4001005,
    TEXT_COURIER_A = 4001006,
    TEXT_COURIER_H = 4001007,
};

struct Point
{
    float x;
    float y;
    float z;
    float orientation;
};

inline constexpr std::uint32_t MapId = 1;
inline constexpr std::size_t DistinctCount = 3;

inline constexpr std::array<std::uint32_t, 3> TrailCredits =
{
    CREDIT_TRAIL_A, CREDIT_TRAIL_B, CREDIT_TRAIL_C
};

inline constexpr std::array<std::uint32_t, 3> WardCredits =
{
    CREDIT_WARD_A, CREDIT_WARD_B, CREDIT_WARD_C
};

inline constexpr std::array<std::uint32_t, 3> CaptiveCredits =
{
    CREDIT_CAPTIVE_A, CREDIT_CAPTIVE_B, CREDIT_CAPTIVE_C
};

inline constexpr std::array<std::uint32_t, 3> CaptiveEntries =
{
    NPC_CAPTIVE_A, NPC_CAPTIVE_B, NPC_CAPTIVE_C
};

inline constexpr std::array<std::uint32_t, 3> WardEntries =
{
    GO_WARD_A, GO_WARD_B, GO_WARD_C
};

inline constexpr std::array<std::uint32_t, 3> TrailEntries =
{
    GO_TRAIL_A, GO_TRAIL_B, GO_TRAIL_C
};

inline constexpr std::array<Point, 3> CaptiveStarts =
{{
    {882.0000f, 1680.0000f, -19.9206f, 3.1400f},
    {886.0000f, 1683.0000f, -19.8249f, 3.1400f},
    {890.0000f, 1684.0000f, -19.7682f, 3.1400f},
}};

inline constexpr std::array<Point, 4> RecruitPatrol =
{{
    {891.0000f, 1678.0000f, -19.8282f, 3.1400f},
    {892.0000f, 1682.0000f, -19.7870f, 3.1400f},
    {896.0000f, 1681.0000f, -19.6735f, 3.1400f},
    {898.0000f, 1678.0000f, -19.6566f, 3.1400f},
}};

inline constexpr Point Refuge = {1098.0000f, 1540.0000f, 26.3195f, 3.1400f};
}

#endif
