// Generated by tools/generate_broken_seal_chapter2.py. Do not edit.
#ifndef MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER2_DATA_H
#define MOD_CUSTOMNPCS_BROKEN_SEAL_CHAPTER2_DATA_H

#include <array>
#include <cstdint>

namespace BrokenSeal::Chapter2
{
enum Id : std::uint32_t
{
    QUEST_SIGNED = 900200,
    QUEST_IDENTITY = 900201,
    QUEST_FIRE = 900202,
    QUEST_BLOOM = 900203,
    QUEST_WASTE = 900204,
    QUEST_TRAINING = 900205,
    QUEST_LABOR = 900206,
    QUEST_AGILITY = 900207,
    QUEST_MENTAL = 900208,
    QUEST_MERCY = 900209,
    QUEST_DOG = 900210,
    QUEST_COLLAR = 900211,
    QUEST_GRUDGE = 900212,
    QUEST_INTELLIGENCE = 900213,
    QUEST_DISCORD = 900214,
    QUEST_GREATER = 900215,
    QUEST_TERRITORY = 900216,
    QUEST_WRITING = 900217,
    QUEST_HEAD = 900218,
    QUEST_SPEECH = 900219,
    QUEST_RIOT = 900220,
    QUEST_BUYERS = 900221,
    QUEST_LETTER = 900222,
    NPC_CONDENNA = 4001200,
    NPC_CARGALL = 4001201,
    NPC_MYLVA = 4001202,
    NPC_DEVORAN = 4001203,
    NPC_JAROD_FREE = 4001204,
    NPC_DEZCO = 4001205,
    NPC_RECRUIT = 4001206,
    NPC_SUPPLICANT_A = 4001207,
    NPC_SUPPLICANT_B = 4001208,
    NPC_SUPPLICANT_C = 4001209,
    NPC_HOUND = 4001210,
    NPC_ORB = 4001211,
    NPC_CROWD = 4001212,
    NPC_OGRE = 4001213,
    NPC_KARRGONN = 4001214,
    NPC_AZENNIOS = 4001215,
    NPC_GARNOTH = 4001216,
    NPC_GROMMKO = 4001217,
    NPC_OKROG = 4001218,
    NPC_RESTRAINT = 4001219,
    NPC_ENFORCER = 4001220,
    NPC_SCENE = 4001221,
    NPC_FIRE = 4001222,
    NPC_SMOLDEROS = 4001223,
    NPC_MATRIARCH = 4001224,
    NPC_FAILED = 4001225,
    NPC_HORRORGUARD = 4001226,
    NPC_GUARD = 4001227,
    NPC_SCOUT = 4001228,
    CREDIT_KNOCKOUT = 4001250,
    CREDIT_IDENTITY = 4001251,
    CREDIT_FIRE = 4001252,
    CREDIT_SUPPLICANT_A = 4001253,
    CREDIT_SUPPLICANT_B = 4001254,
    CREDIT_SUPPLICANT_C = 4001255,
    CREDIT_MYLVA = 4001256,
    CREDIT_DEVORAN = 4001257,
    CREDIT_LOADS = 4001258,
    CREDIT_COURSE = 4001259,
    CREDIT_MENTAL = 4001260,
    CREDIT_MERCY = 4001261,
    CREDIT_DOG_A = 4001262,
    CREDIT_DOG_B = 4001263,
    CREDIT_DOG_C = 4001264,
    CREDIT_GRUDGE = 4001265,
    CREDIT_DROP = 4001266,
    CREDIT_DISCORD = 4001267,
    CREDIT_GARNOTH = 4001268,
    CREDIT_TERRITORY = 4001269,
    CREDIT_OKROG = 4001270,
    CREDIT_HEAD = 4001271,
    CREDIT_SPEECH = 4001272,
    CREDIT_ALTAR = 4001273,
    CREDIT_RIOT = 4001274,
    GO_RENDEZVOUS = 4001300,
    GO_FLOWER = 4001301,
    GO_STONES = 4001302,
    GO_DELIVERY = 4001303,
    GO_COURSE_START = 4001304,
    GO_CHECK_A = 4001305,
    GO_CHECK_B = 4001306,
    GO_CHECK_C = 4001307,
    GO_CHECK_D = 4001308,
    GO_DOG_A = 4001309,
    GO_DOG_B = 4001310,
    GO_DOG_C = 4001311,
    GO_COMMUNIQUE = 4001312,
    GO_PLANS = 4001313,
    GO_DROP = 4001314,
    GO_DISCORD = 4001315,
    GO_GARNOTH = 4001316,
    GO_OKROG = 4001317,
    GO_PODIUM = 4001318,
    GO_PRISON = 4001319,
    GO_BUYERS = 4001320,
    ITEM_BLACKJACK = 900200,
    ITEM_PAPERS = 900201,
    ITEM_IDENTITY = 900202,
    ITEM_BLOSSOMS = 900203,
    ITEM_GEM = 900204,
    ITEM_LEASH = 900205,
    ITEM_COLLAR = 900206,
    ITEM_HIDE = 900207,
    ITEM_COMMUNIQUE = 900208,
    ITEM_PLANS = 900209,
    ITEM_TALISMAN = 900210,
    ITEM_ORB = 900211,
    ITEM_NOTES = 900212,
    ITEM_KEY = 900213,
    ITEM_LEDGER = 900214,
    ITEM_LETTER = 900215,
    ITEM_MIGHT = 900216,
    ITEM_PRECISION = 900217,
    ITEM_SORCERY = 900218,
    ITEM_RESTORATION = 900219,
    ITEM_GUARDING = 900220,
    ITEM_BALANCE = 900221,
    NPC_ORTELL = 4001001,
    NPC_PRISONER = 4001002,
    QUEST_C01_END = 900107,
    SPELL_DISGUISE = 4329,
    SPELL_FIRE_FORM = 4933,
    SPELL_BLACKJACK = 41358,
    SPELL_OPENING = 3365,
    SPELL_STRIKE = 11976,
    SPELL_FIREBALL = 20823,
    SPELL_BURNING = 42726,
    NPC_BUTCHER = 4001229,
    SPELL_BLACKJACK_TARGET = 39865,
    SPELL_GEM_TARGET = 34665,
    GO_TERRITORY = 4001321,
    SPELL_SHOOT = 6660,
    SPELL_SHADOW_BOLT = 20816,
    SPELL_POISON = 744,
    NPC_SUPPLICANT_D = 4001230,
    NPC_BASILISK = 4001231,
    NPC_ORTELL_SCENE = 4001232,
    NPC_BLAZING_TRAINER = 4001233,
    CREDIT_SUPPLICANT_D = 4001275,
    GO_HIDEOUT = 4001322,
    ITEM_PICK = 900222,
    ITEM_MEAT = 900223,
    ITEM_ASCENDANT_STRIKE = 900224,
    ITEM_FLAME_SHIELD = 900225,
    SPELL_FLAME_SHIELD = 2947,
};

inline constexpr std::uint32_t FireDisplay = 2172;

struct Point
{
    float x;
    float y;
    float z;
    float orientation;
};

namespace Locations
{
inline constexpr Point condenna = {635.0000f, 1624.0000f, -17.6592f, 3.1400f};
inline constexpr Point cargall = {636.0000f, 1632.0000f, -17.6717f, 3.1400f};
inline constexpr Point mylva = {644.0000f, 1620.0000f, -18.0993f, 3.1400f};
inline constexpr Point devoran = {646.0000f, 1630.0000f, -17.7682f, 3.1400f};
inline constexpr Point ortell = {1100.0000f, 1540.0000f, 26.6937f, 3.1400f};
inline constexpr Point prison = {895.0000f, 1682.0000f, -19.5787f, 3.1400f};
inline constexpr Point refuge = {1098.0000f, 1540.0000f, 26.3195f, 3.1400f};
inline constexpr Point rendezvous = {869.0000f, 1666.0000f, -19.8930f, 3.1400f};
inline constexpr Point recruit_start = {950.0000f, 1600.0000f, -12.0997f, 3.1400f};
inline constexpr Point recruit_hide = {965.0000f, 1577.0000f, -7.8366f, 3.1400f};
inline constexpr Point supplicant_a = {636.0000f, 1635.0000f, -17.6990f, 3.1400f};
inline constexpr Point supplicant_b = {640.0000f, 1636.0000f, -17.6474f, 3.1400f};
inline constexpr Point supplicant_c = {643.0000f, 1635.0000f, -17.5658f, 3.1400f};
inline constexpr Point stones = {636.0000f, 1617.0000f, -16.2885f, 3.1400f};
inline constexpr Point delivery = {649.0000f, 1626.0000f, -18.2885f, 3.1400f};
inline constexpr Point course_start = {650.0000f, 1637.0000f, -17.6398f, 3.1400f};
inline constexpr Point check_a = {657.0000f, 1637.0000f, -18.5702f, 3.1400f};
inline constexpr Point check_b = {657.0000f, 1616.0000f, -19.2652f, 3.1400f};
inline constexpr Point check_c = {625.0000f, 1616.0000f, -16.0206f, 3.1400f};
inline constexpr Point check_d = {625.0000f, 1635.0000f, -16.6342f, 3.1400f};
inline constexpr Point dog_a = {647.0000f, 1636.0000f, -17.6552f, 3.1400f};
inline constexpr Point dog_b = {640.0000f, 1640.0000f, -17.8000f, 3.1400f};
inline constexpr Point dog_c = {628.0000f, 1638.0000f, -17.5394f, 3.1400f};
inline constexpr Point hound = {645.0000f, 1632.0000f, -17.6088f, 3.1400f};
inline constexpr Point communique = {632.0000f, 1626.0000f, -17.5595f, 3.1400f};
inline constexpr Point plans = {895.0000f, 1687.0000f, -19.3277f, 3.1400f};
inline constexpr Point drop = {1089.0000f, 1537.0000f, 24.9390f, 3.1400f};
inline constexpr Point discord = {735.0000f, 1410.0000f, -12.0316f, 3.1400f};
inline constexpr Point karrgonn = {741.0000f, 1414.0000f, -12.6196f, 3.1400f};
inline constexpr Point azennios = {735.0000f, 1410.0000f, -12.0316f, 3.1400f};
inline constexpr Point garnoth = {720.0000f, 1480.0000f, -16.5017f, 3.1400f};
inline constexpr Point okrog = {735.0000f, 1555.0000f, -22.4066f, 3.1400f};
inline constexpr Point podium = {895.0000f, 1675.0000f, -19.5937f, 3.1400f};
inline constexpr Point crowd_a = {897.0000f, 1678.0000f, -19.7074f, 3.1400f};
inline constexpr Point crowd_b = {900.0000f, 1677.0000f, -19.5802f, 3.1400f};
inline constexpr Point crowd_c = {900.0000f, 1680.0000f, -19.4863f, 3.1400f};
inline constexpr Point buyers = {732.0000f, 1404.0000f, -11.8936f, 3.1400f};
inline constexpr Point restraint = {892.0000f, 1682.0000f, -19.7870f, 3.1400f};
inline constexpr Point escape_a = {922.4380f, 1679.2400f, -15.9204f, 3.1400f};
inline constexpr Point escape_b = {985.0000f, 1625.0000f, 6.2190f, 3.1400f};
inline constexpr Point escape_c = {1050.0000f, 1550.0000f, 21.7871f, 3.1400f};
inline constexpr Point flower_0 = {776.0000f, 1588.0000f, -29.0848f, 3.1400f};
inline constexpr Point flower_1 = {790.0000f, 1580.0000f, -29.3460f, 3.1400f};
inline constexpr Point flower_2 = {805.0000f, 1590.0000f, -29.1135f, 3.1400f};
inline constexpr Point flower_3 = {782.0000f, 1603.0000f, -30.4614f, 3.1400f};
inline constexpr Point flower_4 = {798.0000f, 1608.0000f, -30.9879f, 3.1400f};
inline constexpr Point flower_5 = {774.0000f, 1620.0000f, -32.1311f, 3.1400f};
inline constexpr Point flower_6 = {808.0000f, 1625.0000f, -29.3217f, 3.1400f};
inline constexpr Point flower_7 = {790.0000f, 1638.0000f, -33.0936f, 3.1400f};
inline constexpr Point smolderos = {784.0000f, 1628.0000f, -33.9268f, 3.1400f};
inline constexpr Point fire_0 = {650.0000f, 1627.0000f, -18.3044f, 3.1400f};
inline constexpr Point fire_1 = {824.0000f, 1669.0000f, -28.4060f, 3.1400f};
inline constexpr Point fire_2 = {819.0000f, 1682.0000f, -26.4018f, 3.1400f};
inline constexpr Point fire_3 = {839.0000f, 1679.0000f, -25.5763f, 3.1400f};
inline constexpr Point fire_4 = {852.0000f, 1697.0000f, -22.1805f, 3.1400f};
inline constexpr Point fire_5 = {825.0000f, 1694.0000f, -24.3259f, 3.1400f};
inline constexpr Point fire_6 = {810.0000f, 1672.0000f, -29.0308f, 3.1400f};
inline constexpr Point fire_7 = {844.0000f, 1712.0000f, -20.6457f, 3.1400f};
inline constexpr Point failed_0 = {600.0000f, 1648.0000f, -14.6094f, 3.1400f};
inline constexpr Point failed_1 = {600.0000f, 1654.0000f, -15.6629f, 3.1400f};
inline constexpr Point failed_2 = {880.0000f, 1527.0000f, -16.2161f, 3.1400f};
inline constexpr Point failed_3 = {885.0000f, 1541.0000f, -18.6750f, 3.1400f};
inline constexpr Point failed_4 = {842.0000f, 1548.0000f, -23.4771f, 3.1400f};
inline constexpr Point horrorguard_0 = {810.0000f, 1815.0000f, -11.7856f, 3.1400f};
inline constexpr Point horrorguard_1 = {888.0000f, 1683.0000f, -19.8491f, 3.1400f};
inline constexpr Point horrorguard_2 = {804.0000f, 1740.0000f, -20.7443f, 3.1400f};
inline constexpr Point horrorguard_3 = {827.0000f, 1748.0000f, -17.9652f, 3.1400f};
inline constexpr Point horrorguard_4 = {794.0000f, 1754.0000f, -19.5734f, 3.1400f};
inline constexpr Point horrorguard_5 = {821.0000f, 1757.0000f, -17.2247f, 3.1400f};
inline constexpr Point horrorguard_6 = {790.0000f, 1734.0000f, -20.4124f, 3.1400f};
inline constexpr Point horrorguard_7 = {832.0000f, 1729.0000f, -17.3188f, 3.1400f};
inline constexpr Point horrorguard_8 = {807.0000f, 1771.0000f, -15.7415f, 3.1400f};
inline constexpr Point horrorguard_9 = {829.0000f, 1774.0000f, -13.3625f, 3.1400f};
inline constexpr Point guard_0 = {643.0000f, 1627.0000f, -17.7775f, 3.1400f};
inline constexpr Point guard_1 = {633.0000f, 1627.0000f, -17.6110f, 3.1400f};
inline constexpr Point scout_0 = {638.0000f, 1627.0000f, -17.7647f, 3.1400f};
inline constexpr Point scout_1 = {640.0000f, 1629.0000f, -17.7004f, 3.1400f};
inline constexpr Point matriarch = {955.0000f, 1570.0000f, -10.1519f, 3.1400f};
inline constexpr Point dezco = {-3970.0000f, -3350.0000f, 39.3428f, 3.1400f};
inline constexpr Point garnoth_foe = {724.0000f, 1482.0000f, -17.1534f, 3.1400f};
inline constexpr Point hideout = {590.0000f, 1630.0000f, -12.7718f, 3.1400f};
inline constexpr Point discord_exit = {767.0000f, 1421.0000f, -14.5208f, 3.1400f};
inline constexpr Point okrog_exit = {758.0000f, 1570.0000f, -25.8344f, 3.1400f};
inline constexpr Point fire_chaser = {651.0000f, 1620.0000f, -18.9095f, 3.1400f};
inline constexpr Point supplicant_d = {648.0000f, 1634.0000f, -17.7190f, 3.1400f};
inline constexpr Point lodestone_0 = {591.0000f, 1639.0000f, -11.5777f, 3.1400f};
inline constexpr Point lodestone_1 = {610.0000f, 1662.0000f, -16.6698f, 3.1400f};
inline constexpr Point lodestone_2 = {636.0000f, 1680.0000f, -17.7263f, 3.1400f};
inline constexpr Point lodestone_3 = {661.0000f, 1666.0000f, -20.7442f, 3.1400f};
inline constexpr Point lodestone_4 = {677.0000f, 1640.0000f, -21.5056f, 3.1400f};
inline constexpr Point basilisk_0 = {728.0000f, 1745.0000f, -22.0635f, 3.1400f};
inline constexpr Point basilisk_1 = {745.0000f, 1770.0000f, -18.4009f, 3.1400f};
inline constexpr Point basilisk_2 = {758.0000f, 1744.0000f, -20.8965f, 3.1400f};
inline constexpr Point basilisk_3 = {784.0000f, 1758.0000f, -19.0654f, 3.1400f};
inline constexpr Point basilisk_4 = {782.0000f, 1737.0000f, -21.5910f, 3.1400f};
}

inline constexpr std::array<Point, 4> Course =
{
    Locations::check_a, Locations::check_b, Locations::check_c, Locations::check_d
};

inline constexpr std::array<Point, 3> DogStations =
{
    Locations::dog_a, Locations::dog_b, Locations::dog_c
};

inline constexpr std::array<Point, 4> EscapeRoute =
{
    Locations::escape_a, Locations::escape_b, Locations::escape_c, Locations::refuge
};

struct QuestSupply
{
    std::uint32_t quest;
    std::array<std::uint32_t, 3> items;
};

inline constexpr std::array<QuestSupply, 13> Supplies =
{{
    {QUEST_SIGNED, {ITEM_BLACKJACK, 0, 0}},
    {QUEST_IDENTITY, {ITEM_IDENTITY, 0, 0}},
    {QUEST_WASTE, {ITEM_GEM, 0, 0}},
    {QUEST_LABOR, {ITEM_PICK, 0, 0}},
    {QUEST_MENTAL, {ITEM_ORB, 0, 0}},
    {QUEST_DOG, {ITEM_LEASH, 0, 0}},
    {QUEST_GRUDGE, {ITEM_LEASH, ITEM_COLLAR, 0}},
    {QUEST_DISCORD, {ITEM_KEY, 0, 0}},
    {QUEST_GREATER, {ITEM_TALISMAN, ITEM_ASCENDANT_STRIKE, ITEM_FLAME_SHIELD}},
    {QUEST_WRITING, {ITEM_NOTES, 0, 0}},
    {QUEST_SPEECH, {ITEM_NOTES, 0, 0}},
    {QUEST_RIOT, {ITEM_KEY, 0, 0}},
    {QUEST_LETTER, {ITEM_LETTER, 0, 0}},
}};

inline constexpr std::array<std::uint32_t, 23> Quests =
{
    QUEST_SIGNED, QUEST_IDENTITY, QUEST_FIRE, QUEST_BLOOM, QUEST_WASTE, QUEST_TRAINING, QUEST_LABOR, QUEST_AGILITY, QUEST_MENTAL, QUEST_MERCY, QUEST_DOG, QUEST_COLLAR, QUEST_GRUDGE, QUEST_INTELLIGENCE, QUEST_DISCORD, QUEST_GREATER, QUEST_TERRITORY, QUEST_WRITING, QUEST_HEAD, QUEST_SPEECH, QUEST_RIOT, QUEST_BUYERS, QUEST_LETTER
};
inline constexpr std::array<std::uint32_t, 23> PersonalEntries =
{
    NPC_JAROD_FREE, NPC_RECRUIT, NPC_SUPPLICANT_A, NPC_SUPPLICANT_B, NPC_SUPPLICANT_C, NPC_HOUND, NPC_ORB, NPC_CROWD, NPC_OGRE, NPC_KARRGONN, NPC_AZENNIOS, NPC_GARNOTH, NPC_GROMMKO, NPC_OKROG, NPC_RESTRAINT, NPC_ENFORCER, NPC_SCENE, NPC_FIRE, NPC_HORRORGUARD, NPC_BUTCHER, NPC_SUPPLICANT_D, NPC_ORTELL_SCENE, NPC_BLAZING_TRAINER
};
}

#endif
